CREATE TABLE IF NOT EXISTS irregular_verbs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  base TEXT NOT NULL,
  past TEXT NOT NULL,
  past_participle TEXT NOT NULL,
  meaning TEXT NOT NULL,
  example_base TEXT,
  example_past TEXT,
  example_participle TEXT,
  level TEXT NOT NULL DEFAULT 'intermediate',
  created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now'))
);

INSERT INTO irregular_verbs (base, past, past_participle, meaning, example_base, example_past, example_participle, level) VALUES
('be', 'was/were', 'been', 'être', 'I am happy today.', 'She was late yesterday.', 'They have been friends for years.', 'beginner'),
('have', 'had', 'had', 'avoir', 'I have a car.', 'He had breakfast at 8 AM.', 'We have had this house since 2010.', 'beginner'),
('do', 'did', 'done', 'faire', 'What do you do for a living?', 'She did her homework last night.', 'I have done the dishes.', 'beginner'),
('go', 'went', 'gone', 'aller', 'I go to school every day.', 'They went to Paris last summer.', 'She has gone to the market.', 'beginner'),
('come', 'came', 'come', 'venir', 'Please come to my party.', 'He came home late.', 'They have come a long way.', 'beginner'),
('see', 'saw', 'seen', 'voir', 'I see what you mean.', 'We saw a great movie.', 'I have never seen such beauty.', 'beginner'),
('take', 'took', 'taken', 'prendre', 'I take the bus to work.', 'She took a photo.', 'He has taken my book.', 'beginner'),
('get', 'got', 'got/gotten', 'obtenir', 'I get up early.', 'He got a new job.', 'I have got/gotten used to it.', 'beginner'),
('make', 'made', 'made', 'faire / fabriquer', 'I make dinner every evening.', 'She made a mistake.', 'He has made progress.', 'beginner'),
('know', 'knew', 'known', 'savoir / connaître', 'I know the answer.', 'She knew him well.', 'I have known her since childhood.', 'beginner'),
('think', 'thought', 'thought', 'penser', 'I think you are right.', 'He thought about it.', 'I have thought of a solution.', 'intermediate'),
('say', 'said', 'said', 'dire', 'What did you say?', 'She said hello.', 'I have said this before.', 'beginner'),
('tell', 'told', 'told', 'dire / raconter', 'I tell the truth.', 'He told me a story.', 'She has told everyone.', 'beginner'),
('give', 'gave', 'given', 'donner', 'I give him a gift.', 'She gave me advice.', 'He has given his best.', 'beginner'),
('find', 'found', 'found', 'trouver', 'I find it interesting.', 'She found her keys.', 'We have found a solution.', 'beginner'),
('feel', 'felt', 'felt', 'sentir', 'I feel great today.', 'She felt sick yesterday.', 'I have felt better.', 'intermediate'),
('become', 'became', 'become', 'devenir', 'I want to become a doctor.', 'He became famous.', 'She has become more confident.', 'intermediate'),
('begin', 'began', 'begun', 'commencer', 'Classes begin at 9 AM.', 'The movie began late.', 'It has begun to rain.', 'intermediate'),
('break', 'broke', 'broken', 'casser / briser', 'Be careful not to break it.', 'He broke his leg.', 'The window has been broken.', 'intermediate'),
('bring', 'brought', 'brought', 'apporter', 'I bring my lunch.', 'She brought a friend.', 'He has brought good news.', 'intermediate'),
('build', 'built', 'built', 'construire', 'They build houses.', 'He built a treehouse.', 'We have built a strong team.', 'intermediate'),
('buy', 'bought', 'bought', 'acheter', 'I buy groceries on Saturdays.', 'She bought a new dress.', 'He has bought a car.', 'beginner'),
('catch', 'caught', 'caught', 'attraper', 'I catch the ball.', 'The dog caught the stick.', 'She has caught a cold.', 'intermediate'),
('choose', 'chose', 'chosen', 'choisir', 'I choose the red one.', 'He chose the wrong path.', 'She has chosen her career.', 'intermediate'),
('cost', 'cost', 'cost', 'coûter', 'This shirt costs 20 euros.', 'The trip cost a lot.', 'The repair has cost too much.', 'intermediate'),
('cut', 'cut', 'cut', 'couper', 'I cut the vegetables.', 'She cut her finger.', 'He has cut the paper.', 'intermediate'),
('draw', 'drew', 'drawn', 'dessiner / tirer', 'I draw every weekend.', 'She drew a beautiful picture.', 'He has drawn the curtains.', 'intermediate'),
('drive', 'drove', 'driven', 'conduire', 'I drive to work.', 'He drove too fast.', 'She has driven across Europe.', 'intermediate'),
('eat', 'ate', 'eaten', 'manger', 'I eat healthy food.', 'She ate an apple.', 'He has eaten already.', 'beginner'),
('fall', 'fell', 'fallen', 'tomber', 'Leaves fall in autumn.', 'He fell off his bike.', 'She has fallen asleep.', 'intermediate'),
('fly', 'flew', 'flown', 'voler', 'Birds fly south in winter.', 'The plane flew to London.', 'He has flown many times.', 'intermediate'),
('forget', 'forgot', 'forgotten', 'oublier', 'I never forget a face.', 'She forgot her keys.', 'He has forgotten the password.', 'intermediate'),
('forgive', 'forgave', 'forgiven', 'pardonner', 'I forgive you.', 'She forgave him.', 'He has forgiven her mistake.', 'advanced'),
('freeze', 'froze', 'frozen', 'geler', 'Water freezes at 0°C.', 'The lake froze overnight.', 'The meat has frozen solid.', 'intermediate'),
('grow', 'grew', 'grown', 'grandir / cultiver', 'Plants grow fast in spring.', 'He grew up in Paris.', 'She has grown into a leader.', 'intermediate'),
('hide', 'hid', 'hidden', 'cacher', 'I hide the presents.', 'She hid the letter.', 'The treasure has been hidden.', 'intermediate'),
('hit', 'hit', 'hit', 'frapper', 'I hit the target.', 'He hit the ball hard.', 'She has hit a record.', 'intermediate'),
('hold', 'held', 'held', 'tenir', 'I hold your hand.', 'She held the door open.', 'He has held the position for years.', 'intermediate'),
('hurt', 'hurt', 'hurt', 'blesser / faire mal', 'My head hurts.', 'She hurt her ankle.', 'He has hurt his back.', 'intermediate'),
('keep', 'kept', 'kept', 'garder', 'I keep a diary.', 'She kept her promise.', 'He has kept the secret.', 'intermediate'),
('lead', 'led', 'led', 'mener / diriger', 'I lead the team.', 'She led the project.', 'He has led the company.', 'intermediate'),
('leave', 'left', 'left', 'quitter / laisser', 'I leave at 6 PM.', 'She left her phone.', 'He has left the country.', 'intermediate'),
('lend', 'lent', 'lent', 'prêter', 'I lend him my notes.', 'She lent me money.', 'He has lent his car.', 'intermediate'),
('let', 'let', 'let', 'laisser / permettre', 'I let him decide.', 'She let the cat out.', 'He has let the opportunity go.', 'intermediate'),
('lie', 'lay', 'lain', 'être allongé', 'I lie on the grass.', 'He lay on the sofa.', 'She has lain in bed all day.', 'advanced'),
('light', 'lit/lighted', 'lit/lighted', 'allumer', 'I light candles.', 'She lit the fire.', 'He has lit the way.', 'intermediate'),
('lose', 'lost', 'lost', 'perdre', 'I lose my keys often.', 'She lost the game.', 'He has lost his mind.', 'beginner'),
('mean', 'meant', 'meant', 'signifier', 'What does this mean?', 'She meant to call you.', 'I have meant to do this.', 'intermediate'),
('meet', 'met', 'met', 'rencontrer', 'I meet new people daily.', 'She met him at a party.', 'We have met before.', 'beginner'),
('pay', 'paid', 'paid', 'payer', 'I pay in cash.', 'She paid the bill.', 'He has paid the fine.', 'beginner'),
('put', 'put', 'put', 'mettre / poser', 'I put the book on the shelf.', 'She put on her coat.', 'He has put effort into it.', 'intermediate'),
('read', 'read', 'read', 'lire', 'I read every night.', 'She read the instructions.', 'He has read the report.', 'beginner'),
('ride', 'rode', 'ridden', 'monter / rouler', 'I ride my bike.', 'She rode a horse.', 'He has ridden the subway.', 'intermediate'),
('ring', 'rang', 'rung', 'sonner', 'The bells ring loudly.', 'She rang the doorbell.', 'He has rung twice.', 'intermediate'),
('rise', 'rose', 'risen', 'se lever / monter', 'The sun rises early.', 'Prices rose sharply.', 'He has risen to the challenge.', 'advanced'),
('run', 'ran', 'run', 'courir', 'I run every morning.', 'She ran a marathon.', 'He has run out of time.', 'beginner'),
('sell', 'sold', 'sold', 'vendre', 'I sell handmade jewelry.', 'She sold her car.', 'He has sold the house.', 'beginner'),
('send', 'sent', 'sent', 'envoyer', 'I send emails daily.', 'She sent a message.', 'He has sent the package.', 'beginner'),
('shine', 'shone', 'shone', 'briller', 'The sun shines brightly.', 'The moon shone that night.', 'She has shone in her role.', 'advanced'),
('shoot', 'shot', 'shot', 'tirer / filmer', 'I shoot videos.', 'He shot the arrow.', 'She has shot three films.', 'advanced'),
('show', 'showed', 'shown/showed', 'montrer', 'I show my work.', 'She showed me the way.', 'He has shown great skill.', 'beginner'),
('shut', 'shut', 'shut', 'fermer', 'I shut the door quietly.', 'She shut her eyes.', 'He has shut down the computer.', 'intermediate'),
('sing', 'sang', 'sung', 'chanter', 'I sing in the shower.', 'She sang beautifully.', 'He has sung opera.', 'intermediate'),
('sink', 'sank', 'sunk', 'couler', 'The boat sinks slowly.', 'The ship sank in 1912.', 'He has sunk all his money.', 'advanced'),
('sit', 'sat', 'sat', 's''asseoir', 'I sit by the window.', 'She sat on the chair.', 'He has sat there for hours.', 'beginner'),
('sleep', 'slept', 'slept', 'dormir', 'I sleep eight hours.', 'She slept well.', 'He has slept in.', 'beginner'),
('speak', 'spoke', 'spoken', 'parler', 'I speak three languages.', 'She spoke to the manager.', 'He has spoken out.', 'beginner'),
('spend', 'spent', 'spent', 'dépenser / passer', 'I spend time with family.', 'She spent all her savings.', 'He has spent years on it.', 'intermediate'),
('stand', 'stood', 'stood', 'se tenir debout', 'I stand in line.', 'She stood up abruptly.', 'He has stood by his word.', 'intermediate'),
('steal', 'stole', 'stolen', 'voler', 'They steal data.', 'He stole the painting.', 'She has stolen my heart.', 'advanced'),
('stick', 'stuck', 'stuck', 'coller / rester', 'The label sticks well.', 'He stuck the note on the fridge.', 'She has stuck to her plan.', 'advanced'),
('swim', 'swam', 'swum', 'nager', 'I swim every summer.', 'She swam across the lake.', 'He has swum in the ocean.', 'intermediate'),
('teach', 'taught', 'taught', 'enseigner', 'I teach English.', 'She taught him a lesson.', 'He has taught for 20 years.', 'intermediate'),
('tear', 'tore', 'torn', 'déchirer', 'Paper tears easily.', 'She tore the letter.', 'He has torn his ligament.', 'advanced'),
('throw', 'threw', 'thrown', 'jeter', 'I throw the ball.', 'She threw a party.', 'He has thrown away his chance.', 'intermediate'),
('wake', 'woke/waked', 'woken/waked', 'se réveiller', 'I wake up at 7 AM.', 'She woke up late.', 'He has woken the neighbors.', 'beginner'),
('wear', 'wore', 'worn', 'porter (vêtements)', 'I wear glasses.', 'She wore a red dress.', 'He has worn this shirt before.', 'intermediate'),
('win', 'won', 'won', 'gagner', 'I win sometimes.', 'She won the competition.', 'He has won three medals.', 'beginner'),
('write', 'wrote', 'written', 'écrire', 'I write in my journal.', 'She wrote a novel.', 'He has written many articles.', 'beginner');
