CREATE TABLE IF NOT EXISTS phrasal_verbs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  verb TEXT NOT NULL,
  particle TEXT NOT NULL,
  meaning TEXT NOT NULL,
  example TEXT,
  level TEXT CHECK(level IN ('beginner', 'intermediate', 'advanced')) DEFAULT 'beginner'
);

INSERT INTO phrasal_verbs (verb, particle, meaning, example, level) VALUES
('get', 'up', 'se lever', 'I get up at 7 AM every day.', 'beginner'),
('look', 'for', 'chercher', 'I am looking for my keys.', 'beginner'),
('turn', 'on', 'allumer', 'Please turn on the light.', 'beginner'),
('turn', 'off', 'éteindre', 'Turn off the TV before bed.', 'beginner'),
('pick', 'up', 'prendre, récupérer', 'I will pick you up at 5.', 'beginner'),
('put', 'on', 'mettre (vêtements)', 'Put on your jacket, it is cold.', 'beginner'),
('take', 'off', 'enlever (vêtements), décoller', 'The plane took off on time.', 'beginner'),
('call', 'back', 'rappeler', 'I will call you back later.', 'beginner'),
('sit', 'down', 's''asseoir', 'Please sit down and relax.', 'beginner'),
('stand', 'up', 'se lever, se tenir debout', 'Everyone stood up for the national anthem.', 'beginner'),
('wake', 'up', 'se réveiller', 'I wake up early on weekends.', 'beginner'),
('clean', 'up', 'nettoyer', 'We need to clean up the kitchen.', 'beginner'),
('fill', 'out', 'remplir (formulaire)', 'Fill out this form, please.', 'beginner'),
('give', 'back', 'rendre', 'Give me back my book!', 'beginner'),
('hang', 'up', 'raccrocher (téléphone)', 'She hung up on me.', 'beginner'),
('hold', 'on', 'attendre (au téléphone)', 'Hold on, I will check.', 'beginner'),
('write', 'down', 'noter, écrire', 'Write down the address.', 'beginner'),
('find', 'out', 'découvrir', 'I found out the truth yesterday.', 'intermediate'),
('give', 'up', 'abandonner', 'Don''t give up on your dreams.', 'intermediate'),
('look', 'after', 's''occuper de', 'Can you look after my cat?', 'intermediate'),
('look', 'forward to', 'attendre avec impatience', 'I look forward to meeting you.', 'intermediate'),
('put', 'off', 'remettre à plus tard', 'Don''t put off your homework.', 'intermediate'),
('run', 'out of', 'manquer de', 'We ran out of milk this morning.', 'intermediate'),
('set', 'up', 'installer, organiser', 'We need to set up the equipment.', 'intermediate'),
('take', 'care of', 's''occuper de', 'Take care of yourself.', 'intermediate'),
('try', 'on', 'essayer (vêtements)', 'Try on these shoes.', 'intermediate'),
('work', 'out', 'faire de l''exercice, résoudre', 'I work out every morning.', 'intermediate'),
('break', 'down', 'tomber en panne, s''effondrer', 'My car broke down on the highway.', 'intermediate'),
('bring', 'up', 'élever (enfant), soulever (sujet)', 'She brought up an interesting point.', 'intermediate'),
('carry', 'on', 'continuer', 'Carry on with your work.', 'intermediate'),
('catch', 'up', 'rattraper (son retard)', 'I need to catch up on sleep.', 'intermediate'),
('come', 'across', 'tomber sur par hasard', 'I came across an old photo.', 'intermediate'),
('come', 'up with', 'trouver (une idée)', 'She came up with a great idea.', 'intermediate'),
('cut', 'down on', 'réduire', 'I need to cut down on sugar.', 'intermediate'),
('deal', 'with', 'gérer, traiter', 'I will deal with this problem.', 'intermediate'),
('drop', 'off', 'déposer (quelqu''un)', 'I will drop you off at school.', 'intermediate'),
('end', 'up', 'finir par', 'We ended up staying home.', 'intermediate'),
('fall', 'out', 'se disputer', 'They fell out over money.', 'intermediate'),
('figure', 'out', 'comprendre, résoudre', 'I can''t figure out this puzzle.', 'intermediate'),
('get', 'along with', 's''entendre avec', 'Do you get along with him?', 'intermediate'),
('get', 'rid of', 'se débarrasser de', 'Get rid of those old clothes.', 'intermediate'),
('go', 'over', 'réviser, revoir', 'Let''s go over the plan.', 'intermediate'),
('keep', 'up with', 'suivre le rythme de', 'I can''t keep up with the news.', 'advanced'),
('make', 'up', 'inventer, se réconcilier, se maquiller', 'They made up after the fight.', 'advanced'),
('pull', 'through', 's''en sortir (maladie)', 'He pulled through after surgery.', 'advanced'),
('put', 'up with', 'supporter, tolérer', 'I can''t put up with the noise.', 'advanced'),
('run', 'into', 'rencontrer par hasard', 'I ran into an old friend.', 'advanced'),
('set', 'off', 'partir, déclencher', 'We set off early in the morning.', 'advanced'),
('show', 'off', 'se vanter, faire étalage', 'Stop showing off!', 'advanced'),
('sort', 'out', 'résoudre, organiser', 'We need to sort out this mess.', 'advanced'),
('speak', 'up', 'parler plus fort', 'Speak up, I can''t hear you.', 'advanced'),
('take', 'after', 'tenir de (un parent)', 'She takes after her mother.', 'advanced'),
('take', 'on', 'accepter (défi), embaucher', 'We are taking on new staff.', 'advanced'),
('turn', 'around', 'faire demi-tour, inverser', 'The company turned around last year.', 'advanced'),
('turn', 'down', 'refuser, baisser (volume)', 'They turned down my offer.', 'advanced'),
('turn', 'into', 'se transformer en', 'The frog turned into a prince.', 'advanced'),
('turn', 'up', 'augmenter (volume), arriver', 'Turn up the music!', 'advanced'),
('wear', 'off', 's''estomper, s''atténuer', 'The pain will wear off soon.', 'advanced'),
('work', 'on', 'travailler sur', 'I am working on a new project.', 'beginner');
