CREATE TABLE IF NOT EXISTS grammar_lessons (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  content TEXT NOT NULL,
  category TEXT DEFAULT 'general',
  level TEXT CHECK(level IN ('A1','A2','B1','B2','C1','C2')) DEFAULT 'B1',
  order_index INTEGER DEFAULT 0,
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS grammar_exercises (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  lesson_id INTEGER NOT NULL,
  type TEXT CHECK(type IN ('qcm','fill_blank','reorder','match')) NOT NULL,
  question TEXT NOT NULL,
  options TEXT,
  correct_answer TEXT NOT NULL,
  explanation TEXT,
  points INTEGER DEFAULT 1,
  order_index INTEGER DEFAULT 0,
  FOREIGN KEY (lesson_id) REFERENCES grammar_lessons(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS grammar_progress (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  lesson_id INTEGER NOT NULL UNIQUE,
  completed INTEGER DEFAULT 0,
  score INTEGER DEFAULT 0,
  total INTEGER DEFAULT 0,
  last_exercise_id INTEGER,
  completed_at INTEGER,
  FOREIGN KEY (lesson_id) REFERENCES grammar_lessons(id) ON DELETE CASCADE
);

INSERT INTO grammar_lessons (id, title, slug, description, content, category, level, order_index, created_at) VALUES
(1, 'Présent simple - Formation et usage', 'present-simple', 'Le présent simple sert à exprimer des habitudes, des vérités générales et des faits permanents.', '<h3>Formation</h3><p>Base verbale (+ <i>-s</i> à la 3e personne du singulier).</p><h3>Usage</h3><ul><li>Habitudes : <i>I drink coffee every morning.</i></li><li>Vérités générales : <i>The sun rises in the east.</i></li><li>Programmes fixes : <i>The train leaves at 8 PM.</i></li></ul><h3>Signal words</h3><p>always, usually, often, sometimes, never, every day</p>', 'temps', 'A1', 1, 1718380800000),
(2, 'Présent simple - 3e personne', 'present-simple-third', 'Les règles spéciales pour conjuguer les verbes à la 3e personne du singulier.', '<h3>Règles</h3><ul><li>général : +<i>s</i> → <i>work → works</i></li><li>-ch, -sh, -ss, -x, -o, -z : +<i>es</i> → <i>watch → watches</i></li><li>consonne + y : <i>-y → ies</i> → <i>study → studies</i></li></ul><h3>Exceptions</h3><p><i>have → has, be → is</i></p>', 'temps', 'A1', 2, 1718380800000),
(3, 'Présent continu - Formation et usage', 'present-continuous', 'Le présent continu exprime une action en cours au moment où l''on parle.', '<h3>Formation</h3><p><i>am/is/are</i> + base verbale + <i>-ing</i></p><h3>Usage</h3><ul><li>Action en cours : <i>I am reading right now.</i></li><li>Changement : <i>The climate is getting warmer.</i></li><li>Plan proche : <i>I am meeting him tomorrow.</i></li></ul>', 'temps', 'A1', 3, 1718380800000),
(4, 'Présent simple vs Présent continu', 'present-simple-vs-continuous', 'Distinguer quand utiliser le présent simple et le présent continu.', '<h3>Différences clés</h3><ul><li>Simple = habitudes, vérités permanentes : <i>I work in Paris.</i></li><li>Continu = actions en cours, temporaires : <i>I am working from home this week.</i></li></ul><h3>Verbes d''état</h3><p>love, hate, know, want, need, belong → PAS de continu</p>', 'temps', 'A2', 4, 1718380800000),
(5, 'Prétérit simple - Formation régulière', 'past-simple-regular', 'Le prétérit simple exprime une action terminée dans le passé.', '<h3>Formation régulière</h3><p>Base verbale + <i>-ed</i></p><ul><li>général : <i>walk → walked</i></li><li>-e : +<i>d</i> → <i>live → lived</i></li><li>consonne + y : <i>-y → ied</i> → <i>try → tried</i></li></ul><h3>Signal words</h3><p>yesterday, last week, ago, in 2010</p>', 'temps', 'A1', 5, 1718380800000),
(6, 'Prétérit simple - Verbes irréguliers courants', 'past-simple-irregular', 'Les verbes irréguliers les plus fréquents au prétérit simple.', '<h3>Tableau des irréguliers courants</h3><ul><li><i>be → was/were</i></li><li><i>have → had</i></li><li><i>do → did</i></li><li><i>go → went</i></li><li><i>make → made</i></li><li><i>take → took</i></li><li><i>see → saw</i></li><li><i>come → came</i></li><li><i>know → knew</i></li><li><i>think → thought</i></li></ul>', 'temps', 'A2', 6, 1718380800000),
(7, 'Prétérit continu', 'past-continuous', 'Le prétérit continu décrit une action en cours à un moment précis du passé.', '<h3>Formation</h3><p><i>was/were</i> + base verbale + <i>-ing</i></p><h3>Usage</h3><ul><li>Action interrompue : <i>I was reading when she called.</i></li><li>Deux actions simultanées : <i>While I was cooking, he was watching TV.</i></li><li>Contexte d''une histoire : <i>The wind was blowing.</i></li></ul>', 'temps', 'A2', 7, 1718380800000),
(8, 'Prétérit simple vs continu', 'past-simple-vs-continuous', 'Choisir entre le prétérit simple et le prétérit continu.', '<h3>Différences</h3><ul><li>Simple = action terminée, ponctuelle : <i>I broke the window.</i></li><li>Continu = action en cours, plus longue : <i>I was breaking the window when he saw me.</i></li></ul><h3>Combiné</h3><p>Continu (action longue) + simple (interruption) : <i>I was walking when it started to rain.</i></p>', 'temps', 'B1', 8, 1718380800000),
(9, 'Present perfect simple', 'present-perfect', 'Le present perfect relie le passé au présent.', '<h3>Formation</h3><p><i>have/has</i> + participe passé</p><h3>Usage</h3><ul><li>Expérience de vie : <i>I have visited Japan.</i></li><li>Changement récent : <i>She has lost weight.</i></li><li>Action qui continue : <i>I have lived here for 5 years.</i></li></ul><h3>Signal words</h3><p>ever, never, already, yet, just, since, for</p>', 'temps', 'A2', 9, 1718380800000),
(10, 'Present perfect - Since vs For', 'present-perfect-since-for', 'Distinguer since (point précis) et for (durée).', '<h3>Since</h3><p>Indique le <b>début</b> d''une période : <i>since 2010, since Monday</i></p><h3>For</h3><p>Indique une <b>durée</b> : <i>for two hours, for 5 years</i></p><h3>Exemples</h3><ul><li><i>I have known her since 2015.</i></li><li><i>I have known her for 8 years.</i></li></ul>', 'temps', 'A2', 10, 1718380800000),
(11, 'Present perfect continu', 'present-perfect-continuous', 'Le present perfect continu met l''accent sur la durée d''une action.', '<h3>Formation</h3><p><i>have/has been</i> + base verbale + <i>-ing</i></p><h3>Usage</h3><ul><li>Action commencée dans le passé qui continue : <i>I have been studying for 3 hours.</i></li><li>Action récente avec résultat visible : <i>Why are you wet? I have been walking in the rain.</i></li></ul><h3>Simple vs Continu</h3><p>Simple = résultat ; Continu = processus</p>', 'temps', 'B1', 11, 1718380800000),
(12, 'Past perfect simple', 'past-perfect', 'Le past perfect exprime une action antérieure à une autre action passée.', '<h3>Formation</h3><p><i>had</i> + participe passé</p><h3>Usage</h3><ul><li>Action antérieure dans le passé : <i>When I arrived, the train had already left.</i></li><li>Avec <i>before, after, when</i></li></ul>', 'temps', 'B1', 12, 1718380800000),
(13, 'Futur - Will et Be going to', 'future-will-going-to', 'Deux façons d''exprimer le futur en anglais.', '<h3>Will</h3><ul><li>Décision spontanée : <i>I will help you.</i></li><li>Prédiction (opinion) : <i>I think it will rain tomorrow.</i></li><li>Promesse : <i>I will call you tonight.</i></li></ul><h3>Be going to</h3><ul><li>Plan/intention : <i>I am going to buy a car.</i></li><li>Prédiction (signes évidents) : <i>Look at those clouds! It is going to rain.</i></li></ul>', 'temps', 'A2', 13, 1718380800000),
(14, 'Futur continu et Futur perfect', 'future-continuous-perfect', 'Deux formes avancées du futur.', '<h3>Futur continu</h3><p><i>will be</i> + <i>-ing</i> : <i>This time tomorrow, I will be flying to Paris.</i></p><h3>Futur perfect</h3><p><i>will have</i> + participe passé : <i>By 2026, I will have finished my studies.</i></p><h3>Signal words</h3><p>by, by the time, this time tomorrow</p>', 'temps', 'B2', 14, 1718380800000),
(15, 'Révision des temps du passé', 'past-tenses-review', 'Tableau comparatif de tous les temps du passé.', '<h3>Tableau récapitulatif</h3><ul><li>Prétérit simple : action terminée → <i>I saw a film.</i></li><li>Prétérit continu : action en cours → <i>I was watching TV.</i></li><li>Present perfect : lien passé-présent → <i>I have seen it twice.</i></li><li>Past perfect : antériorité → <i>I had left before he came.</i></li></ul>', 'temps', 'B1', 15, 1718380800000),
(16, 'Can et Could', 'can-could', 'Can et could expriment la capacité, la possibilité et la permission.', '<h3>Can</h3><ul><li>Capacité : <i>I can swim.</i></li><li>Possibilité : <i>It can get cold at night.</i></li><li>Permission : <i>Can I use your phone?</i></li></ul><h3>Could</h3><ul><li>Passé de can : <i>I could run faster when I was young.</i></li><li>Possibilité hypothétique : <i>It could rain tomorrow.</i></li><li>Demande polie : <i>Could you help me?</i></li></ul>', 'modaux', 'A1', 16, 1718380800000),
(17, 'Can/Could/Be able to', 'can-could-able-to', 'Quand utiliser can, could ou be able to ?', '<h3>Can</h3><p>Capacité générale, présent : <i>I can speak French.</i></p><h3>Could</h3><p>Capacité passée générale : <i>I could swim when I was five.</i></p><h3>Be able to / Manage to</h3><p>Réussite dans une situation particulière : <i>Everyone was able to escape.</i></p>', 'modaux', 'B1', 17, 1718380800000),
(18, 'Must et Have to', 'must-have-to', 'Must et have to expriment l''obligation avec une nuance différente.', '<h3>Must</h3><ul><li>Obligation subjective : <i>I must study. (Je me l''impose)</i></li><li>Déduction logique : <i>He must be tired.</i></li></ul><h3>Have to</h3><ul><li>Obligation externe : <i>I have to wear a uniform. (C''est le règlement)</i></li></ul>', 'modaux', 'A2', 18, 1718380800000),
(19, 'Mustn''t et Don''t have to', 'mustnt-dont-have-to', 'Ne pas confondre l''interdiction et l''absence d''obligation.', '<h3>Mustn''t</h3><p><b>Interdiction</b> : <i>You mustn''t smoke here.</i></p><h3>Don''t have to / Needn''t</h3><p><b>Absence d''obligation</b> : <i>You don''t have to come if you''re busy.</i></p>', 'modaux', 'B1', 19, 1718380800000),
(20, 'Should et Ought to', 'should-ought-to', 'Should et ought to servent à donner un conseil.', '<h3>Should</h3><ul><li>Conseil : <i>You should eat more vegetables.</i></li><li>Attente : <i>The train should arrive at 6 PM.</i></li><li>Regret : <i>I should have studied harder.</i></li></ul><h3>Ought to</h3><p>Même sens que should, plus formel : <i>You ought to apologize.</i></p>', 'modaux', 'A2', 20, 1718380800000),
(21, 'May et Might', 'may-might', 'May et might expriment la permission et la possibilité.', '<h3>Permission</h3><ul><li><i>May I come in?</i> (très formel)</li><li><i>Can I come in?</i> (courant)</li></ul><h3>Possibilité</h3><ul><li><i>It may rain tomorrow.</i> (50%)</li><li><i>It might rain tomorrow.</i> (moins probable)</li></ul><h3>Interdiction</h3><p><i>You may not enter.</i> (formel)</p>', 'modaux', 'B1', 21, 1718380800000),
(22, 'Shall et Will', 'shall-will', 'Shall et will pour le futur et les suggestions.', '<h3>Will</h3><p>Futur standard : <i>I will see you tomorrow.</i></p><h3>Shall</h3><ul><li>Suggestions avec <i>I</i> et <i>we</i> : <i>Shall we go?</i></li><li>Offres : <i>Shall I help you?</i></li><li>Promesses solennelles : <i>I shall return.</i></li></ul><p>Shall est plus rare aujourd''hui, surtout britannique.</p>', 'modaux', 'B1', 22, 1718380800000),
(23, 'Need et Dare', 'need-dare', 'Need et dare peuvent être modaux ou verbes ordinaires.', '<h3>Need</h3><p>Modal (surtout négatif) : <i>You needn''t worry.</i> (= don''t need to)</p><p>Verbe ordinaire : <i>You don''t need to come.</i></p><h3>Dare</h3><p>Modal : <i>Dare he contradict her?</i></p><p>Verbe ordinaire : <i>He doesn''t dare to speak.</i></p>', 'modaux', 'C1', 23, 1718380800000);

-- Exercices temps (1-15)
INSERT INTO grammar_exercises (lesson_id, type, question, options, correct_answer, explanation, points, order_index) VALUES
(1, 'qcm', 'She ___ to school every day.', '["go", "goes", "going", "went"]', 'goes', '3e personne du singulier → +s', 1, 1),
(1, 'fill_blank', 'Water ___ (boil) at 100 degrees Celsius.', NULL, 'boils', 'Vérité générale → présent simple', 1, 2),
(1, 'qcm', '___ you like pizza?', '["Do", "Does", "Are", "Is"]', 'Do', 'Sujet YOU → auxiliaire DO', 1, 3),
(2, 'qcm', 'He ___ TV every evening.', '["watch", "watchs", "watches", "watching"]', 'watches', 'ch + es', 1, 1),
(2, 'fill_blank', 'My baby brother ___ (cry) when he is hungry.', NULL, 'cries', 'consonne + y → ies', 1, 2),
(2, 'qcm', 'They ___ in a big house.', '["live", "lives", "living", "lived"]', 'live', 'Sujet THEY → base verbale', 1, 3),
(3, 'qcm', 'Look! The baby ___ .', '["sleep", "sleeps", "is sleeping", "sleeping"]', 'is sleeping', 'Action en cours → présent continu', 1, 1),
(3, 'fill_blank', 'Be quiet! I ___ (try) to concentrate.', NULL, 'am trying', 'Action en cours → be + V-ing', 1, 2),
(3, 'qcm', 'She ___ to Paris tomorrow.', '["flies", "is flying", "fly", "flew"]', 'is flying', 'Plan proche → présent continu', 1, 3),
(4, 'qcm', 'I ___ coffee every morning.', '["drink", "am drinking", "drinks", "drank"]', 'drink', 'Habitude → présent simple', 1, 1),
(4, 'qcm', 'Listen! Someone ___ the piano.', '["plays", "is playing", "play", "played"]', 'is playing', 'Action en cours → continu', 1, 2),
(4, 'fill_blank', 'I ___ (not/understand) this word.', NULL, 'do not understand', 'Verbe d''état → présent simple', 1, 3),
(5, 'qcm', 'Yesterday, I ___ a delicious cake.', '["eat", "eats", "ate", "eaten"]', 'ate', 'Yesterday → prétérit', 1, 1),
(5, 'fill_blank', 'She ___ (walk) to school last week.', NULL, 'walked', 'Régulier + ed', 1, 2),
(5, 'qcm', 'They ___ TV last night.', '["watch", "watched", "watching", "watches"]', 'watched', 'Last night → prétérit', 1, 3),
(6, 'qcm', 'He ___ to London last summer.', '["go", "goes", "went", "gone"]', 'went', 'Go → went (irrégulier)', 1, 1),
(6, 'fill_blank', 'She ___ (make) a beautiful cake yesterday.', NULL, 'made', 'Make → made (irrégulier)', 1, 2),
(6, 'qcm', 'I ___ that film before.', '["see", "saw", "seen", "seeing"]', 'saw', 'See → saw (irrégulier)', 1, 3),
(7, 'qcm', 'While I was cooking, he ___ TV.', '["watched", "was watching", "watching", "watches"]', 'was watching', 'Deux actions simultanées → continu', 1, 1),
(7, 'fill_blank', 'When the phone rang, I ___ (take) a shower.', NULL, 'was taking', 'Action interrompue → continu', 1, 2),
(7, 'qcm', 'What ___ you ___ at 8 PM yesterday?', '["did / do", "were / doing", "are / doing", "do / do"]', 'were / doing', 'Moment précis du passé → continu', 1, 3),
(8, 'qcm', 'I ___ a bike when I was young.', '["ride", "rode", "was riding", "ridden"]', 'rode', 'Action terminée → prétérit simple', 1, 1),
(8, 'qcm', 'While I ___ home, it started to rain.', '["walk", "walked", "was walking", "am walking"]', 'was walking', 'Action longue interrompue → continu', 1, 2),
(8, 'fill_blank', 'When I ___ (arrive), they ___ (already/leave).', NULL, 'arrived / had already left', 'Antériorité → past perfect', 1, 3),
(9, 'qcm', 'I ___ never ___ such a beautiful sunset.', '["have / seen", "had / seen", "saw", "see"]', 'have / seen', 'Expérience de vie → present perfect', 1, 1),
(9, 'fill_blank', 'She ___ (just/finish) her homework.', NULL, 'has just finished', 'Just → present perfect', 1, 2),
(9, 'qcm', '___ you ever ___ sushi?', '["Did / eat", "Have / eaten", "Do / eat", "Are / eating"]', 'Have / eaten', 'Ever → present perfect', 1, 3),
(10, 'qcm', 'I have lived here ___ 2010.', '["for", "since", "from", "during"]', 'since', 'Date précise → since', 1, 1),
(10, 'qcm', 'She has studied English ___ five years.', '["since", "for", "from", "during"]', 'for', 'Durée → for', 1, 2),
(10, 'fill_blank', 'They have been married ___ they were young.', NULL, 'since', 'Depuis quand → since', 1, 3),
(11, 'qcm', 'It ___ for three hours.', '["rains", "is raining", "has rained", "has been raining"]', 'has been raining', 'Focus durée → present perfect continu', 1, 1),
(11, 'fill_blank', 'How long ___ you ___ (wait) here?', NULL, 'have / been waiting', 'Question sur la durée → present perfect continu', 1, 2),
(11, 'qcm', 'I ___ the book. You can have it now.', '["have read", "have been reading", "read", "am reading"]', 'have read', 'Résultat terminé → present perfect simple', 1, 3),
(12, 'qcm', 'When I arrived, the train ___ already ___.', '["has / left", "had / left", "was / leaving", "left"]', 'had / left', 'Antériorité dans le passé', 1, 1),
(12, 'fill_blank', 'She ___ (never/see) a ghost before that night.', NULL, 'had never seen', 'Antériorité → past perfect', 1, 2),
(12, 'qcm', 'After he ___ his homework, he went out.', '["finished", "had finished", "has finished", "was finishing"]', 'had finished', 'After + antériorité', 1, 3),
(13, 'qcm', 'Look at those clouds! It ___ rain.', '["will", "is going to", "goes to", "shall"]', 'is going to', 'Signes évidents → be going to', 1, 1),
(13, 'qcm', 'I think the economy ___ improve next year.', '["will", "is going to", "shall", "would"]', 'will', 'Prédiction d''opinion → will', 1, 2),
(13, 'fill_blank', 'We ___ (get married) in June. We have already booked the venue.', NULL, 'are going to get married', 'Plan → be going to', 1, 3),
(14, 'qcm', 'By next year, I ___ my degree.', '["will finish", "will have finished", "am finishing", "finish"]', 'will have finished', 'By + futur → future perfect', 1, 1),
(14, 'fill_blank', 'This time tomorrow, I ___ (fly) over the Atlantic.', NULL, 'will be flying', 'Moment précis du futur → future continuous', 1, 2),
(14, 'qcm', 'She ___ here for ten years by 2027.', '["will live", "will be living", "will have lived", "lives"]', 'will have lived', 'By + durée → future perfect', 1, 3),
(15, 'qcm', 'I ___ the report before the meeting started.', '["finished", "had finished", "have finished", "was finishing"]', 'had finished', 'Antériorité dans le passé', 1, 1),
(15, 'qcm', 'She ___ in Paris since 2015.', '["lives", "is living", "has lived", "lived"]', 'has lived', 'Since → present perfect', 1, 2),
(15, 'fill_blank', 'When I got home, my roommate ___ (cook) dinner. It smelled delicious.', NULL, 'was cooking', 'Action en cours dans le passé', 1, 3);

-- Exercices modaux (16-23)
INSERT INTO grammar_exercises (lesson_id, type, question, options, correct_answer, explanation, points, order_index) VALUES
(16, 'qcm', 'I ___ swim when I was five.', '["can", "could", "was able to", "managed to"]', 'could', 'Capacité passée générale → could', 1, 1),
(16, 'fill_blank', '___ you help me with this heavy box?', NULL, 'Can / Could', 'Demande de permission/aide', 1, 2),
(16, 'qcm', 'She ___ speak French fluently.', '["can", "could", "may", "might"]', 'can', 'Capacité présente → can', 1, 3),
(17, 'qcm', 'The fire was serious, but everyone ___ escape.', '["can", "could", "was able to", "is able to"]', 'was able to', 'Réussite dans une situation particulière', 1, 1),
(17, 'fill_blank', 'I ___ (manage/finish) the report before the deadline.', NULL, 'managed to finish', 'Réussite avec effort → manage to', 1, 2),
(17, 'qcm', 'When I was young, I ___ run faster than anyone.', '["can", "could", "am able to", "manage to"]', 'could', 'Capacité passée générale', 1, 3),
(18, 'qcm', 'You ___ wear a seatbelt. It is the law.', '["must", "have to", "should", "ought to"]', 'have to', 'Obligation externe → have to', 1, 1),
(18, 'fill_blank', 'I ___ (study) harder. My exam is tomorrow.', NULL, 'must', 'Obligation subjective → must', 1, 2),
(18, 'qcm', 'He ___ be tired. He has been working all day.', '["must", "have to", "should", "can"]', 'must', 'Déduction logique → must', 1, 3),
(19, 'qcm', 'You ___ tell anyone. It is a secret.', '["mustn''t", "don''t have to", "needn''t", "shouldn''t"]', 'mustn''t', 'Interdiction → mustn''t', 1, 1),
(19, 'qcm', 'You ___ come if you don''t want to.', '["mustn''t", "don''t have to", "shouldn''t", "can''t"]', 'don''t have to', 'Absence d''obligation → don''t have to', 1, 2),
(19, 'fill_blank', 'We ___ (not/hurry). We have plenty of time.', NULL, 'don''t have to hurry', 'Absence d''obligation', 1, 3),
(20, 'qcm', 'You ___ eat more vegetables. It''s good for your health.', '["must", "have to", "should", "can"]', 'should', 'Conseil → should', 1, 1),
(20, 'fill_blank', 'I ___ (study) harder for my exam. I regret not doing it.', NULL, 'should have studied', 'Regret → should have + PP', 1, 2),
(20, 'qcm', 'You ___ to apologize to her.', '["must", "have", "should", "ought"]', 'ought', 'Ought to → conseil formel', 1, 3),
(21, 'qcm', '___ I use your phone, please?', '["Can", "May", "Must", "Should"]', 'May', 'Permission formelle → may', 1, 1),
(21, 'qcm', 'It ___ rain tomorrow. The forecast is uncertain.', '["can", "could", "may", "must"]', 'may', 'Possibilité → may/might', 1, 2),
(21, 'fill_blank', '___ (might/be) a good idea to leave early.', NULL, 'It might be', 'Possibilité → might', 1, 3),
(22, 'qcm', '___ we go to the cinema tonight?', '["Will", "Shall", "Would", "Should"]', 'Shall', 'Suggestion avec WE → shall', 1, 1),
(22, 'fill_blank', 'I ___ (see) you tomorrow at the meeting.', NULL, 'will', 'Futur standard → will', 1, 2),
(22, 'qcm', '___ I open the window for you?', '["Will", "Shall", "Would", "Should"]', 'Shall', 'Offre avec I → shall', 1, 3),
(23, 'qcm', 'You ___ worry. Everything will be fine.', '["needn''t", "mustn''t", "don''t have to", "shouldn''t"]', 'needn''t', 'Pas besoin → needn''t', 1, 1),
(23, 'fill_blank', 'How ___ she say such a thing?', NULL, 'dare', 'Dare + modal → défi', 1, 2),
(23, 'qcm', 'You ___ come if you don''t want to.', '["needn''t", "mustn''t", "don''t have to", "shouldn''t"]', 'don''t have to', 'Absence d''obligation', 1, 3);

INSERT INTO grammar_lessons (id, title, slug, description, content, category, level, order_index, created_at) VALUES
(24, 'Adverbes de fréquence', 'adverbs-frequency', 'Always, usually, often, sometimes, rarely, never.', '<h3>Ordre de fréquence</h3><p>always (100%) → usually (80%) → often (60%) → sometimes (40%) → rarely (10%) → never (0%)</p><h3>Position</h3><ul><li>Avant le verbe principal : <i>I always eat breakfast.</i></li><li>Après BE : <i>She is always late.</i></li><li>Après auxiliaire/modal : <i>I have never seen it.</i></li></ul><h3>Exceptions</h3><p><i>Sometimes</i> peut être en début : <i>Sometimes I go to the cinema.</i></p>', 'adverbes', 'A1', 24, 1718380800000),
(25, 'Adverbes de manière', 'adverbs-manner', 'Les adverbes en -ly décrivent comment une action est faite.', '<h3>Formation</h3><p>Adjectif + <i>-ly</i> : <i>quick → quickly, careful → carefully</i></p><h3>Exceptions</h3><ul><li>good → well</li><li>fast → fast</li><li>hard → hard</li></ul><h3>Position</h3><p>Généralement après l''objet : <i>She sings beautifully.</i></p>', 'adverbes', 'A1', 25, 1718380800000),
(26, 'Adverbes de lieu et de temps', 'adverbs-place-time', 'Here, there, now, then, today, tomorrow.', '<h3>Adverbes de lieu</h3><p>here, there, everywhere, nowhere, upstairs, downstairs, abroad</p><h3>Adverbes de temps</h3><p>now, then, today, tomorrow, yesterday, soon, later, already, yet, still</p><h3>Position</h3><p>En général en fin de phrase ou en début pour l''emphase.</p>', 'adverbes', 'A1', 26, 1718380800000),
(27, 'Adverbes de degré', 'adverbs-degree', 'Very, quite, rather, fairly, too, enough.', '<h3>Very / Quite / Rather / Fairly</h3><p>Intensifient l''adjectif : <i>very good, quite interesting, rather difficult, fairly easy</i></p><h3>Too + adjectif</h3><p>Trop (négatif) : <i>It is too hot. (On ne peut pas sortir)</i></p><h3>Adjectif + enough</h3><p>Assez (positif) : <i>It is warm enough. (On peut sortir)</i></p>', 'adverbes', 'A2', 27, 1718380800000),
(28, 'Still, Yet, Already', 'still-yet-already', 'Trois adverbes souvent confondus.', '<h3>Still</h3><p>Encore (action qui continue) : <i>Are you still here?</i></p><h3>Yet</h3><p>Déjà/pas encore (en fin de phrase, négatif/interrogatif) : <i>Have you finished yet? / I haven''t finished yet.</i></p><h3>Already</h3><p>Déjà (plus tôt que prévu) : <i>I have already eaten.</i></p>', 'adverbes', 'A2', 28, 1718380800000),
(29, 'Adverbes comparatifs et superlatifs', 'adverbs-comparative', 'Plus vite, le plus vite.', '<h3>Formation</h3><p>Adverbes courts : <i>fast → faster → fastest</i></p><p>Adverbes en -ly : <i>quickly → more quickly → most quickly</i></p><h3>Exceptions</h3><p><i>well → better → best, badly → worse → worst, far → further → furthest</i></p>', 'adverbes', 'B1', 29, 1718380800000),
(30, 'Hard vs Hardly', 'hard-hardly', 'Deux adverbes avec des sens très différents.', '<h3>Hard</h3><p>Dur, avec effort : <i>She works hard.</i></p><h3>Hardly</h3><p>Presque pas : <i>I hardly know him.</i></p><h3>Attention</h3><p><i>Hardly</i> = presque jamais/presque pas. C''est un adverbe de fréquence/négation, pas un adverbe de manière.</p>', 'adverbes', 'B1', 30, 1718380800000),
(31, 'Position des adverbes', 'adverbs-position', 'Où placer les adverbes dans la phrase anglaise.', '<h3>Règles générales</h3><ul><li>Fréquence : avant le verbe principal, après BE/auxiliaire</li><li>Manière : après l''objet</li><li>Lieu : avant le temps (PLACE avant TIME)</li><li>Temps : en fin de phrase</li></ul><h3>Ordre</h3><p><i>MANNER + PLACE + TIME</i> : <i>She sang beautifully at the concert last night.</i></p>', 'adverbes', 'B1', 31, 1718380800000),
(32, 'Prépositions de lieu - in, on, at', 'prepositions-place', 'Les prépositions de lieu les plus fondamentales.', '<h3>In</h3><p>Espace fermé, grand : <i>in the room, in Paris, in France</i></p><h3>On</h3><p>Surface, ligne : <i>on the table, on the wall, on the street</i></p><h3>At</h3><p>Point précis : <i>at the door, at the station, at home</i></p><h3>Exceptions</h3><p><i>on the bus, on the plane, on the train</i> (moyens de transport)</p>', 'prepositions', 'A1', 32, 1718380800000),
(33, 'Prépositions de lieu avancées', 'prepositions-place-advanced', 'Above, below, under, over, between, among.', '<h3>Above / Over</h3><p>Au-dessus : <i>above the line, over the bridge</i></p><h3>Below / Under / Beneath</h3><p>Au-dessous : <i>below zero, under the table</i></p><h3>Between / Among</h3><p>Between = 2 éléments. Among = 3+ éléments : <i>between you and me, among the crowd</i></p>', 'prepositions', 'B1', 33, 1718380800000),
(34, 'Prépositions de temps - in, on, at', 'prepositions-time', 'Quand utiliser in, on et at avec le temps.', '<h3>In</h3><p>Périodes longues : <i>in 2024, in July, in the morning</i></p><h3>On</h3><p>Jours et dates : <i>on Monday, on Christmas Day, on June 1st</i></p><h3>At</h3><p>Moments précis : <i>at 5 o''clock, at noon, at night, at the weekend (UK)</i></p>', 'prepositions', 'A1', 34, 1718380800000),
(35, 'For, Since, During, While', 'for-since-during', 'Quatre prépositions/conjonctions temporelles essentielles.', '<h3>For</h3><p>Durée : <i>for two hours, for a long time</i></p><h3>Since</h3><p>Point de départ : <i>since Monday, since 2010</i></p><h3>During</h3><p>Pendant (préposition) : <i>during the meeting, during the summer</i></p><h3>While</h3><p>Pendant que (conjonction + sujet + verbe) : <i>while I was eating</i></p>', 'prepositions', 'A2', 35, 1718380800000),
(36, 'To, Into, Onto', 'to-into-onto', 'Mouvement vers un lieu.', '<h3>To</h3><p>Direction générale : <i>go to school, from Paris to London</i></p><h3>Into</h3><p>Entrer dans (intérieur) : <i>walk into the room, pour water into the glass</i></p><h3>Onto</h3><p>Monter sur (surface) : <i>jump onto the table, put the book onto the shelf</i></p>', 'prepositions', 'A2', 36, 1718380800000),
(37, 'By, With, Without', 'by-with-without', 'Prépositions d''instrument et d''accompagnement.', '<h3>By</h3><p>Moyen/transport/agent : <i>by car, by hand, written by Shakespeare</i></p><h3>With</h3><p>Instrument/accompagnement : <i>cut with a knife, with my brother</i></p><h3>Without</h3><p>Absence : <i>without money, without saying goodbye</i></p>', 'prepositions', 'A2', 37, 1718380800000),
(38, 'Prépositions de mouvement', 'prepositions-movement', 'Across, through, past, along, around, up, down.', '<h3>Across</h3><p>D''un côté à l''autre (surface) : <i>walk across the street</i></p><h3>Through</h3><p>À travers (intérieur) : <i>drive through the tunnel</i></p><h3>Past</h3><p>Passer devant : <i>walk past the shop</i></p><h3>Along</h3><p>Le long de : <i>walk along the river</i></p>', 'prepositions', 'B1', 38, 1718380800000),
(39, 'Conjonctions de coordination', 'conjunctions-coordinating', 'And, but, or, so, yet, for, nor.', '<h3>Les 7 conjonctions de coordination</h3><p><b>FANBOYS</b> : <b>F</b>or, <b>A</b>nd, <b>N</b>or, <b>B</b>ut, <b>O</b>r, <b>Y</b>et, <b>S</b>o</p><h3>Usage</h3><ul><li>Relier deux propositions indépendantes</li><li>Virgule avant la conjonction (sauf phrases courtes)</li></ul><h3>Exemples</h3><p><i>I wanted to go, but I was too tired.</i></p><p><i>She was ill, so she stayed home.</i></p>', 'conjonctions', 'A2', 39, 1718380800000),
(40, 'Conjonctions de subordination - Cause', 'conjunctions-cause', 'Because, since, as.', '<h3>Because</h3><p>Cause (motivation) : <i>I stayed because it was raining.</i></p><h3>Since / As</h3><p>Cause connue, moins emphatique : <i>Since you are here, let''s start.</i></p><h3>Différences</h3><p><i>Because</i> = cause directe et nouvelle. <i>Since/As</i> = cause évidente ou déjà connue.</p>', 'conjonctions', 'A2', 40, 1718380800000),
(41, 'Conjonctions de subordination - Condition', 'conjunctions-condition', 'If, unless, as long as, provided that.', '<h3>If</h3><p>Si : <i>If it rains, I will stay home.</i></p><h3>Unless</h3><p>À moins que (= if not) : <i>Unless you study, you will fail.</i></p><h3>As long as / Provided that</h3><p>À condition que : <i>You can go as long as you finish your homework.</i></p>', 'conjonctions', 'B1', 41, 1718380800000),
(42, 'Conjonctions de subordination - Temps', 'conjunctions-time', 'When, while, before, after, until, as soon as.', '<h3>When / While</h3><p>When = quand (ponctuel). While = pendant que (durée) : <i>When I arrived, she was cooking. / While I was eating, he called.</i></p><h3>Before / After</h3><p><i>Before she left, she said goodbye. / After he finished, he went home.</i></p><h3>Until / As soon as</h3><p><i>Wait until I come back. / Call me as soon as you arrive.</i></p>', 'conjonctions', 'A2', 42, 1718380800000),
(43, 'Conjonctions de concession', 'conjunctions-concession', 'Although, though, even though, whereas, while.', '<h3>Although / Though / Even though</h3><p>Bien que (concession) : <i>Although it was raining, we went out.</i></p><h3>Whereas / While</h3><p>Alors que (contraste) : <i>Whereas he is rich, his brother is poor.</i></p><h3>Attention</h3><p>Pas de <i>but</i> après <i>although</i> ! <i>Although it was cold, we went out.</i> (PAS Although...but)</p>', 'conjonctions', 'B1', 43, 1718380800000),
(44, 'Conjonctions corrélatives', 'conjunctions-correlative', 'Both...and, either...or, neither...nor, not only...but also.', '<h3>Both...and</h3><p>Les deux : <i>Both John and Mary are coming.</i></p><h3>Either...or</h3><p>L''un ou l''autre : <i>You can either stay or leave.</i></p><h3>Neither...nor</h3><p>Ni l''un ni l''autre : <i>Neither John nor Mary is coming.</i></p><h3>Not only...but also</h3><p>Pas seulement...mais aussi : <i>She is not only smart but also kind.</i></p>', 'conjonctions', 'B1', 44, 1718380800000),
(45, 'However, Nevertheless, Therefore', 'however-nevertheless', 'Adverbes de liaison pour exprimer l''opposition et la conséquence.', '<h3>However</h3><p>Cependant : <i>I was tired. However, I finished the work.</i></p><h3>Nevertheless / Nonetheless</h3><p>Néanmoins (plus formel) : <i>The weather was bad. Nevertheless, we had a great time.</i></p><h3>Therefore / Thus / Hence</h3><p>Par conséquent : <i>She was ill. Therefore, she stayed home.</i></p>', 'conjonctions', 'B2', 45, 1718380800000),
(46, 'Articles indéfinis - A et An', 'articles-indefinite', 'Les articles indéfinis a et an.', '<h3>Avant une consonne</h3><p><i>a book, a university (se prononce [ju])</i></p><h3>Avant une voyelle</h3><p><i>an apple, an hour (se prononce [aʊ])</i></p><h3>Usage</h3><ul><li>Première mention : <i>I saw a dog.</i></li><li>Profession : <i>She is a doctor.</i></li><li>Exclamations : <i>What a beautiful day!</i></li></ul>', 'determinants', 'A1', 46, 1718380800000),
(47, 'Article défini - The', 'articles-definite', 'Quand utiliser et ne pas utiliser the.', '<h3>Usage de THE</h3><ul><li>Quand l''élément est unique : <i>the sun, the president</i></li><li>Deuxième mention : <i>I saw a cat. The cat was black.</i></li><li>Superlatifs : <i>the best, the most important</i></li><li>Noms de fleuves, océans, chaînes de montagnes : <i>the Thames, the Pacific, the Alps</i></li></ul><h3>Pas de THE</h3><ul><li>Noms de pays (sauf pluriels) : <i>France, the United States</i></li><li>Noms de villes, montagnes isolées, lacs</li><li>Repas, sports, langues</li></ul>', 'determinants', 'A1', 47, 1718380800000),
(48, 'Some et Any', 'some-any', 'Some et any pour exprimer la quantité.', '<h3>Some</h3><p>Offres, demandes, affirmations : <i>Would you like some coffee? / I have some time.</i></p><h3>Any</h3><p>Négations, interrogations : <i>I don''t have any money. / Do you have any questions?</i></p><h3>Exceptions</h3><p><i>Any</i> peut s''utiliser à l''affirmatif avec le sens de "n''importe quel" : <i>Any student can do this.</i></p>', 'determinants', 'A1', 48, 1718380800000),
(49, 'Much, Many, A lot of', 'much-many', 'Exprimer une grande quantité.', '<h3>Much</h3><p>Noms indénombrables + négation/interrogation : <i>How much water? / I don''t have much time.</i></p><h3>Many</h3><p>Noms dénombrables + négation/interrogation : <i>How many books? / I don''t have many friends.</i></p><h3>A lot of / Lots of / Plenty of</h3><p>Tous types de noms, toutes situations : <i>I have a lot of time/friends.</i></p>', 'determinants', 'A2', 49, 1718380800000),
(50, 'Few, A few, Little, A little', 'few-little', 'Peu ou un peu.', '<h3>Few / A few</h3><p>Dénombrables : <i>Few people came.</i> (presque personne, négatif) / <i>A few people came.</i> (quelques-uns, positif)</p><h3>Little / A little</h3><p>Indénombrables : <i>Little water remained.</i> (presque rien, négatif) / <i>A little water remained.</i> (un peu, positif)</p>', 'determinants', 'B1', 50, 1718380800000);

INSERT INTO grammar_lessons (id, title, slug, description, content, category, level, order_index, created_at) VALUES
(51, 'Pronoms personnels sujet', 'pronouns-subject', 'I, you, he, she, it, we, they.', '<h3>Tableau</h3><table><tr><th>Singulier</th><th>Pluriel</th></tr><tr><td>I (1e)</td><td>we (1e)</td></tr><tr><td>you (2e)</td><td>you (2e)</td></tr><tr><td>he/she/it (3e)</td><td>they (3e)</td></tr></table><h3>Usage</h3><p>Le sujet fait l''action : <i>She sings. / They are happy.</i></p>', 'pronoms', 'A1', 51, 1718380800000),
(52, 'Pronoms personnels objet', 'pronouns-object', 'Me, you, him, her, it, us, them.', '<h3>Tableau</h3><table><tr><th>Singulier</th><th>Pluriel</th></tr><tr><td>me</td><td>us</td></tr><tr><td>you</td><td>you</td></tr><tr><td>him/her/it</td><td>them</td></tr></table><h3>Usage</h3><p>L''objet subit l''action : <i>She loves him. / I saw them.</i></p>', 'pronoms', 'A1', 52, 1718380800000),
(53, 'Pronoms possessifs', 'pronouns-possessive', 'My, your, his, her, its, our, their.', '<h3>Adjectifs possessifs (avant le nom)</h3><p>my, your, his, her, its, our, their</p><h3>Pronoms possessifs (remplacent le nom)</h3><p>mine, yours, his, hers, ours, theirs</p><h3>Exemples</h3><p><i>This is my book. / This book is mine.</i></p><p><i>That is her car. / That car is hers.</i></p>', 'pronoms', 'A1', 53, 1718380800000),
(54, 'Pronoms réflexifs', 'pronouns-reflexive', 'Myself, yourself, himself, herself, itself, ourselves, yourselves, themselves.', '<h3>Formation</h3><p>Adjectif possessif + <i>-self/-selves</i></p><h3>Usage</h3><ul><li>Action réflexive : <i>I cut myself.</i></li><li>Pour insister : <i>I did it myself.</i></li><li>Seul : <i>She lives by herself.</i></li></ul>', 'pronoms', 'A2', 54, 1718380800000),
(55, 'Pronoms démonstratifs', 'pronouns-demonstrative', 'This, that, these, those.', '<h3>Singulier</h3><p><i>This</i> (proche) : <i>This book is mine.</i></p><p><i>That</i> (loin) : <i>That car is red.</i></p><h3>Pluriel</h3><p><i>These</i> (proches) : <i>These apples are fresh.</i></p><p><i>Those</i> (loins) : <i>Those mountains are high.</i></p>', 'pronoms', 'A1', 55, 1718380800000),
(56, 'Pronoms indéfinis - Somebody, Anyone, Nobody', 'pronouns-indefinite', 'Somebody, anyone, nobody, everybody, something, anything.', '<h3>Quelqu''un/quelque chose</h3><p><i>Somebody/someone/something</i> (affirmatif)</p><p><i>Anybody/anyone/anything</i> (négatif/interrogatif)</p><p><i>Nobody/no one/nothing</i> (négatif, sujet)</p><p><i>Everybody/everyone/everything</i> (tout le monde, tout)</p><h3>Accord du verbe</h3><p>Toujours singulier : <i>Everybody is happy.</i></p>', 'pronoms', 'A2', 56, 1718380800000),
(57, 'Pronoms relatifs - Who, Which, That', 'pronouns-relative', 'Qui, que, lequel.', '<h3>Who</h3><p>Pour les personnes : <i>The man who called you is my boss.</i></p><h3>Which</h3><p>Pour les choses/animaux : <i>The car which is parked outside is mine.</i></p><h3>That</h3><p>Pour tout : <i>The book that I read was interesting.</i></p><h3>Whose / Whom</h3><p><i>Whose</i> = possession : <i>The man whose car was stolen...</i></p><p><i>Whom</i> = formel, objet : <i>The person to whom I spoke...</i></p>', 'pronoms', 'B1', 57, 1718380800000),
(58, 'Pronoms interrogatifs', 'pronouns-interrogative', 'Who, what, which, whose, whom.', '<h3>Who</h3><p>Pour les personnes (sujet) : <i>Who is coming?</i></p><h3>Whom</h3><p>Pour les personnes (objet, formel) : <i>Whom did you see?</i></p><h3>What</h3><p>Pour les choses : <i>What is your name?</i></p><h3>Which</h3><p>Choix limité : <i>Which colour do you prefer?</i></p><h3>Whose</h3><p>Possession : <i>Whose car is this?</i></p>', 'pronoms', 'A2', 58, 1718380800000),
(59, 'Each other vs One another', 'each-other', 'Exprimer la réciprocité.', '<h3>Each other</h3><p>Entre deux personnes : <i>They love each other.</i></p><h3>One another</h3><p>Entre plusieurs personnes (théorique) : <i>They helped one another.</i></p><h3>Usage moderne</h3><p>Aujourd''hui, <i>each other</i> et <i>one another</i> sont souvent interchangeables.</p>', 'pronoms', 'B1', 59, 1718380800000),
(60, 'One et You - Généralité', 'one-you-general', 'Utiliser one ou you pour parler de manière générale.', '<h3>One</h3><p>Très formel, britannique : <i>One must be careful.</i></p><h3>You</h3><p>Courant, général : <i>You must be careful. (= il faut être prudent)</i></p><h3>Différence</h3><p><i>One</i> est plus impersonnel et soutenu. <i>You</i> est plus naturel à l''oral.</p>', 'pronoms', 'B2', 60, 1718380800000),
(61, 'La voix passive - Présent', 'passive-present', 'Transformer une phrase active en passive.', '<h3>Formation</h3><p><i>BE</i> (présent) + participe passé</p><h3>Exemples</h3><ul><li>Active : <i>Someone cleans the room every day.</i></li><li>Passive : <i>The room is cleaned every day.</i></li></ul><h3>Usage</h3><p>Quand l''agent est inconnu, moins important ou évident : <i>My car was stolen.</i></p>', 'structures', 'B1', 61, 1718380800000),
(62, 'La voix passive - Passé et modaux', 'passive-past-modals', 'Le passif au prétérit et avec les modaux.', '<h3>Prétérit</h3><p><i>was/were</i> + participe passé : <i>The letter was written yesterday.</i></p><h3>Avec modaux</h3><p>Modal + <i>be</i> + participe passé : <i>The report must be finished by Friday.</i></p><h3>By + agent</h3><p>Quand on mentionne l''agent : <i>The book was written by Hemingway.</i></p>', 'structures', 'B1', 62, 1718380800000),
(63, 'Reported speech - Présent', 'reported-speech-present', 'Rapporter des déclarations au présent.', '<h3>Transformation</h3><ul><li>Guillemets → that</li><li>Pronoms : <i>I → he/she</i>, <i>my → his/her</i></li><li>Temps : <i>am → was</i>, <i>have → had</i></li><li>Adverbes : <i>now → then</i>, <i>today → that day</i>, <i>yesterday → the day before</i></li></ul><h3>Exemple</h3><p>Direct : <i>She said, "I am tired."</i></p><p>Reported : <i>She said (that) she was tired.</i></p>', 'structures', 'B1', 63, 1718380800000),
(64, 'Reported speech - Questions et ordres', 'reported-speech-questions', 'Rapporter des questions et des ordres.', '<h3>Questions fermées (yes/no)</h3><p><i>if/whether</i> + sujet + verbe : <i>He asked if she was coming.</i></p><h3>Questions ouvertes</h3><p>Mot interrogatif + sujet + verbe : <i>She asked where he lived.</i></p><h3>Ordres/demandes</h3><p><i>Tell/ask/order + object + to + infinitive</i> : <i>He told me to wait.</i></p>', 'structures', 'B2', 64, 1718380800000),
(65, 'Les conditionnels - Zero et First', 'conditionals-zero-first', 'If + présent et If + présent/futur.', '<h3>Zero conditional</h3><p>Vérité générale : <i>If + présent, présent</i></p><p><i>If you heat ice, it melts.</i></p><h3>First conditional</h3><p>Réel/probable : <i>If + présent, will + base</i></p><p><i>If it rains, I will stay home.</i></p>', 'structures', 'A2', 65, 1718380800000),
(66, 'Les conditionnels - Second', 'conditionals-second', 'If + prétérit → would + base.', '<h3>Second conditional</h3><p>Hypothétique/improbable : <i>If + prétérit, would + base</i></p><p><i>If I won the lottery, I would buy a house.</i></p><h3>Be → were (toutes les personnes)</h3><p><i>If I were rich, I would travel the world.</i></p><p>Aussi : <i>If he were here, he would help.</i></p>', 'structures', 'B1', 66, 1718380800000),
(67, 'Les conditionnels - Third', 'conditionals-third', 'If + past perfect → would have + PP.', '<h3>Third conditional</h3><p>Regret/impossible dans le passé : <i>If + past perfect, would have + past participle</i></p><p><i>If I had studied harder, I would have passed the exam.</i></p><h3>Variation</h3><p><i>Could have, might have</i> au lieu de <i>would have</i></p>', 'structures', 'B2', 67, 1718380800000),
(68, 'Wishes au présent', 'wishes-present', 'Exprimer un souhait au présent.', '<h3>Wish + prétérit</h3><p>Souhait contraire à la réalité présente : <i>I wish I were taller.</i></p><p><i>I wish I had a car.</i> (mais je n''en ai pas)</p><h3>If only</h3><p>Même sens, plus émotif : <i>If only she knew the truth!</i></p>', 'structures', 'B1', 68, 1718380800000),
(69, 'Wishes au passé', 'wishes-past', 'Exprimer un regret.', '<h3>Wish + past perfect</h3><p>Regret dans le passé : <i>I wish I had studied medicine.</i></p><h3>Exemples</h3><p><i>She wishes she had never met him.</i></p><p><i>If only I had listened to my parents!</i></p>', 'structures', 'B2', 69, 1718380800000),
(70, 'Causative - Have/Get something done', 'causative', 'Faire faire quelque chose par quelqu''un.', '<h3>Have/get + object + past participle</h3><p><i>I had my hair cut.</i> (quelqu''un m''a coupé les cheveux)</p><p><i>She is getting the car repaired.</i></p><h3>Différences</h3><p><i>Have</i> = plus courant. <i>Get</i> = plus informel.</p>', 'structures', 'B2', 70, 1718380800000),
(71, 'Used to et Be used to', 'used-to', 'Deux structures avec « used » mais des sens différents.', '<h3>Used to + base</h3><p>Habitude passée (aujourd''hui non) : <i>I used to smoke. (but I quit)</i></p><h3>Be used to + V-ing / nom</h3><p>Être habitué à : <i>I am used to waking up early.</i></p><h3>Get used to</h3><p>Devenir habitué : <i>I got used to the noise.</i></p>', 'structures', 'B1', 71, 1718380800000),
(72, 'Too et Enough', 'too-enough', 'Trop et assez.', '<h3>Too + adjectif</h3><p>Trop (négatif, impossible) : <i>It is too cold to go out.</i></p><h3>Adjectif + enough</h3><p>Assez (positif, possible) : <i>It is warm enough to go out.</i></p><h3>Not + adjectif + enough</h3><p>Pas assez : <i>He is not tall enough to reach the shelf.</i></p>', 'structures', 'A2', 72, 1718380800000),
(73, 'So et Such', 'so-such', 'Intensifier avec so et such.', '<h3>So + adjectif/adverbe</h3><p><i>So beautiful, so quickly</i></p><h3>Such + (a/an) + adjectif + nom</h3><p><i>Such a beautiful day, such bad weather</i></p><h3>So...that / Such...that</h3><p><i>It was so cold that we stayed inside.</i></p><p><i>It was such a good film that I saw it twice.</i></p>', 'structures', 'B1', 73, 1718380800000),
(74, 'Ordre des mots en anglais', 'word-order', 'La structure fondamentale SVO.', '<h3>SVO (Subject + Verb + Object)</h3><p><i>She (S) eats (V) apples (O).</i></p><h3>Place des adverbes</h3><p>Fréquence : avant le verbe principal, après BE</p><p><i>She always eats apples. / She is always late.</i></p><h3>Inversion en questions</h3><p><i>Do you like apples?</i></p><p><i>Are you happy?</i></p>', 'syntaxe', 'A1', 74, 1718380800000),
(75, 'Questions tags', 'question-tags', 'Les tags de confirmation en fin de phrase.', '<h3>Formation</h3><p>Auxiliaire + pronom (opposé à l''affirmation) : <i>You are happy, aren''t you?</i></p><h3>Règles</h3><ul><li>Phrase positive → tag négatif</li><li>Phrase négative → tag positif</li><li>BE et auxiliaires se répètent : <i>She has left, hasn''t she?</i></li></ul><h3>Exceptions</h3><p><i>Let''s... shall we? / I am... aren''t I?</i></p>', 'syntaxe', 'B1', 75, 1718380800000),
(76, 'Inversion pour l''emphase', 'inversion-emphasis', 'Inverser le sujet pour mettre l''accent.', '<h3>After negative adverbs</h3><p><i>Never have I seen such beauty.</i></p><p><i>Hardly had I arrived when it started to rain.</i></p><h3>Conditionnel sans if</h3><p><i>Were I rich, I would travel. / Had I known, I would have come.</i></p>', 'syntaxe', 'C1', 76, 1718380800000),
(77, 'Cleft sentences', 'cleft-sentences', 'Mettre l''emphase sur un élément de la phrase.', '<h3>It is/was... that/who</h3><p><i>John bought a car yesterday.</i></p><p>→ <i>It was John who bought a car yesterday.</i></p><p>→ <i>It was a car that John bought yesterday.</i></p><p>→ <i>It was yesterday that John bought a car.</i></p>', 'syntaxe', 'C1', 77, 1718380800000),
(78, 'Emphatic do', 'emphatic-do', 'Utiliser do pour insister.', '<h3>Do/Does/Did + base</h3><p>Insister sur l''action : <i>I do like you!</i></p><p><i>She does speak French.</i></p><h3>Exemples</h3><p><i>Do be careful!</i></p><p><i>He did finish his homework.</i></p>', 'syntaxe', 'B2', 78, 1718380800000),
(79, 'Gérondif vs Infinitif', 'gerund-infinitive', 'Quand utiliser le gérondif et l''infinitif.', '<h3>Après certaines prépositions</h3><p><i>interested in doing, good at swimming</i></p><h3>Verbes suivis du gérondif</h3><p><i>enjoy, finish, avoid, suggest, admit, deny, imagine, consider, miss, postpone, practice, risk</i></p><h3>Verbes suivis de l''infinitif</h3><p><i>want, decide, hope, promise, agree, refuse, offer, manage, plan, learn, seem, appear</i></p>', 'syntaxe', 'B1', 79, 1718380800000),
(80, 'Gérondif vs Infinitif - Suite', 'gerund-infinitive-verbs', 'Les verbes qui changent de sens.', '<h3>Stop + gérondif</h3><p>Arrêter une activité : <i>Stop smoking!</i></p><h3>Stop + infinitif</h3><p>S''arrêter pour faire : <i>He stopped to tie his shoelaces.</i></p><h3>Remember + gérondif</h3><p>Se souvenir d''avoir fait : <i>I remember locking the door.</i></p><h3>Remember + infinitif</h3><p>Ne pas oublier de faire : <i>Remember to lock the door.</i></p><h3>Try + gérondif</h3><p>Expérimenter : <i>Try eating less sugar.</i></p><h3>Try + infinitif</h3><p>Faire un effort : <i>Try to be on time.</i></p>', 'syntaxe', 'B2', 80, 1718380800000);

INSERT INTO grammar_lessons (id, title, slug, description, content, category, level, order_index, created_at) VALUES
(81, 'Phrasal verbs courants', 'phrasal-verbs-common', 'Les phrasal verbs les plus fréquents.', '<h3>Définition</h3><p>Un verbe + une particule (adverbe ou préposition) qui change le sens du verbe.</p><h3>Exemples courants</h3><ul><li><i>get up</i> = se lever</li><li><i>turn on</i> = allumer</li><li><i>look for</i> = chercher</li><li><i>give up</i> = abandonner</li><li><i>take off</i> = décoller / enlever</li><li><i>put on</i> = mettre (vêtements)</li><li><i>look after</i> = s''occuper de</li></ul>', 'vocabulaire', 'A2', 81, 1718380800000),
(82, 'Phrasal verbs séparables', 'phrasal-verbs-separable', 'Les phrasal verbs où l''on peut intercaler l''objet.', '<h3>Séparables</h3><p>Verbe + particule : l''objet peut aller entre les deux :</p><p><i>turn off the TV / turn the TV off / turn it off</i></p><h3>Non-séparables</h3><p>L''objet est toujours après :</p><p><i>look after the children</i> (PAS look the children after)</p><h3>Liste des séparables courants</h3><p>turn on/off, put on, take off, give back, throw away, pick up, clean up, fill in</p>', 'vocabulaire', 'B1', 82, 1718380800000),
(83, 'Collocations', 'collocations', 'Les mots qui vont ensemble.', '<h3>Définition</h3><p>Association fréquente de deux mots : <i>make a decision, take a photo, do homework</i></p><h3>Types</h3><ul><li>Verbe + nom : <i>have breakfast, take a shower, make progress</i></li><li>Adjectif + nom : <i>heavy rain, strong coffee, fast food</i></li><li>Adverbe + adjectif : <i>absolutely brilliant, deeply sorry</i></li></ul>', 'vocabulaire', 'B1', 83, 1718380800000),
(84, 'Expressions idiomatiques', 'idioms', 'Expressions figées à connaître.', '<h3>Expressions courantes</h3><ul><li><i>It''s raining cats and dogs.</i> = Il pleut des cordes</li><li><i>Break a leg!</i> = Bonne chance !</li><li><i>Bite the bullet.</i> = Prendre son courage à deux mains</li><li><i>Hit the sack.</i> = Aller se coucher</li><li><i>Let the cat out of the bag.</i> = Vendre la mèche</li><li><i>Once in a blue moon.</i> = Tous les trente-six du mois</li></ul>', 'vocabulaire', 'B1', 84, 1718380800000),
(85, 'Verbes à préposition', 'verbs-prepositions', 'Les verbes qui s''associent à une préposition spécifique.', '<h3>Verbe + préposition</h3><ul><li><i>listen to</i> (PAS listen the radio)</li><li><i>look at</i></li><li><i>wait for</i></li><li><i>ask for</i></li><li><i>pay for</i></li><li><i>depend on</i></li><li><i>believe in</i></li><li><i>agree with</i></li><li><i>apologize for</i></li><li><i>dream of</i></li></ul><p>Attention : aucune logique, il faut apprendre par cœur.</p>', 'vocabulaire', 'A2', 85, 1718380800000),
(86, 'Register formel vs informel', 'register-formal-informal', 'Adapter son langage selon le contexte.', '<h3>Formel</h3><p><i>Dear Sir or Madam, I am writing to inquire about...</i></p><h3>Informel</h3><p><i>Hey! How''s it going? Just wanted to ask...</i></p><h3>Différences</h3><table><tr><th>Formel</th><th>Informel</th></tr><tr><td>I would like to</td><td>I want to</td></tr><tr><td>Could you please</td><td>Can you</td></tr><tr><td>I am afraid</td><td>Sorry</td></tr><tr><td>Furthermore</td><td>Also</td></tr></table>', 'vocabulaire', 'B2', 86, 1718380800000),
(87, 'Faux amis', 'false-friends', 'Les mots similaires mais de sens différents.', '<h3>Exemples courants</h3><table><tr><th>Anglais</th><th>Faux ami</th><th>Vrai sens</th></tr><tr><td>actually</td><td>actuellement</td><td>en fait</td></tr><tr><td>eventually</td><td>éventuellement</td><td>finalement</td></tr><tr><td>currently</td><td>couramment</td><td>actuellement</td></tr><tr><td>library</td><td>librairie</td><td>bibliothèque</td></tr><tr><td>bookshop</td><td>-</td><td>librairie</td></tr><tr><td>venue</td><td>-</td><td>lieu (de concert)</td></tr></table>', 'vocabulaire', 'A2', 87, 1718380800000),
(88, 'Différences UK vs US', 'uk-vs-us', 'Les différences entre anglais britannique et américain.', '<h3>Vocabulaire</h3><table><tr><th>UK</th><th>US</th></tr><tr><td>lift</td><td>elevator</td></tr><tr><td>flat</td><td>apartment</td></tr><tr><td>lorry</td><td>truck</td></tr><tr><td>petrol</td><td>gas</td></tr><tr><td>chips</td><td>fries</td></tr><tr><td>crisps</td><td>chips</td></tr></table><h3>Orthographe</h3><p><i>colour/color, organise/organize, travelled/traveled</i></p>', 'vocabulaire', 'A2', 88, 1718380800000),
(89, 'Double négation', 'double-negation', 'La règle de la négation en anglais.', '<h3>Règle</h3><p>En anglais standard, une seule négation par phrase.</p><h3>Incorrect</h3><p><i>I don''t know nothing.</i> (faux)</p><h3>Correct</h3><p><i>I don''t know anything.</i></p><p><i>I know nothing.</i></p><h3>Exception</h3><p>Double négation = affirmation : <i>I can''t not help you. (= I must help you)</i></p>', 'syntaxe', 'A2', 89, 1718380800000),
(90, 'As...as - Comparaisons d''égalité', 'as-as', 'Exprimer l''égalité avec as...as.', '<h3>Formation</h3><p><i>as + adjectif/adverbe + as</i></p><h3>Exemples</h3><p><i>She is as tall as her brother.</i></p><p><i>I run as fast as you.</i></p><h3>Négation</h3><p><i>not as/so + adjectif + as</i> : <i>He is not as rich as his father.</i></p>', 'syntaxe', 'A2', 90, 1718380800000),
(91, 'Les nombres et dates', 'numbers-dates', 'Comment exprimer les nombres et dates.', '<h3>Nombres cardinaux</h3><p>21 = twenty-one, 100 = one hundred, 1,000 = one thousand</p><h3>Nombres ordinaux</h3><p>1st = first, 2nd = second, 3rd = third, 21st = twenty-first</p><h3>Dates</h3><p>UK : 14th March 2024 / the fourteenth of March</p><p>US : March 14, 2024 / March the fourteenth</p>', 'vocabulaire', 'A1', 91, 1718380800000),
(92, 'Let, Make, Have + infinitif', 'let-make-have', 'Les causatifs simples.', '<h3>Let</h3><p>Permettre : <i>She let me go.</i> (= elle m''a laissé partir)</p><h3>Make</h3><p>Forcer : <i>She made me laugh.</i> (= elle m''a fait rire)</p><h3>Have</h3><p>Demander à quelqu''un de faire : <i>I had him fix my computer.</i></p><h3>Attention</h3><p><i>Let</i> et <i>make</i> sont suivis de l''infinitif SANS to.</p>', 'structures', 'B1', 92, 1718380800000),
(93, 'Rather et Would rather', 'would-rather', 'Exprimer la préférence.', '<h3>Would rather + base</h3><p>Préférence pour soi : <i>I would rather stay home.</i></p><h3>Would rather + sujet + prétérit</h3><p>Préférence pour quelqu''un d''autre : <i>I would rather you didn''t smoke here.</i></p><h3>Had better</h3><p>Conseil fort : <i>You had better hurry. (= tu ferais mieux de te dépêcher)</i></p>', 'structures', 'B1', 93, 1718380800000),
(94, 'There is / There are', 'there-is-there-are', 'Exprimer l''existence.', '<h3>There is</h3><p>Singulier/indénombrable : <i>There is a book on the table.</i></p><h3>There are</h3><p>Pluriel : <i>There are three chairs.</i></p><h3>There was/were</h3><p>Passé : <i>There was a problem yesterday.</i></p><h3>There will be</h3><p>Futur : <i>There will be a meeting tomorrow.</i></p>', 'syntaxe', 'A1', 94, 1718380800000),
(95, 'It is / It was', 'it-is', 'Utiliser it pour le temps, la distance, l''identification.', '<h3>Temps</h3><p><i>It is 3 o''clock. / It was raining.</i></p><h3>Distance</h3><p><i>It is 10 kilometres to the city.</i></p><h3>Identification</h3><p><i>It is John at the door.</i></p><h3>Impossible sans it</h3><p><i>It is important to study.</i> (PAS To study is important)</p>', 'syntaxe', 'A1', 95, 1718380800000),
(96, 'Comparatif et superlatif', 'comparative-superlative', 'Comparer en anglais.', '<h3>Adjectifs courts</h3><p>tall → taller → tallest / big → bigger → biggest</p><h3>Adjectifs longs</h3><p>beautiful → more beautiful → most beautiful</p><h3>Exceptions</h3><p>good → better → best / bad → worse → worst / far → further → furthest</p><h3>Than</h3><p><i>She is taller than her brother.</i></p><h3>The...in/of</h3><p><i>He is the best player in the team.</i></p>', 'syntaxe', 'A2', 96, 1718380800000),
(97, 'Possessif avec apostrophe', 'possessive-apostrophe', 'Le génitif saxon.', '<h3>Singulier</h3><p><i>the boy''s book, James''s car / James'' car</i></p><h3>Pluriel</h3><p><i>the boys'' books</i> (PAS the boys''s books)</p><h3>Exceptions</h3><p><i>its</i> = possessif (pas d''apostrophe)</p><p><i>it''s</i> = it is / it has</p><h3>Usage</h3><p>Personnes, animaux : <i>my brother''s wife, the dog''s tail</i></p><p>Choses : préférer of : <i>the roof of the house</i></p>', 'syntaxe', 'A2', 97, 1718380800000),
(98, 'Déclarations négatives', 'negative-statements', 'Formuler des phrases négatives.', '<h3>Présent simple / Prétérit simple</h3><p>Do/does/did + not + base : <i>She does not like coffee.</i></p><h3>BE</h3><p>BE + not : <i>He is not here.</i></p><h3>Modaux</h3><p>Modal + not + base : <i>I cannot swim.</i></p><h3>Auxiliaires</h3><p>Have + not + participe passé : <i>I have not finished.</i></p>', 'syntaxe', 'A1', 98, 1718380800000),
(99, 'Questions ouvertes et fermées', 'questions-open-closed', 'Former des questions.', '<h3>Questions fermées (yes/no)</h3><p>Auxiliaire + sujet + base : <i>Do you like pizza? / Are you happy?</i></p><h3>Questions ouvertes (WH-)</h3><p>WH- + auxiliaire + sujet + base : <i>Where do you live? / What are you doing?</i></p><h3>Questions avec préposition</h3><p>Formel : <i>To whom did you speak?</i></p><p>Courant : <i>Who did you speak to?</i></p>', 'syntaxe', 'A1', 99, 1718380800000),
(100, 'Articles zéro', 'zero-article', 'Quand ne PAS utiliser d''article.', '<h3>Pas d''article devant</h3><ul><li>Noms propres de pays, villes, montagnes isolées : <i>France, Paris, Everest</i></li><li>Repas : <i>have breakfast</i></li><li>Sports : <i>play football</i></li><li>Langues : <i>speak French</i></li><li>Jours de la semaine (sauf spécifique) : <i>on Monday</i></li></ul><h3>Attention</h3><p><i>The United States, the Alps</i> (noms pluriaux)</p>', 'determinants', 'A2', 100, 1718380800000),
(101, 'Noms dénombrables et indénombrables', 'countable-uncountable', 'Distinguer les noms comptables et non-comptables.', '<h3>Dénombrables</h3><p>On peut compter : <i>a book, two books, many books</i></p><h3>Indénombrables</h3><p>On ne peut pas compter : <i>water, information, advice, furniture, luggage, money, news</i></p><h3>Quantifiers</h3><p>Dénombrables : <i>many, a few, several</i></p><p>Indénombrables : <i>much, a little, a bit of</i></p>', 'vocabulaire', 'A1', 101, 1718380800000),
(102, 'Les quantifieurs', 'quantifiers', 'All, both, either, neither, none, every, each.', '<h3>All / Both</h3><p><i>All</i> = tous (3+) : <i>All students passed.</i></p><p><i>Both</i> = les deux : <i>Both answers are correct.</i></p><h3>Either / Neither</h3><p><i>Either</i> = l''un ou l''autre : <i>Either day is fine.</i></p><p><i>Neither</i> = aucun des deux : <i>Neither answer is correct.</i></p><h3>None / No</h3><p><i>None</i> = aucun (de) : <i>None of them came.</i></p>', 'determinants', 'B1', 102, 1718380800000),
(103, 'Les deux, les trois...', 'all-both-none', 'All, both, every, each, none.', '<h3>Every vs Each</h3><p><i>Every</i> = ensemble : <i>Every student has a book.</i></p><p><i>Each</i> = individuellement : <i>Each student has his own book.</i></p><h3>None of</h3><p><i>None of my friends came.</i></p><p>Le verbe peut être singulier ou pluriel : <i>None is/are...</i></p>', 'determinants', 'B1', 103, 1718380800000),
(104, 'Les adjectifs composés', 'compound-adjectives', 'Adjectifs formés de deux mots.', '<h3>Formation</h3><p>Deux mots reliés par un trait d''union :</p><ul><li><i>well-known</i> = bien connu</li><li><i>hard-working</i> = travailleur</li><li><i>good-looking</i> = beau/belle</li><li><i>long-lasting</i> = durable</li><li><i>old-fashioned</i> = démodé</li></ul><h3>Position</h3><p>Avant le nom : <i>a well-known actor</i></p><p>Après BE : <i>The actor is well-known.</i></p>', 'syntaxe', 'B1', 104, 1718380800000),
(105, 'Word formation', 'word-formation', 'Formation des mots : préfixes et suffixes.', '<h3>Préfixes</h3><ul><li>un- : <i>unhappy</i></li><li>dis- : <i>disagree</i></li><li>in- : <i>incorrect</i></li><li>re- : <i>rewrite</i></li><li>pre- : <i>preview</i></li><li>mis- : <i>misunderstand</i></li></ul><h3>Suffixes</h3><ul><li>-ness : <i>happiness</i></li><li>-ful : <i>beautiful</i></li><li>-less : <i>homeless</i></li><li>-ment : <i>government</i></li></ul>', 'vocabulaire', 'B2', 105, 1718380800000),
(106, 'Discourse markers', 'discourse-markers', 'Mots de liaison pour structurer un discours.', '<h3>Ajouter une idée</h3><p>furthermore, moreover, in addition, besides</p><h3>Contraster</h3><p>however, nevertheless, on the other hand, in contrast</p><h3>Expliquer</h3><p>in other words, that is to say, to put it another way</p><h3>Conclure</h3><p>in conclusion, to sum up, all in all, in short</p>', 'vocabulaire', 'B2', 106, 1718380800000),
(107, 'Subjonctif', 'subjunctive', 'Le subjonctif en anglais.', '<h3>Formation</h3><p>Base verbale pour toutes les personnes (pas de -s à la 3e personne)</p><h3>Usage</h3><ul><li>Après <i>insist, suggest, recommend, demand</i> : <i>He suggested that she come early.</i></li><li>Formules fixes : <i>God save the Queen! / Long live the King!</i></li><li><i>It is important/necessary that he be here.</i></li></ul><h3>UK vs US</h3><p>Plus courant en américain. En britannique, <i>should</i> est souvent utilisé : <i>He suggested that she should come.</i></p>', 'structures', 'C1', 107, 1718380800000),
(108, 'Apposition', 'apposition', 'Un nom qui explique un autre nom.', '<h3>Définition</h3><p>Un groupe de mots qui identifie ou précise un nom : <i>My brother, a doctor, lives in London.</i></p><h3>Avec ou sans virgules</h3><ul><li>Avec virgules = information non essentielle : <i>Paris, the capital of France, is beautiful.</i></li><li>Sans virgules = information essentielle : <i>the writer Hemingway</i></li></ul>', 'syntaxe', 'B2', 108, 1718380800000),
(109, 'Ellipsis', 'ellipsis', 'Omettre des mots quand le sens est clair.', '<h3>Dans les réponses</h3><p><i>Are you coming? Yes, I am.</i> (pas I am coming)</p><h3>Après and, but, or</h3><p><i>She sings and (she) dances.</i></p><h3>Comparaisons</h3><p><i>She sings better than I do.</i></p><h3>Infinitif</h3><p><i>I want to go and (to) see her.</i></p>', 'syntaxe', 'B2', 109, 1718380800000),
(110, 'Révision complète - Niveau avancé', 'advanced-review', 'Révision des points complexes.', '<h3>Récapitulatif des structures avancées</h3><ul><li>Inversion : <i>Never have I...</i></li><li>Cleft sentences : <i>It was... who...</i></li><li>Subjonctif : <i>I suggest that he be...</i></li><li>Emphatic do : <i>I do believe...</i></li><li>Conditionnels mixtes : <i>If I had studied, I would be a doctor now.</i></li></ul><h3>Astuce</h3><p>Lire beaucoup pour intégrer ces structures naturellement.</p>', 'structures', 'C1', 110, 1718380800000);

-- Exercices leçons 24-50
INSERT INTO grammar_exercises (lesson_id, type, question, options, correct_answer, explanation, points, order_index) VALUES
(24, 'qcm', 'She ___ eats meat. She is a vegetarian.', '["always", "usually", "sometimes", "never"]', 'never', 'Végétarienne = ne mange jamais de viande', 1, 1),
(24, 'fill_blank', 'I ___ (go) to the gym on Saturdays.', NULL, 'usually go', 'Fréquence + présent simple', 1, 2),
(24, 'qcm', '___ do you play tennis?', '["How always", "How often", "How much", "How long"]', 'How often', 'Question sur la fréquence', 1, 3),
(25, 'qcm', 'She speaks English very ___.', '["good", "well", "better", "best"]', 'well', 'Adverbe de manière → well (pas good)', 1, 1),
(25, 'fill_blank', 'He drives very ___ (careful).', NULL, 'carefully', 'Adverbe en -ly', 1, 2),
(25, 'qcm', 'They arrived ___.', '["quick", "quickly", "more quick", "quicker"]', 'quickly', 'Arriver = verbe → adverbe', 1, 3),
(26, 'qcm', 'I can''t find my keys. I looked ___.', '["everywhere", "somewhere", "nowhere", "anywhere"]', 'everywhere', 'Chercher partout → everywhere', 1, 1),
(26, 'fill_blank', 'We are leaving ___ (tomorrow).', NULL, 'tomorrow', 'Adverbe de temps', 1, 2),
(26, 'qcm', 'Come ___! I need your help.', '["here", "there", "where", "nowhere"]', 'here', 'Venez ici → here', 1, 3),
(27, 'qcm', 'It is ___ hot to go outside.', '["very", "too", "enough", "so"]', 'too', 'Too + adjectif = trop (négatif)', 1, 1),
(27, 'qcm', 'He is not tall ___ to reach the shelf.', '["too", "enough", "so", "very"]', 'enough', 'Not + adj + enough = pas assez', 1, 2),
(27, 'fill_blank', 'The coffee is ___ (hot) to drink.', NULL, 'too hot', 'Trop chaud pour boire', 1, 3),
(28, 'qcm', 'Have you finished your homework ___?', '["already", "yet", "still", "just"]', 'yet', 'Yet en fin de phrase (interrogation)', 1, 1),
(28, 'qcm', 'I have ___ eaten. I am not hungry.', '["already", "yet", "still", "just"]', 'already', 'Already = déjà fait', 1, 2),
(28, 'fill_blank', 'Are you ___ watching that series?', NULL, 'still', 'Still = encore', 1, 3),
(29, 'qcm', 'She sings ___ than her sister.', '["more beautifully", "more beautiful", "beautifullier", "most beautifully"]', 'more beautifully', 'Comparatif adverbe en -ly → more', 1, 1),
(29, 'fill_blank', 'He runs ___ (fast) than anyone in the team.', NULL, 'faster', 'Fast → faster (irrégulier court)', 1, 2),
(29, 'qcm', 'Of all the students, she speaks ___.', '["more fluently", "most fluently", "fluenter", "fluentliest"]', 'most fluently', 'Superlatif adverbe en -ly → most', 1, 3),
(30, 'qcm', 'She ___ works on weekends.', '["hard", "hardly", "hardy", "harden"]', 'hardly', 'Hardly = presque jamais', 1, 1),
(30, 'fill_blank', 'He works very ___ (hard) every day.', NULL, 'hard', 'Hard = dur (sens différent de hardly)', 1, 2),
(30, 'qcm', 'I ___ know him. We just met.', '["hard", "hardly", "hardy", "harden"]', 'hardly', 'Presque pas → hardly', 1, 3),
(31, 'qcm', 'She sang beautifully ___ the concert ___ night.', '["at / last", "at / the last", "in / last", "in / the last"]', 'at / last', 'Adverbes : place puis temps', 1, 1),
(31, 'fill_blank', 'They arrived ___ (early) ___ (yesterday).', NULL, 'early / yesterday', 'Ordre : manière + temps', 1, 2),
(31, 'qcm', 'I ___ go to the cinema on Sundays.', '["always", "always go", "go always", "go always to"]', 'always go', 'Fréquence avant le verbe principal', 1, 3),
(32, 'qcm', 'She lives ___ Paris.', '["in", "on", "at", "to"]', 'in', 'Ville grande → in', 1, 1),
(32, 'qcm', 'There is a picture ___ the wall.', '["in", "on", "at", "to"]', 'on', 'Surface → on', 1, 2),
(32, 'fill_blank', 'I am waiting ___ the bus stop.', NULL, 'at', 'Point précis → at', 1, 3),
(33, 'qcm', 'The plane flew ___ the clouds.', '["above", "below", "between", "among"]', 'above', 'Au-dessus → above', 1, 1),
(33, 'fill_blank', 'The secret is ___ you and me.', NULL, 'between', 'Entre deux personnes → between', 1, 2),
(33, 'qcm', 'She hid ___ the crowd.', '["between", "among", "above", "under"]', 'among', 'Au milieu de plusieurs → among', 1, 3),
(34, 'qcm', 'I was born ___ 1995.', '["in", "on", "at", "by"]', 'in', 'Année → in', 1, 1),
(34, 'qcm', 'We have a meeting ___ Monday.', '["in", "on", "at", "by"]', 'on', 'Jour → on', 1, 2),
(34, 'fill_blank', 'The shop opens ___ 9 o''clock.', NULL, 'at', 'Heure précise → at', 1, 3),
(35, 'qcm', 'I have lived here ___ five years.', '["for", "since", "during", "while"]', 'for', 'Durée → for', 1, 1),
(35, 'qcm', 'I have lived here ___ 2018.', '["for", "since", "during", "while"]', 'since', 'Point de départ → since', 1, 2),
(35, 'fill_blank', '___ the summer, I traveled a lot.', NULL, 'During', 'Pendant une période → during', 1, 3),
(36, 'qcm', 'She walked ___ the room.', '["to", "into", "onto", "at"]', 'into', 'Entrer dans → into', 1, 1),
(36, 'fill_blank', 'He jumped ___ the table.', NULL, 'onto', 'Monter sur une surface → onto', 1, 2),
(36, 'qcm', 'I am going ___ school.', '["to", "into", "onto", "at"]', 'to', 'Direction générale → to', 1, 3),
(37, 'qcm', 'I prefer to travel ___ train.', '["by", "with", "on", "in"]', 'by', 'Moyen de transport → by', 1, 1),
(37, 'fill_blank', 'She cut the paper ___ scissors.', NULL, 'with', 'Instrument → with', 1, 2),
(37, 'qcm', 'He left ___ saying goodbye.', '["by", "with", "without", "out"]', 'without', 'Sans → without', 1, 3),
(38, 'qcm', 'We walked ___ the street to the other side.', '["across", "through", "past", "along"]', 'across', 'D''un côté à l''autre → across', 1, 1),
(38, 'fill_blank', 'The train went ___ the tunnel.', NULL, 'through', 'À travers → through', 1, 2),
(38, 'qcm', 'She walked ___ the river for an hour.', '["across", "through", "past", "along"]', 'along', 'Le long de → along', 1, 3),
(39, 'qcm', 'I wanted to go, ___ I was too tired.', '["and", "but", "or", "so"]', 'but', 'Contraste → but', 1, 1),
(39, 'fill_blank', 'She was ill, ___ she stayed home.', NULL, 'so', 'Conséquence → so', 1, 2),
(39, 'qcm', 'Would you like tea ___ coffee?', '["and", "but", "or", "so"]', 'or', 'Alternative → or', 1, 3),
(40, 'qcm', 'I stayed home ___ it was raining.', '["because", "although", "but", "so"]', 'because', 'Cause → because', 1, 1),
(40, 'fill_blank', '___ you are here, let''s start the meeting.', NULL, 'Since', 'Cause connue → since', 1, 2),
(40, 'qcm', '___ the weather was bad, we went out.', '["Because", "Although", "But", "So"]', 'Although', 'Concession → although', 1, 3),
(41, 'qcm', 'You will fail ___ you study hard.', '["if", "unless", "because", "although"]', 'unless', 'À moins que → unless', 1, 1),
(41, 'fill_blank', 'You can go out ___ you finish your homework.', NULL, 'as long as', 'À condition que → as long as', 1, 2),
(41, 'qcm', '___ it rains, I will stay home.', '["If", "Unless", "Although", "Because"]', 'If', 'Condition → if', 1, 3),
(42, 'qcm', '___ I was eating, the phone rang.', '["When", "While", "Before", "Until"]', 'While', 'Pendant que → while (durée)', 1, 1),
(42, 'fill_blank', 'Call me ___ you arrive.', NULL, 'as soon as', 'Dès que → as soon as', 1, 2),
(42, 'qcm', 'I will wait ___ you come back.', '["when", "while", "before", "until"]', 'until', 'Jusqu''à ce que → until', 1, 3),
(43, 'qcm', '___ it was expensive, I bought it.', '["Although", "Because", "So", "But"]', 'Although', 'Concession → although', 1, 1),
(43, 'fill_blank', 'He is rich, ___ his brother is poor.', NULL, 'whereas', 'Contraste → whereas', 1, 2),
(43, 'qcm', '___ she is young, she is very mature.', '["Although", "Because", "So", "But"]', 'Although', 'Bien que → although', 1, 3),
(44, 'qcm', '___ John ___ Mary are coming to the party.', '["Both / and", "Either / or", "Neither / nor", "Not only / but also"]', 'Both / and', 'Les deux → both...and', 1, 1),
(44, 'fill_blank', 'You can ___ stay ___ leave. It''s up to you.', NULL, 'either / or', 'L''un ou l''autre → either...or', 1, 2),
(44, 'qcm', '___ John ___ Mary is coming. They are both busy.', '["Both / and", "Either / or", "Neither / nor", "Not only / but also"]', 'Neither / nor', 'Aucun des deux → neither...nor', 1, 3),
(45, 'qcm', 'The weather was bad. ___, we had a great time.', '["However", "Therefore", "Because", "So"]', 'However', 'Opposition → however', 1, 1),
(45, 'fill_blank', 'She was ill. ___, she stayed home.', NULL, 'Therefore', 'Conséquence → therefore', 1, 2),
(45, 'qcm', 'It was raining. ___, we went out.', '["However", "Therefore", "Because", "So"]', 'However', 'Cependant → however', 1, 3),
(46, 'qcm', 'She is ___ engineer.', '["a", "an", "the", "-"]', 'an', 'Voyelle → an', 1, 1),
(46, 'qcm', 'I saw ___ dog in the park.', '["a", "an", "the", "-"]', 'a', 'Première mention → a', 1, 2),
(46, 'fill_blank', 'He is ___ honest man.', NULL, 'an', 'H muet → voyelle → an', 1, 3),
(47, 'qcm', '___ sun rises in the east.', '["A", "An", "The", "-"]', 'The', 'Unique → the', 1, 1),
(47, 'fill_blank', 'I saw a cat. ___ cat was black.', NULL, 'The', 'Deuxième mention → the', 1, 2),
(47, 'qcm', 'She is ___ best student in the class.', '["a", "an", "the", "-"]', 'the', 'Superlatif → the', 1, 3),
(48, 'qcm', 'Would you like ___ coffee?', '["some", "any", "a", "the"]', 'some', 'Offre → some', 1, 1),
(48, 'qcm', 'I don''t have ___ money.', '["some", "any", "a", "the"]', 'any', 'Négation → any', 1, 2),
(48, 'fill_blank', 'Do you have ___ questions?', NULL, 'any', 'Interrogation → any', 1, 3),
(49, 'qcm', 'How ___ water do you need?', '["much", "many", "a lot of", "few"]', 'much', 'Indénombrable → much', 1, 1),
(49, 'qcm', 'How ___ books did you read?', '["much", "many", "a lot of", "little"]', 'many', 'Dénombrable → many', 1, 2),
(49, 'fill_blank', 'I have ___ of friends.', NULL, 'a lot', 'Beaucoup de → a lot of', 1, 3),
(50, 'qcm', '___ people came to the party. It was a success.', '["Few", "A few", "Little", "A little"]', 'A few', 'Quelques-uns, positif → a few', 1, 1),
(50, 'qcm', '___ people came. It was disappointing.', '["Few", "A few", "Little", "A little"]', 'Few', 'Presque personne, négatif → few', 1, 2),
(50, 'fill_blank', 'There is ___ milk left. We need to buy more.', NULL, 'little', 'Presque rien → little', 1, 3);

-- Exercices leçons 51-80
INSERT INTO grammar_exercises (lesson_id, type, question, options, correct_answer, explanation, points, order_index) VALUES
(51, 'qcm', '___ is my best friend.', '["I", "He", "She", "They"]', 'She', 'Sujet féminin → she', 1, 1),
(51, 'fill_blank', '___ (we) are going to the cinema tonight.', NULL, 'We', 'Sujet pluriel 1e personne', 1, 2),
(51, 'qcm', '___ is raining outside.', '["He", "She", "It", "They"]', 'It', 'Sujet impersonnel → it', 1, 3),
(52, 'qcm', 'She loves ___.', '["he", "him", "his", "himself"]', 'him', 'Objet masculin → him', 1, 1),
(52, 'fill_blank', 'Please give this book to ___ (I).', NULL, 'me', 'Objet 1e personne → me', 1, 2),
(52, 'qcm', 'Can you help ___ with this exercise?', '["I", "me", "my", "mine"]', 'me', 'Objet → me', 1, 3),
(53, 'qcm', 'This is ___ book.', '["my", "mine", "me", "I"]', 'my', 'Adjectif possessif → my', 1, 1),
(53, 'qcm', 'This book is ___.', '["my", "mine", "me", "I"]', 'mine', 'Pronom possessif → mine', 1, 2),
(53, 'fill_blank', 'That car is ___ (she).', NULL, 'hers', 'Pronom possessif → hers', 1, 3),
(54, 'qcm', 'She looked at ___ in the mirror.', '["her", "herself", "she", "hers"]', 'herself', 'Action réflexive → herself', 1, 1),
(54, 'fill_blank', 'I did it ___ (I).', NULL, 'myself', 'Insistance → myself', 1, 2),
(54, 'qcm', 'He lives by ___.', '["him", "himself", "his", "he"]', 'himself', 'Seul → by himself', 1, 3),
(55, 'qcm', '___ book is on the table (proche).', '["This", "That", "These", "Those"]', 'This', 'Singulier proche → this', 1, 1),
(55, 'qcm', '___ cars are expensive (loin, pluriel).', '["This", "That", "These", "Those"]', 'Those', 'Pluriel loin → those', 1, 2),
(55, 'fill_blank', '___ (this) apples are fresh.', NULL, 'These', 'Pluriel proche → these', 1, 3),
(56, 'qcm', 'Is ___ at the door?', '["somebody", "anybody", "nobody", "everybody"]', 'anybody', 'Interrogation → anybody', 1, 1),
(56, 'qcm', '___ knows the answer.', '["Somebody", "Anybody", "Nobody", "Everybody"]', 'Everybody', 'Tout le monde → everybody', 1, 2),
(56, 'fill_blank', 'There is ___ in the room. It is empty.', NULL, 'nobody', 'Personne → nobody', 1, 3),
(57, 'qcm', 'The man ___ called you is my boss.', '["who", "which", "that", "whose"]', 'who', 'Personne → who', 1, 1),
(57, 'qcm', 'The book ___ I read was interesting.', '["who", "which", "that", "whose"]', 'that', 'Chose → that', 1, 2),
(57, 'fill_blank', 'The woman ___ car was stolen reported it to the police.', NULL, 'whose', 'Possession → whose', 1, 3),
(58, 'qcm', '___ is your name?', '["Who", "What", "Which", "Whose"]', 'What', 'Chose → what', 1, 1),
(58, 'qcm', '___ car is this?', '["Who", "What", "Which", "Whose"]', 'Whose', 'Possession → whose', 1, 2),
(58, 'fill_blank', '___ did you see at the party?', NULL, 'Who', 'Personne sujet → who', 1, 3),
(59, 'qcm', 'They looked at ___.', '["each other", "one another", "them", "themselves"]', 'each other', 'Deux personnes → each other', 1, 1),
(59, 'fill_blank', 'The team members helped ___.', NULL, 'one another', 'Plusieurs → one another', 1, 2),
(59, 'qcm', 'They have known ___ for years.', '["each other", "one another", "them", "themselves"]', 'each other', 'Réciproque → each other', 1, 3),
(60, 'qcm', '___ must be careful when crossing the street.', '["One", "You", "He", "They"]', 'You', 'Généralité courante → you', 1, 1),
(60, 'fill_blank', 'In formal English, ___ should always be polite.', NULL, 'one', 'Formel → one', 1, 2),
(60, 'qcm', '___ should always wear a seatbelt.', '["One", "You", "He", "They"]', 'You', 'Conseil général → you', 1, 3),
(61, 'qcm', 'The room ___ every day.', '["is cleaned", "cleans", "cleaned", "is cleaning"]', 'is cleaned', 'Passif présent → is + PP', 1, 1),
(61, 'fill_blank', 'The letter ___ (write) yesterday.', NULL, 'was written', 'Passé → was + PP', 1, 2),
(61, 'qcm', 'English ___ all over the world.', '["speaks", "is spoken", "spoke", "is speaking"]', 'is spoken', 'Passif général', 1, 3),
(62, 'qcm', 'The report ___ be finished by Friday.', '["must", "must be", "must to be", "must being"]', 'must be', 'Passif + modal → modal + be + PP', 1, 1),
(62, 'fill_blank', 'The book ___ (write) by Hemingway.', NULL, 'was written', 'Passif + agent', 1, 2),
(62, 'qcm', 'My car ___ last night.', '["stole", "was stolen", "is stolen", "has stolen"]', 'was stolen', 'Passif passé', 1, 3),
(63, 'qcm', 'She said, "I am tired." → She said (that) she ___ tired.', '["is", "was", "were", "am"]', 'was', 'Reported speech → présent devient passé', 1, 1),
(63, 'fill_blank', '"I have finished," he said. → He said he ___ (finish).', NULL, 'had finished', 'Present perfect → past perfect', 1, 2),
(63, 'qcm', '"I will call you," she said. → She said she ___ call me.', '["will", "would", "can", "could"]', 'would', 'Will → would', 1, 3),
(64, 'qcm', '"Are you coming?" he asked. → He asked if she ___.', '["is coming", "was coming", "came", "comes"]', 'was coming', 'Question fermée → if + sujet + verbe', 1, 1),
(64, 'fill_blank', '"Where do you live?" she asked. → She asked where he ___ (live).', NULL, 'lived', 'Question ouverte → mot interrogatif + sujet + verbe', 1, 2),
(64, 'qcm', '"Wait here," he said. → He told me ___ here.', '["wait", "to wait", "waiting", "waited"]', 'to wait', 'Ordre → tell + object + to + infinitif', 1, 3),
(65, 'qcm', 'If you heat ice, it ___.', '["melts", "melted", "will melt", "would melt"]', 'melts', 'Zero conditional → présent/présent', 1, 1),
(65, 'fill_blank', 'If it rains, I ___ (stay) home.', NULL, 'will stay', 'First conditional → if + présent, will + base', 1, 2),
(65, 'qcm', 'If I ___ the lottery, I would buy a house.', '["win", "won", "will win", "would win"]', 'won', 'Second conditional → if + prétérit', 1, 3),
(66, 'qcm', 'If I ___ rich, I would travel the world.', '["am", "were", "was", "be"]', 'were', 'Second conditional → were (toutes personnes)', 1, 1),
(66, 'fill_blank', 'If she ___ (have) more time, she would learn French.', NULL, 'had', 'If + prétérit → would + base', 1, 2),
(66, 'qcm', 'If I were you, I ___ accept the offer.', '["will", "would", "can", "should"]', 'would', 'Conseil hypothétique → would', 1, 3),
(67, 'qcm', 'If I had studied harder, I ___ the exam.', '["pass", "would pass", "would have passed", "had passed"]', 'would have passed', 'Third conditional → would have + PP', 1, 1),
(67, 'fill_blank', 'If she had left earlier, she ___ (not/miss) the train.', NULL, 'would not have missed', 'Third conditional négatif', 1, 2),
(67, 'qcm', 'If he ___ the truth, he would have told us.', '["knows", "knew", "had known", "has known"]', 'had known', 'Third conditional → if + past perfect', 1, 3),
(68, 'qcm', 'I wish I ___ taller.', '["am", "were", "was", "be"]', 'were', 'Wish + prétérit (présent irréel)', 1, 1),
(68, 'fill_blank', 'I wish I ___ (have) a car.', NULL, 'had', 'Wish + prétérit', 1, 2),
(68, 'qcm', 'If only she ___ the truth!', '["knows", "knew", "know", "had known"]', 'knew', 'If only + prétérit', 1, 3),
(69, 'qcm', 'I wish I ___ studied medicine.', '["have", "had", "would have", "have had"]', 'had', 'Wish + past perfect (regret)', 1, 1),
(69, 'fill_blank', 'She wishes she ___ (never/meet) him.', NULL, 'had never met', 'Regret passé', 1, 2),
(69, 'qcm', 'If only I ___ harder!', '["study", "studied", "had studied", "have studied"]', 'had studied', 'Regret → if only + past perfect', 1, 3),
(70, 'qcm', 'I ___ my hair cut yesterday.', '["had", "have", "got", "did"]', 'had', 'Causative → have + object + PP', 1, 1),
(70, 'fill_blank', 'She is getting the car ___ (repair).', NULL, 'repaired', 'Get + object + PP', 1, 2),
(70, 'qcm', 'I ___ him fix my computer.', '["let", "made", "had", "got"]', 'had', 'Have + object + infinitif', 1, 3),
(71, 'qcm', 'I ___ smoke, but I quit.', '["used to", "am used to", "use to", "was used to"]', 'used to', 'Used to = habitude passée', 1, 1),
(71, 'qcm', 'I ___ waking up early.', '["used to", "am used to", "use to", "was used to"]', 'am used to', 'Be used to = être habitué', 1, 2),
(71, 'fill_blank', 'I ___ (get used) to the noise after a week.', NULL, 'got used', 'Devenir habitué → get used to', 1, 3),
(72, 'qcm', 'It is ___ cold to go out.', '["very", "too", "enough", "so"]', 'too', 'Too = trop (négatif)', 1, 1),
(72, 'qcm', 'He is not tall ___ to reach the shelf.', '["too", "enough", "so", "very"]', 'enough', 'Not + adj + enough', 1, 2),
(72, 'fill_blank', 'The box is ___ (heavy) for me to carry.', NULL, 'too heavy', 'Too heavy = trop lourd', 1, 3),
(73, 'qcm', 'It was ___ cold that we stayed inside.', '["very", "too", "enough", "so"]', 'so', 'So + adj + that', 1, 1),
(73, 'fill_blank', 'It was ___ a good film that I saw it twice.', NULL, 'such', 'Such + a/an + adj + nom', 1, 2),
(73, 'qcm', 'She is ___ kind.', '["very", "too", "so", "such"]', 'so', 'So + adjectif (sans nom)', 1, 3),
(74, 'qcm', '___ you like apples?', '["Do", "Does", "Are", "Is"]', 'Do', 'Question présent simple → Do + sujet', 1, 1),
(74, 'fill_blank', '___ (be) you happy?', NULL, 'Are', 'Question avec BE', 1, 2),
(74, 'qcm', '___ she eat meat?', '["Do", "Does", "Is", "Are"]', 'Does', '3e personne → Does', 1, 3),
(75, 'qcm', 'You are happy, ___ you?', '["aren''t", "are", "don''t", "do"]', 'aren''t', 'Tag négatif après phrase positive', 1, 1),
(75, 'qcm', 'She hasn''t left, ___ she?', '["has", "hasn''t", "did", "didn''t"]', 'has', 'Tag positif après phrase négative', 1, 2),
(75, 'fill_blank', 'Let''s go, ___ we?', NULL, 'shall', 'Let''s → shall we', 1, 3),
(76, 'qcm', '___ have I seen such beauty.', '["Never", "Always", "Sometimes", "Often"]', 'Never', 'Never + inversion', 1, 1),
(76, 'fill_blank', '___ (hardly/I/arrive) when it started to rain.', NULL, 'Hardly had I arrived', 'Hardly + inversion', 1, 2),
(76, 'qcm', '___ I rich, I would travel.', '["If", "Were", "Was", "Am"]', 'Were', 'Conditionnel sans if → Were', 1, 3),
(77, 'qcm', 'It was John ___ bought a car.', '["who", "which", "that", "whose"]', 'who', 'Cleft sentence avec personne', 1, 1),
(77, 'fill_blank', 'It was ___ that John bought yesterday.', NULL, 'a car', 'Emphase sur l''objet', 1, 2),
(77, 'qcm', 'It was yesterday ___ John bought a car.', '["who", "which", "that", "when"]', 'that', 'Emphase sur le temps → that', 1, 3),
(78, 'qcm', 'I ___ like you!', '["do", "does", "did", "am"]', 'do', 'Emphatic do', 1, 1),
(78, 'fill_blank', '___ be careful!', NULL, 'Do', 'Emphase impérative', 1, 2),
(78, 'qcm', 'He ___ finish his homework.', '["do", "does", "did", "done"]', 'did', 'Emphase passée → did', 1, 3),
(79, 'qcm', 'I enjoy ___ tennis.', '["play", "playing", "to play", "played"]', 'playing', 'Enjoy + gérondif', 1, 1),
(79, 'qcm', 'She wants ___ to Paris.', '["go", "going", "to go", "gone"]', 'to go', 'Want + infinitif', 1, 2),
(79, 'fill_blank', 'He is good at ___ (swim).', NULL, 'swimming', 'At + gérondif', 1, 3),
(80, 'qcm', 'Stop ___! It is bad for your health.', '["smoke", "smoking", "to smoke", "smoked"]', 'smoking', 'Stop + gérondif = arrêter une activité', 1, 1),
(80, 'fill_blank', 'He stopped ___ (tie) his shoelaces.', NULL, 'to tie', 'Stop + infinitif = s''arrêter pour faire', 1, 2),
(80, 'qcm', 'I remember ___ the door. I am sure I did it.', '["lock", "locking", "to lock", "locked"]', 'locking', 'Remember + gérondif = souvenir d''avoir fait', 1, 3);

-- Exercices leçons 81-110
INSERT INTO grammar_exercises (lesson_id, type, question, options, correct_answer, explanation, points, order_index) VALUES
(81, 'qcm', 'I ___ at 7 AM every day.', '["get up", "get on", "get in", "get off"]', 'get up', 'Se lever → get up', 1, 1),
(81, 'fill_blank', 'Please ___ (turn on) the TV.', NULL, 'turn on', 'Allumer → turn on', 1, 2),
(81, 'qcm', 'I am ___ my keys. I can''t find them.', '["looking for", "looking at", "looking after", "looking up"]', 'looking for', 'Chercher → look for', 1, 3),
(82, 'qcm', 'Please turn ___ the TV.', '["off", "on", "up", "down"]', 'off', 'Éteindre → turn off', 1, 1),
(82, 'fill_blank', 'She ___ (take off) her coat when she entered.', NULL, 'took off', 'Enlever → take off', 1, 2),
(82, 'qcm', 'I need to ___ this form before submitting.', '["fill in", "fill on", "fill at", "fill with"]', 'fill in', 'Remplir → fill in', 1, 3),
(83, 'qcm', 'She ___ a decision yesterday.', '["did", "made", "took", "had"]', 'made', 'Make a decision = prendre une décision', 1, 1),
(83, 'fill_blank', 'Can I ___ (take) a photo?', NULL, 'take', 'Take a photo = prendre une photo', 1, 2),
(83, 'qcm', 'I need to ___ my homework.', '["do", "make", "take", "have"]', 'do', 'Do homework = faire ses devoirs', 1, 3),
(84, 'qcm', '"___!" he shouted before the concert.', '["Break a leg", "Hit the sack", "Bite the bullet", "Let the cat out"]', 'Break a leg', 'Bonne chance → break a leg', 1, 1),
(84, 'fill_blank', 'It is raining ___ (cats/dogs).', NULL, 'cats and dogs', 'Il pleut des cordes', 1, 2),
(84, 'qcm', 'I only eat fast food ___.', '["break a leg", "once in a blue moon", "hit the sack", "bite the bullet"]', 'once in a blue moon', 'Rarement → once in a blue moon', 1, 3),
(85, 'qcm', 'Please ___ the music. I can''t hear it.', '["listen", "listen to", "hear", "hear to"]', 'listen to', 'Listen to = écouter', 1, 1),
(85, 'fill_blank', 'I am waiting ___ the bus.', NULL, 'for', 'Wait for = attendre', 1, 2),
(85, 'qcm', 'She ___ on her parents for money.', '["depends", "depends on", "depends in", "depends at"]', 'depends on', 'Depend on = dépendre de', 1, 3),
(86, 'qcm', '___ Sir or Madam, I am writing to inquire about...', '["Dear", "Hey", "Hi", "Hello"]', 'Dear', 'Formel → Dear Sir or Madam', 1, 1),
(86, 'fill_blank', '___ (formel) you please send me the document?', NULL, 'Could', 'Formel → Could you please', 1, 2),
(86, 'qcm', '"Hey! How''s it going?" is ___.', '["formal", "informal", "professional", "academic"]', 'informal', 'Hey → informel', 1, 3),
(87, 'qcm', '___ means "en fait" in French.', '["Actually", "Currently", "Eventually", "Finally"]', 'Actually', 'Actually = en fait (pas actuellement)', 1, 1),
(87, 'fill_blank', 'I ___ (actuellement) live in Paris.', NULL, 'currently', 'Currently = actuellement', 1, 2),
(87, 'qcm', 'A ___ is where you buy books.', '["library", "bookshop", "librarie", "bookstore"]', 'bookshop', 'Bookshop = librairie', 1, 3),
(88, 'qcm', 'In the UK, an ___ is a lift.', '["elevator", "escalator", "apartment", "flat"]', 'elevator', 'UK: lift = US: elevator', 1, 1),
(88, 'fill_blank', 'In the US, people live in an ___ (UK: flat).', NULL, 'apartment', 'US: apartment = UK: flat', 1, 2),
(88, 'qcm', 'In the UK, ___ are what Americans call fries.', '["chips", "crisps", "biscuits", "cookies"]', 'chips', 'UK chips = US fries', 1, 3),
(89, 'qcm', 'Which sentence is correct?', '["I don''t know nothing.", "I don''t know anything.", "I know nothing.", "Both 2 and 3"]', 'Both 2 and 3', 'Pas de double négation en anglais standard', 1, 1),
(89, 'fill_blank', 'I ___ (not/see) anybody.', NULL, 'do not see', 'Négation standard', 1, 2),
(89, 'qcm', 'I ___ know him.', '["hardly", "don''t", "never", "no"]', 'hardly', 'Hardly = presque pas', 1, 3),
(90, 'qcm', 'She is ___ tall as her brother.', '["as", "so", "too", "very"]', 'as', 'As...as = aussi...que', 1, 1),
(90, 'fill_blank', 'He runs ___ fast ___ me.', NULL, 'as / as', 'As fast as = aussi vite que', 1, 2),
(90, 'qcm', 'He is not ___ rich as his father.', '["as", "so", "too", "very"]', 'so', 'Not so...as = pas aussi...que', 1, 3),
(91, 'qcm', '21 in English is ___.', '["twenty-one", "twenty one", "twentie-one", "twentie one"]', 'twenty-one', '21 = twenty-one', 1, 1),
(91, 'fill_blank', 'The 3rd month is ___ (ordinal).', NULL, 'March', 'Troisième mois', 1, 2),
(91, 'qcm', 'In the UK, 14/03/2024 is written as ___.', '["14th March 2024", "March 14, 2024", "March 14th, 2024", "14 March 2024"]', '14th March 2024', 'Format UK', 1, 3),
(92, 'qcm', 'She ___ me go.', '["let", "made", "had", "got"]', 'let', 'Let + infinitif sans to', 1, 1),
(92, 'fill_blank', 'She ___ (make) me laugh.', NULL, 'made', 'Make + infinitif sans to', 1, 2),
(92, 'qcm', 'I ___ him repair my computer.', '["let", "made", "had", "got"]', 'had', 'Have + object + infinitif', 1, 3),
(93, 'qcm', 'I ___ stay home tonight.', '["would rather", "would like", "prefer", "want"]', 'would rather', 'Would rather = préférer', 1, 1),
(93, 'fill_blank', 'You ___ better hurry.', NULL, 'had', 'Had better = conseil fort', 1, 2),
(93, 'qcm', 'I would rather you ___ smoke here.', '["don''t", "didn''t", "not", "wouldn''t"]', 'didn''t', 'Would rather + sujet + prétérit', 1, 3),
(94, 'qcm', '___ is a book on the table.', '["There", "It", "Here", "That"]', 'There', 'There is = existence', 1, 1),
(94, 'fill_blank', '___ are three chairs in the room.', NULL, 'There', 'There are = existence pluriel', 1, 2),
(94, 'qcm', '___ was a problem yesterday.', '["There", "It", "Here", "That"]', 'There', 'There was = passé', 1, 3),
(95, 'qcm', '___ is raining.', '["He", "She", "It", "There"]', 'It', 'It = temps', 1, 1),
(95, 'fill_blank', '___ is 10 kilometres to the city.', NULL, 'It', 'It = distance', 1, 2),
(95, 'qcm', '___ is important to study.', '["He", "She", "It", "There"]', 'It', 'It = sujet factice', 1, 3),
(96, 'qcm', 'She is ___ than her brother.', '["tall", "taller", "tallest", "more tall"]', 'taller', 'Comparatif court → -er', 1, 1),
(96, 'fill_blank', 'She is ___ (beautiful) than her sister.', NULL, 'more beautiful', 'Comparatif long → more', 1, 2),
(96, 'qcm', 'He is ___ player in the team.', '["good", "better", "the best", "best"]', 'the best', 'Superlatif avec the', 1, 3),
(97, 'qcm', 'This is ___ book.', '["the boy''s", "the boys''", "the boys''s", "the boy''"]', 'the boy''s', 'Possessif singulier', 1, 1),
(97, 'fill_blank', 'This is the ___ (boys) room.', NULL, 'boys''', 'Possessif pluriel', 1, 2),
(97, 'qcm', 'Its tail / It''s tail : which is correct?', '["Its tail", "It''s tail", "Both", "Neither"]', 'Its tail', 'Its = possessif sans apostrophe', 1, 3),
(98, 'qcm', 'She ___ like coffee.', '["do not", "does not", "is not", "are not"]', 'does not', '3e personne négation → does not', 1, 1),
(98, 'fill_blank', 'He ___ (be) not here.', NULL, 'is', 'BE + not', 1, 2),
(98, 'qcm', 'I ___ swim.', '["do not", "does not", "am not", "can not"]', 'can not', 'Modal + not', 1, 3),
(99, 'qcm', '___ you like pizza?', '["Do", "Does", "Are", "Is"]', 'Do', 'Question fermée → Do', 1, 1),
(99, 'fill_blank', '___ do you live?', NULL, 'Where', 'Question ouverte → Where', 1, 2),
(99, 'qcm', '___ did you speak to?', '["To whom", "Whom", "Who", "All of the above"]', 'All of the above', 'Toutes les formes possibles', 1, 3),
(100, 'qcm', 'I speak ___.', '["the French", "French", "a French", "the France"]', 'French', 'Langue sans article', 1, 1),
(100, 'fill_blank', 'I live in ___ (France).', NULL, 'France', 'Pays sans article', 1, 2),
(100, 'qcm', '___ United States is a big country.', '["A", "An", "The", "-"]', 'The', 'Nom pluriel → the', 1, 3),
(101, 'qcm', 'I have three ___.', '["book", "books", "a book", "the book"]', 'books', 'Dénombrable pluriel', 1, 1),
(101, 'fill_blank', 'I need some ___ (information).', NULL, 'information', 'Indénombrable', 1, 2),
(101, 'qcm', 'How ___ money do you have?', '["many", "much", "a lot of", "few"]', 'much', 'Indénombrable → much', 1, 3),
(102, 'qcm', '___ students passed the exam.', '["All", "Both", "Either", "Neither"]', 'All', 'Tous (3+) → all', 1, 1),
(102, 'fill_blank', '___ answers are correct.', NULL, 'Both', 'Les deux → both', 1, 2),
(102, 'qcm', '___ day is fine for me.', '["All", "Both", "Either", "Neither"]', 'Either', 'L''un ou l''autre → either', 1, 3),
(103, 'qcm', '___ student has a book.', '["Every", "Each", "All", "Both"]', 'Every', 'Ensemble → every', 1, 1),
(103, 'fill_blank', '___ student has his own book.', NULL, 'Each', 'Individuellement → each', 1, 2),
(103, 'qcm', '___ of my friends came.', '["None", "All", "Both", "Every"]', 'None', 'Aucun → none of', 1, 3),
(104, 'qcm', 'He is a ___ actor.', '["well-known", "well known", "wellknown", "known-well"]', 'well-known', 'Adjectif composé avec trait d''union', 1, 1),
(104, 'fill_blank', 'She is very ___ (hard/work).', NULL, 'hard-working', 'Hard-working = travailleur', 1, 2),
(104, 'qcm', 'The actor is ___.', '["well-known", "well known", "wellknown", "known-well"]', 'well-known', 'Après BE → bien avec trait d''union', 1, 3),
(105, 'qcm', 'Un- + happy = ___.', '["unhappy", "inhappy", "dishappy", "nonhappy"]', 'unhappy', 'Préfixe un-', 1, 1),
(105, 'fill_blank', 'Re- + write = ___', NULL, 'rewrite', 'Préfixe re-', 1, 2),
(105, 'qcm', 'Happy + -ness = ___.', '["happiness", "happyness", "happily", "happyment"]', 'happiness', 'Suffixe -ness', 1, 3),
(106, 'qcm', 'I was tired. ___, I finished the work.', '["However", "Therefore", "Moreover", "In addition"]', 'However', 'Opposition → however', 1, 1),
(106, 'fill_blank', 'She was ill. ___, she stayed home.', NULL, 'Therefore', 'Conséquence → therefore', 1, 2),
(106, 'qcm', '___, the project was a success.', '["In conclusion", "However", "Moreover", "In addition"]', 'In conclusion', 'Conclusion', 1, 3),
(107, 'qcm', 'He suggested that she ___ early.', '["comes", "come", "came", "will come"]', 'come', 'Subjonctif → base verbale', 1, 1),
(107, 'fill_blank', 'It is important that he ___ (be) here.', NULL, 'be', 'Subjonctif → be', 1, 2),
(107, 'qcm', 'God ___ the Queen!', '["saves", "save", "saving", "saved"]', 'save', 'Formule fixe → subjonctif', 1, 3),
(108, 'qcm', 'My brother, ___ doctor, lives in London.', '["a", "an", "the", "-"]', 'a', 'Apposition avec article', 1, 1),
(108, 'fill_blank', 'Paris, ___ capital of France, is beautiful.', NULL, 'the', 'Apposition avec the', 1, 2),
(108, 'qcm', 'The writer ___ is famous.', '["Hemingway", "a Hemingway", "the Hemingway", "an Hemingway"]', 'Hemingway', 'Apposition sans article', 1, 3),
(109, 'qcm', '"Are you coming?" "Yes, I ___."', '["am coming", "am", "come", "coming"]', 'am', 'Ellipsis → am', 1, 1),
(109, 'fill_blank', 'She sings and (she) ___ (dance).', NULL, 'dances', 'Ellipsis du sujet', 1, 2),
(109, 'qcm', 'She sings better than I ___.', '["sing", "do", "am", "sings"]', 'do', 'Ellipsis avec do', 1, 3),
(110, 'qcm', '___ have I seen such beauty.', '["Never", "Always", "Sometimes", "Often"]', 'Never', 'Inversion avancée', 1, 1),
(110, 'fill_blank', 'If I had studied, I ___ (be) a doctor now.', NULL, 'would be', 'Conditionnel mixte', 1, 2),
(110, 'qcm', 'It was John ___ bought the car.', '["who", "which", "that", "whom"]', 'who', 'Cleft sentence avancé', 1, 3);
