CREATE TABLE IF NOT EXISTS number_exercises (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  type TEXT NOT NULL CHECK(type IN ('digit_to_word', 'word_to_digit', 'ordinal', 'time', 'date', 'large_number', 'fraction', 'percentage', 'decimal', 'mixed')),
  hint TEXT,
  difficulty TEXT CHECK(difficulty IN ('easy', 'medium', 'hard')) DEFAULT 'easy',
  category TEXT DEFAULT 'numbers'
);

INSERT INTO number_exercises (question, answer, type, hint, difficulty, category) VALUES
-- CHIFFRES 0-20 (digit_to_word)
('0', 'zero', 'digit_to_word', NULL, 'easy', 'numbers'),
('1', 'one', 'digit_to_word', NULL, 'easy', 'numbers'),
('2', 'two', 'digit_to_word', NULL, 'easy', 'numbers'),
('3', 'three', 'digit_to_word', NULL, 'easy', 'numbers'),
('4', 'four', 'digit_to_word', NULL, 'easy', 'numbers'),
('5', 'five', 'digit_to_word', NULL, 'easy', 'numbers'),
('6', 'six', 'digit_to_word', NULL, 'easy', 'numbers'),
('7', 'seven', 'digit_to_word', NULL, 'easy', 'numbers'),
('8', 'eight', 'digit_to_word', NULL, 'easy', 'numbers'),
('9', 'nine', 'digit_to_word', NULL, 'easy', 'numbers'),
('10', 'ten', 'digit_to_word', NULL, 'easy', 'numbers'),
('11', 'eleven', 'digit_to_word', NULL, 'easy', 'numbers'),
('12', 'twelve', 'digit_to_word', NULL, 'easy', 'numbers'),
('13', 'thirteen', 'digit_to_word', NULL, 'easy', 'numbers'),
('14', 'fourteen', 'digit_to_word', NULL, 'easy', 'numbers'),
('15', 'fifteen', 'digit_to_word', NULL, 'easy', 'numbers'),
('16', 'sixteen', 'digit_to_word', NULL, 'easy', 'numbers'),
('17', 'seventeen', 'digit_to_word', NULL, 'easy', 'numbers'),
('18', 'eighteen', 'digit_to_word', NULL, 'easy', 'numbers'),
('19', 'nineteen', 'digit_to_word', NULL, 'easy', 'numbers'),
('20', 'twenty', 'digit_to_word', NULL, 'easy', 'numbers'),

-- DIZAINES (digit_to_word)
('30', 'thirty', 'digit_to_word', NULL, 'easy', 'numbers'),
('40', 'forty', 'digit_to_word', 'Attention à l''orthographe', 'easy', 'numbers'),
('50', 'fifty', 'digit_to_word', NULL, 'easy', 'numbers'),
('60', 'sixty', 'digit_to_word', NULL, 'easy', 'numbers'),
('70', 'seventy', 'digit_to_word', NULL, 'easy', 'numbers'),
('80', 'eighty', 'digit_to_word', NULL, 'easy', 'numbers'),
('90', 'ninety', 'digit_to_word', NULL, 'easy', 'numbers'),
('100', 'one hundred', 'digit_to_word', NULL, 'easy', 'numbers'),

-- NOMBRES COMPOSÉS 21-99 (digit_to_word)
('21', 'twenty-one', 'digit_to_word', 'Tiret obligatoire', 'easy', 'numbers'),
('35', 'thirty-five', 'digit_to_word', 'Tiret obligatoire', 'easy', 'numbers'),
('42', 'forty-two', 'digit_to_word', NULL, 'easy', 'numbers'),
('58', 'fifty-eight', 'digit_to_word', NULL, 'easy', 'numbers'),
('63', 'sixty-three', 'digit_to_word', NULL, 'easy', 'numbers'),
('77', 'seventy-seven', 'digit_to_word', NULL, 'easy', 'numbers'),
('84', 'eighty-four', 'digit_to_word', NULL, 'easy', 'numbers'),
('99', 'ninety-nine', 'digit_to_word', NULL, 'easy', 'numbers'),

-- CENTAINES (digit_to_word)
('101', 'one hundred and one', 'digit_to_word', 'and obligatoire en GB', 'medium', 'numbers'),
('150', 'one hundred and fifty', 'digit_to_word', NULL, 'medium', 'numbers'),
('200', 'two hundred', 'digit_to_word', NULL, 'easy', 'numbers'),
('350', 'three hundred and fifty', 'digit_to_word', NULL, 'medium', 'numbers'),
('500', 'five hundred', 'digit_to_word', NULL, 'easy', 'numbers'),
('999', 'nine hundred and ninety-nine', 'digit_to_word', NULL, 'medium', 'numbers'),

-- MILLIERS (digit_to_word)
('1,000', 'one thousand', 'digit_to_word', NULL, 'easy', 'numbers'),
('1,500', 'one thousand five hundred', 'digit_to_word', NULL, 'medium', 'numbers'),
('2,000', 'two thousand', 'digit_to_word', NULL, 'easy', 'numbers'),
('10,000', 'ten thousand', 'digit_to_word', NULL, 'medium', 'numbers'),
('100,000', 'one hundred thousand', 'digit_to_word', NULL, 'medium', 'numbers'),
('1,000,000', 'one million', 'digit_to_word', NULL, 'easy', 'numbers'),
('2,500,000', 'two million five hundred thousand', 'digit_to_word', NULL, 'hard', 'numbers'),
('1,000,000,000', 'one billion', 'digit_to_word', 'billion = milliard', 'medium', 'numbers'),

-- ÉCRITURE EN CHIFFRES (word_to_digit)
('twenty-three', '23', 'word_to_digit', NULL, 'easy', 'numbers'),
('forty-five', '45', 'word_to_digit', NULL, 'easy', 'numbers'),
('sixty-seven', '67', 'word_to_digit', NULL, 'easy', 'numbers'),
('eighty-nine', '89', 'word_to_digit', NULL, 'easy', 'numbers'),
('one hundred and twelve', '112', 'word_to_digit', NULL, 'medium', 'numbers'),
('three hundred and forty-five', '345', 'word_to_digit', NULL, 'medium', 'numbers'),
('five hundred', '500', 'word_to_digit', NULL, 'easy', 'numbers'),
('nine hundred and ninety-nine', '999', 'word_to_digit', NULL, 'medium', 'numbers'),
('one thousand two hundred and thirty-four', '1,234', 'word_to_digit', NULL, 'hard', 'numbers'),
('twenty-five thousand', '25,000', 'word_to_digit', NULL, 'medium', 'numbers'),
('one hundred thousand', '100,000', 'word_to_digit', NULL, 'medium', 'numbers'),
('three million', '3,000,000', 'word_to_digit', NULL, 'medium', 'numbers'),

-- ORDINAUX (ordinal)
('1st', 'first', 'ordinal', NULL, 'easy', 'numbers'),
('2nd', 'second', 'ordinal', NULL, 'easy', 'numbers'),
('3rd', 'third', 'ordinal', NULL, 'easy', 'numbers'),
('4th', 'fourth', 'ordinal', NULL, 'easy', 'numbers'),
('5th', 'fifth', 'ordinal', 'Attention orthographe', 'easy', 'numbers'),
('6th', 'sixth', 'ordinal', NULL, 'easy', 'numbers'),
('7th', 'seventh', 'ordinal', NULL, 'easy', 'numbers'),
('8th', 'eighth', 'ordinal', NULL, 'easy', 'numbers'),
('9th', 'ninth', 'ordinal', 'Attention orthographe', 'easy', 'numbers'),
('10th', 'tenth', 'ordinal', NULL, 'easy', 'numbers'),
('11th', 'eleventh', 'ordinal', NULL, 'easy', 'numbers'),
('12th', 'twelfth', 'ordinal', 'Attention orthographe', 'easy', 'numbers'),
('13th', 'thirteenth', 'ordinal', NULL, 'easy', 'numbers'),
('14th', 'fourteenth', 'ordinal', NULL, 'easy', 'numbers'),
('15th', 'fifteenth', 'ordinal', NULL, 'easy', 'numbers'),
('20th', 'twentieth', 'ordinal', NULL, 'easy', 'numbers'),
('21st', 'twenty-first', 'ordinal', NULL, 'medium', 'numbers'),
('22nd', 'twenty-second', 'ordinal', NULL, 'medium', 'numbers'),
('23rd', 'twenty-third', 'ordinal', NULL, 'medium', 'numbers'),
('30th', 'thirtieth', 'ordinal', NULL, 'easy', 'numbers'),
('100th', 'hundredth', 'ordinal', NULL, 'medium', 'numbers'),
('1,000th', 'thousandth', 'ordinal', NULL, 'medium', 'numbers'),
('1,000,000th', 'millionth', 'ordinal', NULL, 'hard', 'numbers'),

-- L''HEURE (time)
('3:00', 'three o''clock', 'time', 'Heure pile', 'easy', 'time'),
('3:05', 'five past three', 'time', 'past = après', 'easy', 'time'),
('3:10', 'ten past three', 'time', NULL, 'easy', 'time'),
('3:15', 'quarter past three', 'time', NULL, 'easy', 'time'),
('3:20', 'twenty past three', 'time', NULL, 'easy', 'time'),
('3:30', 'half past three', 'time', 'half = demi', 'easy', 'time'),
('3:40', 'twenty to four', 'time', 'to = avant', 'easy', 'time'),
('3:45', 'quarter to four', 'time', NULL, 'easy', 'time'),
('3:50', 'ten to four', 'time', NULL, 'easy', 'time'),
('3:55', 'five to four', 'time', NULL, 'easy', 'time'),
('12:00', 'midday / noon', 'time', 'Midi', 'easy', 'time'),
('00:00', 'midnight', 'time', 'Minuit', 'easy', 'time'),
('7:30 AM', 'half past seven in the morning', 'time', NULL, 'medium', 'time'),
('7:30 PM', 'half past seven in the evening', 'time', NULL, 'medium', 'time'),
('14:00', 'two o''clock in the afternoon', 'time', 'Format 24h', 'medium', 'time'),
('18:45', 'quarter to seven in the evening', 'time', 'Format 24h', 'medium', 'time'),
('9:15', 'a quarter past nine', 'time', 'a quarter = un quart', 'medium', 'time'),
('10:30', 'half past ten / ten thirty', 'time', 'Deux façons', 'easy', 'time'),
('11:45', 'quarter to twelve / eleven forty-five', 'time', 'Deux façons', 'easy', 'time'),
('1:20', 'twenty past one', 'time', NULL, 'easy', 'time'),
('4:40', 'twenty to five', 'time', NULL, 'easy', 'time'),
('6:50', 'ten to seven', 'time', NULL, 'easy', 'time'),
('8:05', 'five past eight', 'time', NULL, 'easy', 'time'),
('5:25', 'twenty-five past five', 'time', NULL, 'medium', 'time'),
('2:35', 'twenty-five to three', 'time', NULL, 'medium', 'time'),

-- DATES (date)
('01/01', 'the first of January', 'date', '1er janvier', 'easy', 'date'),
('14/02', 'the fourteenth of February', 'date', 'Saint-Valentin', 'easy', 'date'),
('17/03', 'the seventeenth of March', 'date', 'Saint Patrick', 'medium', 'date'),
('01/04', 'the first of April', 'date', 'Poisson d''avril', 'easy', 'date'),
('01/05', 'the first of May', 'date', 'Fête du travail', 'easy', 'date'),
('14/07', 'the fourteenth of July', 'date', 'Fête nationale française', 'easy', 'date'),
('31/10', 'the thirty-first of October', 'date', 'Halloween', 'medium', 'date'),
('11/11', 'the eleventh of November', 'date', 'Armistice', 'easy', 'date'),
('25/12', 'the twenty-fifth of December', 'date', 'Noël', 'easy', 'date'),
('31/12', 'the thirty-first of December', 'date', 'Saint-Sylvestre', 'medium', 'date'),
('1990', 'nineteen ninety', 'date', 'Année', 'easy', 'date'),
('2000', 'two thousand', 'date', 'An 2000', 'easy', 'date'),
('2005', 'two thousand and five', 'date', NULL, 'medium', 'date'),
('2010', 'twenty ten', 'date', 'Deux façons', 'easy', 'date'),
('2024', 'twenty twenty-four', 'date', NULL, 'easy', 'date'),
('2050', 'twenty fifty', 'date', NULL, 'easy', 'date'),
('1800', 'eighteen hundred', 'date', NULL, 'medium', 'date'),
('1905', 'nineteen oh five', 'date', NULL, 'hard', 'date'),
('1066', 'ten sixty-six', 'date', 'Bataille d''Hastings', 'hard', 'date'),

-- FRACTIONS (fraction)
('1/2', 'a half / one half', 'fraction', NULL, 'easy', 'numbers'),
('1/3', 'a third / one third', 'fraction', NULL, 'easy', 'numbers'),
('1/4', 'a quarter / one quarter / a fourth', 'fraction', 'Deux façons courantes', 'easy', 'numbers'),
('2/3', 'two thirds', 'fraction', 'thirDS (pluriel)', 'easy', 'numbers'),
('3/4', 'three quarters', 'fraction', NULL, 'easy', 'numbers'),
('1/5', 'a fifth / one fifth', 'fraction', NULL, 'medium', 'numbers'),
('2/5', 'two fifths', 'fraction', 'fifTHS (pluriel)', 'medium', 'numbers'),
('1/8', 'an eighth', 'fraction', NULL, 'medium', 'numbers'),
('3/8', 'three eighths', 'fraction', NULL, 'medium', 'numbers'),
('5/6', 'five sixths', 'fraction', NULL, 'medium', 'numbers'),
('7/10', 'seven tenths', 'fraction', NULL, 'easy', 'numbers'),

-- POURCENTAGES (percentage)
('10%', 'ten percent', 'percentage', NULL, 'easy', 'numbers'),
('25%', 'twenty-five percent / a quarter', 'percentage', 'Deux façons', 'easy', 'numbers'),
('50%', 'fifty percent / a half', 'percentage', 'Deux façons', 'easy', 'numbers'),
('75%', 'seventy-five percent / three quarters', 'percentage', 'Deux façons', 'easy', 'numbers'),
('100%', 'a hundred percent', 'percentage', NULL, 'easy', 'numbers'),
('33%', 'thirty-three percent / a third', 'percentage', 'Deux façons', 'easy', 'numbers'),
('0%', 'zero percent', 'percentage', NULL, 'easy', 'numbers'),
('99%', 'ninety-nine percent', 'percentage', NULL, 'easy', 'numbers'),
('12.5%', 'twelve point five percent', 'percentage', NULL, 'medium', 'numbers'),
('150%', 'a hundred and fifty percent', 'percentage', NULL, 'medium', 'numbers'),

-- DÉCIMAUX (decimal)
('0.5', 'zero point five / nought point five', 'decimal', 'Deux façons', 'easy', 'numbers'),
('1.25', 'one point two five', 'decimal', NULL, 'easy', 'numbers'),
('3.14', 'three point one four', 'decimal', 'Pi', 'easy', 'numbers'),
('2.718', 'two point seven one eight', 'decimal', NULL, 'medium', 'numbers'),
('99.99', 'ninety-nine point ninety-nine', 'decimal', NULL, 'medium', 'numbers'),
('0.01', 'zero point zero one / nought point oh one', 'decimal', NULL, 'medium', 'numbers'),
('10.5', 'ten point five', 'decimal', NULL, 'easy', 'numbers'),
('100.25', 'a hundred point two five', 'decimal', NULL, 'medium', 'numbers'),
('1,000.50', 'one thousand point five', 'decimal', NULL, 'medium', 'numbers'),

-- MÉLANGE (mixed - les plus difficiles)
('2nd place in a race', 'second', 'mixed', 'Ordinaux en contexte', 'easy', 'numbers'),
('3rd floor', 'third', 'mixed', 'Ordinaux en contexte', 'easy', 'numbers'),
('21st century', 'twenty-first', 'mixed', 'Siècle', 'medium', 'numbers'),
('20th century', 'twentieth', 'mixed', 'Siècle', 'medium', 'numbers'),
('1st of May', 'first', 'mixed', 'Date', 'easy', 'numbers'),
('Room 405', 'four oh five', 'mixed', 'Numéro de chambre', 'medium', 'numbers'),
('Bus 22', 'twenty-two', 'mixed', 'Numéro de bus', 'easy', 'numbers'),
('Flight BA 1066', 'ten sixty-six', 'mixed', 'Numéro de vol', 'hard', 'numbers'),
('Page 257', 'two fifty-seven / two five seven', 'mixed', 'Numéro de page', 'medium', 'numbers'),
('Tel: 555-0199', 'five five five, oh one nine nine', 'mixed', 'Téléphone', 'hard', 'numbers'),
('2.5 million people', 'two point five million', 'mixed', 'Nombre + contexte', 'medium', 'numbers'),
('a dozen', 'twelve', 'mixed', 'Douzaine', 'easy', 'numbers'),
('a score', 'twenty', 'mixed', 'Vingtaine (littéraire)', 'hard', 'numbers'),
('a gross', 'one hundred and forty-four', 'mixed', 'Grosse = 144', 'hard', 'numbers'),
('once', 'one time', 'mixed', 'Fréquence', 'easy', 'numbers'),
('twice', 'two times', 'mixed', 'Fréquence', 'easy', 'numbers'),
('three times', 'three times', 'mixed', 'Fréquence', 'easy', 'numbers'),
('half a dozen', 'six', 'mixed', 'Demi-douzaine', 'medium', 'numbers'),
('two dozen', 'twenty-four', 'mixed', 'Deux douzaines', 'medium', 'numbers'),
('a couple of', 'two / a few', 'mixed', 'Un couple de...', 'easy', 'numbers'),
('£5.99', 'five pounds ninety-nine', 'mixed', 'Prix', 'medium', 'numbers'),
('$20.50', 'twenty dollars fifty', 'mixed', 'Prix', 'medium', 'numbers'),
('€1,200', 'one thousand two hundred euros', 'mixed', 'Prix', 'medium', 'numbers'),
('3:30 PM = ?', 'half past three in the afternoon / three thirty PM', 'mixed', 'Format 12h/24h', 'medium', 'time'),
('0 degrees', 'zero degrees', 'mixed', 'Température', 'easy', 'numbers'),
('minus 10 degrees', 'minus ten degrees / ten below zero', 'mixed', 'Température négative', 'medium', 'numbers'),
('1st, 2nd, 3rd...', 'first, second, third...', 'mixed', 'Série d''ordinaux', 'easy', 'numbers'),
('every 2 weeks', 'every two weeks / fortnightly', 'mixed', 'Fréquence', 'medium', 'numbers'),
('twice a month', 'twice a month', 'mixed', 'Fréquence', 'easy', 'numbers'),
('three times a year', 'three times a year', 'mixed', 'Fréquence', 'easy', 'numbers'),
('every 4 years', 'every four years', 'mixed', 'Fréquence', 'easy', 'numbers'),
('2 out of 10', 'two out of ten', 'mixed', 'Proportion', 'easy', 'numbers'),
('9 out of 10 people', 'nine out of ten people', 'mixed', 'Proportion', 'easy', 'numbers'),
('1 in 3', 'one in three', 'mixed', 'Proportion', 'easy', 'numbers'),
('50/50 chance', 'a fifty-fifty chance', 'mixed', 'Expression', 'easy', 'numbers'),
('100% sure', 'a hundred percent sure', 'mixed', 'Expression', 'easy', 'numbers'),
('at the eleventh hour', 'at the last minute', 'mixed', 'Expression avec ordinal', 'hard', 'numbers'),
('second to none', 'the best', 'mixed', 'Expression', 'hard', 'numbers'),
('on cloud nine', 'very happy', 'mixed', 'Expression avec chiffre', 'hard', 'numbers');
