-- ============================================================
-- GRAMMAIRE v12 — Ajout traductions leçons 1-5
-- ============================================================

UPDATE grammar_lessons SET content = '<h3>Formation</h3><p>Base verbale (+ <i>-s</i> à la 3e personne du singulier).</p><h3>Usage</h3><ul><li>Habitudes : <i>I drink coffee every morning.</i> <span style="color:#94a3b8">— Je bois du café tous les matins.</span></li><li>Vérités générales : <i>The sun rises in the east.</i> <span style="color:#94a3b8">— Le soleil se lève à l''est.</span></li><li>Programmes fixes : <i>The train leaves at 8 PM.</i> <span style="color:#94a3b8">— Le train part à 20h.</span></li></ul><h3>Signal words</h3><p>always, usually, often, sometimes, never, every day</p>' WHERE id = 1;

UPDATE grammar_lessons SET content = '<h3>Règles</h3><ul><li>général : +<i>s</i> → <i>work → works</i> <span style="color:#94a3b8">— travailler → travaille</span></li><li>-ch, -sh, -ss, -x, -o, -z : +<i>es</i> → <i>watch → watches</i> <span style="color:#94a3b8">— regarder → regarde</span></li><li>consonne + y : <i>-y → ies</i> → <i>study → studies</i> <span style="color:#94a3b8">— étudier → étudie</span></li></ul><h3>Exceptions</h3><p><i>have → has</i> <span style="color:#94a3b8">— avoir → a</span> | <i>be → is</i> <span style="color:#94a3b8">— être → est</span></p>' WHERE id = 2;

UPDATE grammar_lessons SET content = '<h3>Formation</h3><p><i>am/is/are</i> + base verbale + <i>-ing</i></p><h3>Usage</h3><ul><li>Action en cours : <i>I am reading right now.</i> <span style="color:#94a3b8">— Je suis en train de lire maintenant.</span></li><li>Changement : <i>The climate is getting warmer.</i> <span style="color:#94a3b8">— Le climat se réchauffe.</span></li><li>Plan proche : <i>I am meeting him tomorrow.</i> <span style="color:#94a3b8">— Je le rencontre demain.</span></li></ul>' WHERE id = 3;

UPDATE grammar_lessons SET content = '<h3>Différences clés</h3><ul><li>Simple = habitudes, vérités permanentes : <i>I work in Paris.</i> <span style="color:#94a3b8">— Je travaille à Paris.</span></li><li>Continu = actions en cours, temporaires : <i>I am working from home this week.</i> <span style="color:#94a3b8">— Je travaille de la maison cette semaine.</span></li></ul><h3>Verbes d''état</h3><p>love, hate, know, want, need, belong → PAS de continu</p><p><i>I love chocolate.</i> <span style="color:#94a3b8">— J''adore le chocolat.</span> (PAS <i>I am loving</i>)</p>' WHERE id = 4;

UPDATE grammar_lessons SET content = '<h3>Formation régulière</h3><p>Base verbale + <i>-ed</i></p><ul><li>général : <i>walk → walked</i> <span style="color:#94a3b8">— marcher → marché</span></li><li>-e : +<i>d</i> → <i>live → lived</i> <span style="color:#94a3b8">— vivre → vécu</span></li><li>consonne + y : <i>-y → ied</i> → <i>try → tried</i> <span style="color:#94a3b8">— essayer → essayé</span></li></ul><h3>Signal words</h3><p>yesterday, last week, ago, in 2010</p><ul><li><i>I watched TV yesterday.</i> <span style="color:#94a3b8">— J''ai regardé la télé hier.</span></li><li><i>She lived here in 2010.</i> <span style="color:#94a3b8">— Elle vivait ici en 2010.</span></li></ul>' WHERE id = 5;
