-- ============================================================
-- GRAMMAIRE v13 — Ajout traductions leçons 6-10
-- ============================================================

UPDATE grammar_lessons SET content = '<h3>Tableau des irréguliers courants</h3><ul><li><i>be → was/were</i> <span style="color:#94a3b8">— être → étais/étions</span></li><li><i>have → had</i> <span style="color:#94a3b8">— avoir → avais</span></li><li><i>do → did</i> <span style="color:#94a3b8">— faire → fis</span></li><li><i>go → went</i> <span style="color:#94a3b8">— aller → allai</span></li><li><i>make → made</i> <span style="color:#94a3b8">— faire/fabriquer → fis</span></li><li><i>take → took</i> <span style="color:#94a3b8">— prendre → pris</span></li><li><i>see → saw</i> <span style="color:#94a3b8">— voir → vis</span></li><li><i>come → came</i> <span style="color:#94a3b8">— venir → vins</span></li><li><i>know → knew</i> <span style="color:#94a3b8">— savoir → sus</span></li><li><i>think → thought</i> <span style="color:#94a3b8">— penser → pensai</span></li></ul><p><i>I went to London last summer.</i> <span style="color:#94a3b8">— Je suis allé à Londres l''été dernier.</span></p>' WHERE id = 6;

UPDATE grammar_lessons SET content = '<h3>Formation</h3><p><i>was/were</i> + base verbale + <i>-ing</i></p><h3>Usage</h3><ul><li>Action interrompue : <i>I was reading when she called.</i> <span style="color:#94a3b8">— Je lisais quand elle a appelé.</span></li><li>Deux actions simultanées : <i>While I was cooking, he was watching TV.</i> <span style="color:#94a3b8">— Pendant que je faisais la cuisine, il regardait la télé.</span></li><li>Contexte d''une histoire : <i>The wind was blowing.</i> <span style="color:#94a3b8">— Le vent soufflait.</span></li></ul>' WHERE id = 7;

UPDATE grammar_lessons SET content = '<h3>Différences</h3><ul><li>Simple = action terminée, ponctuelle : <i>I broke the window.</i> <span style="color:#94a3b8">— J''ai cassé la fenêtre.</span></li><li>Continu = action en cours, plus longue : <i>I was breaking the window when he saw me.</i> <span style="color:#94a3b8">— J''étais en train de casser la fenêtre quand il m''a vu.</span></li></ul><h3>Combiné</h3><p>Continu (action longue) + simple (interruption) : <i>I was walking when it started to rain.</i> <span style="color:#94a3b8">— Je marchais quand il a commencé à pleuvoir.</span></p>' WHERE id = 8;

UPDATE grammar_lessons SET content = '<h3>Formation</h3><p><i>have/has</i> + participe passé</p><h3>Usage</h3><ul><li>Expérience de vie : <i>I have visited Japan.</i> <span style="color:#94a3b8">— J''ai visité le Japon.</span></li><li>Changement récent : <i>She has lost weight.</i> <span style="color:#94a3b8">— Elle a maigri.</span></li><li>Action qui continue : <i>I have lived here for 5 years.</i> <span style="color:#94a3b8">— Je vis ici depuis 5 ans.</span></li></ul><h3>Signal words</h3><p>ever, never, already, yet, just, since, for</p><ul><li><i>Have you ever been to Paris?</i> <span style="color:#94a3b8">— Es-tu déjà allé à Paris ?</span></li><li><i>I have just finished.</i> <span style="color:#94a3b8">— Je viens de finir.</span></li></ul>' WHERE id = 9;

UPDATE grammar_lessons SET content = '<h3>Since</h3><p>Indique le <b>début</b> d''une période : <i>since 2010, since Monday</i> <span style="color:#94a3b8">— depuis 2010, depuis lundi</span></p><h3>For</h3><p>Indique une <b>durée</b> : <i>for two hours, for 5 years</i> <span style="color:#94a3b8">— pendant deux heures, depuis 5 ans</span></p><h3>Exemples</h3><ul><li><i>I have known her since 2015.</i> <span style="color:#94a3b8">— Je la connais depuis 2015.</span></li><li><i>I have known her for 8 years.</i> <span style="color:#94a3b8">— Je la connais depuis 8 ans.</span></li></ul>' WHERE id = 10;
