-- ============================================================
-- GRAMMAIRE v14 — Ajout traductions leçons 11-15
-- ============================================================

UPDATE grammar_lessons SET content = '<h3>Formation</h3><p><i>have/has been</i> + base verbale + <i>-ing</i></p><h3>Usage</h3><ul><li>Action commencée dans le passé qui continue : <i>I have been studying for 3 hours.</i> <span style="color:#94a3b8">— J''étudie depuis 3 heures.</span></li><li>Action récente avec résultat visible : <i>Why are you wet? I have been walking in the rain.</i> <span style="color:#94a3b8">— Pourquoi es-tu mou ? J''ai marché sous la pluie.</span></li></ul><h3>Simple vs Continu</h3><p>Simple = résultat ; Continu = processus</p><ul><li><i>I have read the book.</i> <span style="color:#94a3b8">— J''ai lu le livre. (fini)</span></li><li><i>I have been reading the book.</i> <span style="color:#94a3b8">— Je suis en train de lire le livre. (en cours)</span></li></ul>' WHERE id = 11;

UPDATE grammar_lessons SET content = '<h3>Formation</h3><p><i>had</i> + participe passé</p><h3>Usage</h3><ul><li>Action antérieure dans le passé : <i>When I arrived, the train had already left.</i> <span style="color:#94a3b8">— Quand je suis arrivé, le train était déjà parti.</span></li><li>Avec <i>before, after, when</i></li></ul><p><i>She had never seen a ghost before that night.</i> <span style="color:#94a3b8">— Elle n''avait jamais vu de fantôme avant cette nuit.</span></p>' WHERE id = 12;

UPDATE grammar_lessons SET content = '<h3>Will</h3><ul><li>Décision spontanée : <i>I will help you.</i> <span style="color:#94a3b8">— Je vais t''aider.</span></li><li>Prédiction (opinion) : <i>I think it will rain tomorrow.</i> <span style="color:#94a3b8">— Je pense qu''il pleuvra demain.</span></li><li>Promesse : <i>I will call you tonight.</i> <span style="color:#94a3b8">— Je t''appellerai ce soir.</span></li></ul><h3>Be going to</h3><ul><li>Plan/intention : <i>I am going to buy a car.</i> <span style="color:#94a3b8">— Je vais acheter une voiture.</span></li><li>Prédiction (signes évidents) : <i>Look at those clouds! It is going to rain.</i> <span style="color:#94a3b8">— Regarde ces nuages ! Il va pleuvoir.</span></li></ul>' WHERE id = 13;

UPDATE grammar_lessons SET content = '<h3>Futur continu</h3><p><i>will be</i> + <i>-ing</i> : <i>This time tomorrow, I will be flying to Paris.</i> <span style="color:#94a3b8">— À cette heure demain, je serai en train de voler vers Paris.</span></p><h3>Futur perfect</h3><p><i>will have</i> + participe passé : <i>By 2026, I will have finished my studies.</i> <span style="color:#94a3b8">— D''ici 2026, j''aurai terminé mes études.</span></p><h3>Signal words</h3><p>by, by the time, this time tomorrow</p>' WHERE id = 14;

UPDATE grammar_lessons SET content = '<h3>Tableau récapitulatif</h3><ul><li>Prétérit simple : action terminée → <i>I saw a film.</i> <span style="color:#94a3b8">— J''ai vu un film.</span></li><li>Prétérit continu : action en cours → <i>I was watching TV.</i> <span style="color:#94a3b8">— Je regardais la télé.</span></li><li>Present perfect : lien passé-présent → <i>I have seen it twice.</i> <span style="color:#94a3b8">— Je l''ai vu deux fois.</span></li><li>Past perfect : antériorité → <i>I had left before he came.</i> <span style="color:#94a3b8">— J''étais parti avant qu''il arrive.</span></li></ul>' WHERE id = 15;
