-- ============================================================
-- GRAMMAIRE v15 — Ajout traductions leçons 16-23 (modaux)
-- ============================================================

UPDATE grammar_lessons SET content = '<h3>Can</h3><ul><li>Capacité : <i>I can swim.</i> <span style="color:#94a3b8">— Je sais nager.</span></li><li>Possibilité : <i>It can get cold at night.</i> <span style="color:#94a3b8">— Il peut faire froid la nuit.</span></li><li>Permission : <i>Can I use your phone?</i> <span style="color:#94a3b8">— Puis-je utiliser ton téléphone ?</span></li></ul><h3>Could</h3><ul><li>Passé de can : <i>I could run faster when I was young.</i> <span style="color:#94a3b8">— Je pouvais courir plus vite quand j''étais jeune.</span></li><li>Possibilité hypothétique : <i>It could rain tomorrow.</i> <span style="color:#94a3b8">— Il pourrait pleuvoir demain.</span></li><li>Demande polie : <i>Could you help me?</i> <span style="color:#94a3b8">— Pourrais-tu m''aider ?</span></li></ul>' WHERE id = 16;

UPDATE grammar_lessons SET content = '<h3>Can</h3><p>Capacité générale, présent : <i>I can speak French.</i> <span style="color:#94a3b8">— Je peux parler français.</span></p><h3>Could</h3><p>Capacité passée générale : <i>I could swim when I was five.</i> <span style="color:#94a3b8">— Je savais nager quand j''avais cinq ans.</span></p><h3>Be able to / Manage to</h3><p>Réussite dans une situation particulière : <i>Everyone was able to escape.</i> <span style="color:#94a3b8">— Tout le monde a réussi à s''échapper.</span></p>' WHERE id = 17;

UPDATE grammar_lessons SET content = '<h3>Must</h3><ul><li>Obligation subjective : <i>I must study.</i> <span style="color:#94a3b8">— Je dois étudier. (je me l''impose)</span></li><li>Déduction logique : <i>He must be tired.</i> <span style="color:#94a3b8">— Il doit être fatigué.</span></li></ul><h3>Have to</h3><ul><li>Obligation externe : <i>I have to wear a uniform.</i> <span style="color:#94a3b8">— Je dois porter un uniforme. (c''est le règlement)</span></li></ul>' WHERE id = 18;

UPDATE grammar_lessons SET content = '<h3>Mustn''t</h3><p><b>Interdiction</b> : <i>You mustn''t smoke here.</i> <span style="color:#94a3b8">— Tu ne dois pas fumer ici. (interdit)</span></p><h3>Don''t have to / Needn''t</h3><p><b>Absence d''obligation</b> : <i>You don''t have to come if you''re busy.</i> <span style="color:#94a3b8">— Tu n''es pas obligé de venir si tu es occupé.</span></p>' WHERE id = 19;

UPDATE grammar_lessons SET content = '<h3>Should</h3><ul><li>Conseil : <i>You should eat more vegetables.</i> <span style="color:#94a3b8">— Tu devrais manger plus de légumes.</span></li><li>Attente : <i>The train should arrive at 6 PM.</i> <span style="color:#94a3b8">— Le train devrait arriver à 18h.</span></li><li>Regret : <i>I should have studied harder.</i> <span style="color:#94a3b8">— J''aurais dû étudier plus dur.</span></li></ul><h3>Ought to</h3><p>Même sens que should, plus formel : <i>You ought to apologize.</i> <span style="color:#94a3b8">— Tu devrais t''excuser.</span></p>' WHERE id = 20;

UPDATE grammar_lessons SET content = '<h3>Permission</h3><ul><li><i>May I come in?</i> <span style="color:#94a3b8">— Puis-je entrer ? (très formel)</span></li><li><i>Can I come in?</i> <span style="color:#94a3b8">— Je peux entrer ? (courant)</span></li></ul><h3>Possibilité</h3><ul><li><i>It may rain tomorrow.</i> <span style="color:#94a3b8">— Il pleuvra peut-être demain. (50%)</span></li><li><i>It might rain tomorrow.</i> <span style="color:#94a3b8">— Il pleuvrait peut-être demain. (moins probable)</span></li></ul><h3>Interdiction</h3><p><i>You may not enter.</i> <span style="color:#94a3b8">— Vous ne pouvez pas entrer. (formel)</span></p>' WHERE id = 21;

UPDATE grammar_lessons SET content = '<h3>Will</h3><p>Futur standard : <i>I will see you tomorrow.</i> <span style="color:#94a3b8">— Je te verrai demain.</span></p><h3>Shall</h3><ul><li>Suggestions avec <i>I</i> et <i>we</i> : <i>Shall we go?</i> <span style="color:#94a3b8">— On y va ?</span></li><li>Offres : <i>Shall I help you?</i> <span style="color:#94a3b8">— Puis-je vous aider ?</span></li><li>Promesses solennelles : <i>I shall return.</i> <span style="color:#94a3b8">— Je reviendrai.</span></li></ul><p>Shall est plus rare aujourd''hui, surtout britannique.</p>' WHERE id = 22;

UPDATE grammar_lessons SET content = '<h3>Need</h3><p>Modal (surtout négatif) : <i>You needn''t worry.</i> <span style="color:#94a3b8">— Tu n''as pas besoin de t''inquiéter.</span> (= don''t need to)</p><p>Verbe ordinaire : <i>You don''t need to come.</i> <span style="color:#94a3b8">— Tu n''as pas besoin de venir.</span></p><h3>Dare</h3><p>Modal : <i>Dare he contradict her?</i> <span style="color:#94a3b8">— Oserait-il la contredire ?</span></p><p>Verbe ordinaire : <i>He doesn''t dare to speak.</i> <span style="color:#94a3b8">— Il n''ose pas parler.</span></p>' WHERE id = 23;
