-- ============================================================
-- GRAMMAIRE v16 — Ajout traductions leçons 24-35
-- ============================================================

UPDATE grammar_lessons SET content = '<h3>Ordre de fréquence</h3><p>always (100%) → usually (80%) → often (60%) → sometimes (40%) → rarely (10%) → never (0%)</p><h3>Position</h3><ul><li>Avant le verbe principal : <i>I always eat breakfast.</i> <span style="color:#94a3b8">— Je prends toujours le petit-déjeuner.</span></li><li>Après BE : <i>She is always late.</i> <span style="color:#94a3b8">— Elle est toujours en retard.</span></li><li>Après auxiliaire/modal : <i>I have never seen it.</i> <span style="color:#94a3b8">— Je ne l''ai jamais vu.</span></li></ul><h3>Exceptions</h3><p><i>Sometimes</i> peut être en début : <i>Sometimes I go to the cinema.</i> <span style="color:#94a3b8">— Parfois je vais au cinéma.</span></p>' WHERE id = 24;

UPDATE grammar_lessons SET content = '<h3>Formation</h3><p>Adjectif + <i>-ly</i> : <i>quick → quickly, careful → carefully</i></p><h3>Exceptions</h3><ul><li>good → well</li><li>fast → fast</li><li>hard → hard</li></ul><h3>Position</h3><p>Généralement après l''objet : <i>She sings beautifully.</i> <span style="color:#94a3b8">— Elle chante magnifiquement.</span></p>' WHERE id = 25;

UPDATE grammar_lessons SET content = '<h3>Adverbes de lieu</h3><p>here, there, everywhere, nowhere, upstairs, downstairs, abroad</p><p><i>Come here!</i> <span style="color:#94a3b8">— Viens ici !</span> | <i>She lives abroad.</i> <span style="color:#94a3b8">— Elle vit à l''étranger.</span></p><h3>Adverbes de temps</h3><p>now, then, today, tomorrow, yesterday, soon, later, already, yet, still</p><p><i>I will call you soon.</i> <span style="color:#94a3b8">— Je t''appellerai bientôt.</span> | <i>I have already eaten.</i> <span style="color:#94a3b8">— J''ai déjà mangé.</span></p><h3>Position</h3><p>En général en fin de phrase ou en début pour l''emphase.</p>' WHERE id = 26;

UPDATE grammar_lessons SET content = '<h3>Very / Quite / Rather / Fairly</h3><p>Intensifient l''adjectif : <i>very good</i> <span style="color:#94a3b8">— très bon</span>, <i>quite interesting</i> <span style="color:#94a3b8">— assez intéressant</span>, <i>rather difficult</i> <span style="color:#94a3b8">— plutôt difficile</span>, <i>fairly easy</i> <span style="color:#94a3b8">— assez facile</span></p><h3>Too + adjectif</h3><p>Trop (négatif) : <i>It is too hot.</i> <span style="color:#94a3b8">— Il fait trop chaud. (On ne peut pas sortir)</span></p><h3>Adjectif + enough</h3><p>Assez (positif) : <i>It is warm enough.</i> <span style="color:#94a3b8">— Il fait assez chaud. (On peut sortir)</span></p>' WHERE id = 27;

UPDATE grammar_lessons SET content = '<h3>Still</h3><p>Encore (action qui continue) : <i>Are you still here?</i> <span style="color:#94a3b8">— Tu es encore là ?</span></p><h3>Yet</h3><p>Déjà/pas encore (en fin de phrase, négatif/interrogatif) : <i>Have you finished yet?</i> <span style="color:#94a3b8">— As-tu déjà fini ?</span> / <i>I haven''t finished yet.</i> <span style="color:#94a3b8">— Je n''ai pas encore fini.</span></p><h3>Already</h3><p>Déjà (plus tôt que prévu) : <i>I have already eaten.</i> <span style="color:#94a3b8">— J''ai déjà mangé.</span></p>' WHERE id = 28;

UPDATE grammar_lessons SET content = '<h3>Formation</h3><p>Adverbes courts : <i>fast → faster → fastest</i> <span style="color:#94a3b8">— vite → plus vite → le plus vite</span></p><p>Adverbes en -ly : <i>quickly → more quickly → most quickly</i> <span style="color:#94a3b8">— rapidement → plus rapidement → le plus rapidement</span></p><h3>Exceptions</h3><p><i>well → better → best, badly → worse → worst, far → further → furthest</i></p>' WHERE id = 29;

UPDATE grammar_lessons SET content = '<h3>Hard</h3><p>Dur, avec effort : <i>She works hard.</i> <span style="color:#94a3b8">— Elle travaille dur.</span></p><h3>Hardly</h3><p>Presque pas : <i>I hardly know him.</i> <span style="color:#94a3b8">— Je le connais à peine.</span></p><h3>Attention</h3><p><i>Hardly</i> = presque jamais/presque pas. C''est un adverbe de fréquence/négation, pas un adverbe de manière.</p>' WHERE id = 30;

UPDATE grammar_lessons SET content = '<h3>Règles générales</h3><ul><li>Fréquence : avant le verbe principal, après BE/auxiliaire</li><li>Manière : après l''objet</li><li>Lieu : avant le temps (PLACE avant TIME)</li><li>Temps : en fin de phrase</li></ul><h3>Ordre</h3><p><i>MANNER + PLACE + TIME</i> : <i>She sang beautifully at the concert last night.</i> <span style="color:#94a3b8">— Elle a chanté magnifiquement au concert hier soir.</span></p>' WHERE id = 31;

UPDATE grammar_lessons SET content = '<h3>In</h3><p>Espace fermé, grand : <i>in the room, in Paris, in France</i> <span style="color:#94a3b8">— dans la pièce, à Paris, en France</span></p><h3>On</h3><p>Surface, ligne : <i>on the table, on the wall, on the street</i> <span style="color:#94a3b8">— sur la table, sur le mur, dans la rue</span></p><h3>At</h3><p>Point précis : <i>at the door, at the station, at home</i> <span style="color:#94a3b8">— à la porte, à la gare, à la maison</span></p><h3>Exceptions</h3><p><i>on the bus, on the plane, on the train</i> <span style="color:#94a3b8">— dans le bus, dans l''avion, dans le train</span> (moyens de transport)</p>' WHERE id = 32;

UPDATE grammar_lessons SET content = '<h3>Above / Over</h3><p>Au-dessus : <i>above the line, over the bridge</i> <span style="color:#94a3b8">— au-dessus de la ligne, au-dessus du pont</span></p><h3>Below / Under / Beneath</h3><p>Au-dessous : <i>below zero, under the table</i> <span style="color:#94a3b8">— en dessous de zéro, sous la table</span></p><h3>Between / Among</h3><p>Between = 2 éléments. Among = 3+ éléments : <i>between you and me, among the crowd</i> <span style="color:#94a3b8">— entre toi et moi, parmi la foule</span></p>' WHERE id = 33;

UPDATE grammar_lessons SET content = '<h3>In</h3><p>Périodes longues : <i>in 2024, in July, in the morning</i> <span style="color:#94a3b8">— en 2024, en juillet, le matin</span></p><h3>On</h3><p>Jours et dates : <i>on Monday, on Christmas Day, on June 1st</i> <span style="color:#94a3b8">— lundi, le jour de Noël, le 1er juin</span></p><h3>At</h3><p>Moments précis : <i>at 5 o''clock, at noon, at night, at the weekend (UK)</i> <span style="color:#94a3b8">— à 5 heures, à midi, la nuit, le week-end</span></p>' WHERE id = 34;

UPDATE grammar_lessons SET content = '<h3>For</h3><p>Durée : <i>for two hours, for a long time</i> <span style="color:#94a3b8">— pendant deux heures, depuis longtemps</span></p><h3>Since</h3><p>Point de départ : <i>since Monday, since 2010</i> <span style="color:#94a3b8">— depuis lundi, depuis 2010</span></p><h3>During</h3><p>Pendant (préposition) : <i>during the meeting, during the summer</i> <span style="color:#94a3b8">— pendant la réunion, pendant l''été</span></p><h3>While</h3><p>Pendant que (conjonction + sujet + verbe) : <i>while I was eating</i> <span style="color:#94a3b8">— pendant que je mangeais</span></p>' WHERE id = 35;
