-- ============================================================
-- GRAMMAIRE v17 — Ajout traductions leçons 36-50
-- ============================================================

UPDATE grammar_lessons SET content = '<h3>To</h3><p>Direction générale : <i>go to school, from Paris to London</i> <span style="color:#94a3b8">— aller à l''école, de Paris à Londres</span></p><h3>Into</h3><p>Entrer dans (intérieur) : <i>walk into the room, pour water into the glass</i> <span style="color:#94a3b8">— entrer dans la pièce, verser de l''eau dans le verre</span></p><h3>Onto</h3><p>Monter sur (surface) : <i>jump onto the table, put the book onto the shelf</i> <span style="color:#94a3b8">— sauter sur la table, mettre le livre sur l''étagère</span></p>' WHERE id = 36;

UPDATE grammar_lessons SET content = '<h3>By</h3><p>Moyen/transport/agent : <i>by car, by hand, written by Shakespeare</i> <span style="color:#94a3b8">— en voiture, à la main, écrit par Shakespeare</span></p><h3>With</h3><p>Instrument/accompagnement : <i>cut with a knife, with my brother</i> <span style="color:#94a3b8">— couper avec un couteau, avec mon frère</span></p><h3>Without</h3><p>Absence : <i>without money, without saying goodbye</i> <span style="color:#94a3b8">— sans argent, sans dire au revoir</span></p>' WHERE id = 37;

UPDATE grammar_lessons SET content = '<h3>Across</h3><p>D''un côté à l''autre (surface) : <i>walk across the street</i> <span style="color:#94a3b8">— traverser la rue</span></p><h3>Through</h3><p>À travers (intérieur) : <i>drive through the tunnel</i> <span style="color:#94a3b8">— conduire à travers le tunnel</span></p><h3>Past</h3><p>Passer devant : <i>walk past the shop</i> <span style="color:#94a3b8">— passer devant le magasin</span></p><h3>Along</h3><p>Le long de : <i>walk along the river</i> <span style="color:#94a3b8">— marcher le long de la rivière</span></p>' WHERE id = 38;

UPDATE grammar_lessons SET content = '<h3>Les 7 conjonctions de coordination</h3><p><b>FANBOYS</b> : <b>F</b>or, <b>A</b>nd, <b>N</b>or, <b>B</b>ut, <b>O</b>r, <b>Y</b>et, <b>S</b>o</p><h3>Usage</h3><ul><li>Relier deux propositions indépendantes</li><li>Virgule avant la conjonction (sauf phrases courtes)</li></ul><h3>Exemples</h3><p><i>I wanted to go, but I was too tired.</i> <span style="color:#94a3b8">— Je voulais y aller, mais j''étais trop fatigué.</span></p><p><i>She was ill, so she stayed home.</i> <span style="color:#94a3b8">— Elle était malade, donc elle est restée chez elle.</span></p>' WHERE id = 39;

UPDATE grammar_lessons SET content = '<h3>Because</h3><p>Cause (motivation) : <i>I stayed because it was raining.</i> <span style="color:#94a3b8">— Je suis resté parce qu''il pleuvait.</span></p><h3>Since / As</h3><p>Cause connue, moins emphatique : <i>Since you are here, let''s start.</i> <span style="color:#94a3b8">— Puisque tu es là, commençons.</span></p><h3>Différences</h3><p><i>Because</i> = cause directe et nouvelle. <i>Since/As</i> = cause évidente ou déjà connue.</p>' WHERE id = 40;

UPDATE grammar_lessons SET content = '<h3>If</h3><p>Si : <i>If it rains, I will stay home.</i> <span style="color:#94a3b8">— S''il pleut, je resterai chez moi.</span></p><h3>Unless</h3><p>À moins que (= if not) : <i>Unless you study, you will fail.</i> <span style="color:#94a3b8">— À moins que tu étudies, tu échoueras.</span></p><h3>As long as / Provided that</h3><p>À condition que : <i>You can go as long as you finish your homework.</i> <span style="color:#94a3b8">— Tu peux y aller à condition que tu finisses tes devoirs.</span></p>' WHERE id = 41;

UPDATE grammar_lessons SET content = '<h3>When / While</h3><p>When = quand (ponctuel). While = pendant que (durée) : <i>When I arrived, she was cooking.</i> <span style="color:#94a3b8">— Quand je suis arrivé, elle faisait la cuisine.</span> / <i>While I was eating, he called.</i> <span style="color:#94a3b8">— Pendant que je mangeais, il a appelé.</span></p><h3>Before / After</h3><p><i>Before she left, she said goodbye.</i> <span style="color:#94a3b8">— Avant de partir, elle a dit au revoir.</span> / <i>After he finished, he went home.</i> <span style="color:#94a3b8">— Après avoir fini, il est rentré chez lui.</span></p><h3>Until / As soon as</h3><p><i>Wait until I come back.</i> <span style="color:#94a3b8">— Attends jusqu''à ce que je revienne.</span> / <i>Call me as soon as you arrive.</i> <span style="color:#94a3b8">— Appelle-moi dès que tu arrives.</span></p>' WHERE id = 42;

UPDATE grammar_lessons SET content = '<h3>Although / Though / Even though</h3><p>Bien que (concession) : <i>Although it was raining, we went out.</i> <span style="color:#94a3b8">— Bien qu''il pleuve, nous sommes sortis.</span></p><h3>Whereas / While</h3><p>Alors que (contraste) : <i>Whereas he is rich, his brother is poor.</i> <span style="color:#94a3b8">— Alors qu''il est riche, son frère est pauvre.</span></p><h3>Attention</h3><p>Pas de <i>but</i> après <i>although</i> ! <i>Although it was cold, we went out.</i> <span style="color:#94a3b8">— Bien qu''il fasse froid, nous sommes sortis.</span></p>' WHERE id = 43;

UPDATE grammar_lessons SET content = '<h3>Both...and</h3><p>Les deux : <i>Both John and Mary are coming.</i> <span style="color:#94a3b8">— Tant John que Mary viennent.</span></p><h3>Either...or</h3><p>L''un ou l''autre : <i>You can either stay or leave.</i> <span style="color:#94a3b8">— Tu peux soit rester soit partir.</span></p><h3>Neither...nor</h3><p>Ni l''un ni l''autre : <i>Neither John nor Mary is coming.</i> <span style="color:#94a3b8">— Ni John ni Mary ne vient.</span></p><h3>Not only...but also</h3><p>Pas seulement...mais aussi : <i>She is not only smart but also kind.</i> <span style="color:#94a3b8">— Elle est non seulement intelligente mais aussi gentille.</span></p>' WHERE id = 44;

UPDATE grammar_lessons SET content = '<h3>However</h3><p>Cependant : <i>I was tired. However, I finished the work.</i> <span style="color:#94a3b8">— J''étais fatigué. Cependant, j''ai fini le travail.</span></p><h3>Nevertheless / Nonetheless</h3><p>Néanmoins (plus formel) : <i>The weather was bad. Nevertheless, we had a great time.</i> <span style="color:#94a3b8">— Le temps était mauvais. Néanmoins, nous nous sommes bien amusés.</span></p><h3>Therefore / Thus / Hence</h3><p>Par conséquent : <i>She was ill. Therefore, she stayed home.</i> <span style="color:#94a3b8">— Elle était malade. Par conséquent, elle est restée chez elle.</span></p>' WHERE id = 45;

UPDATE grammar_lessons SET content = '<h3>Avant une consonne</h3><p><i>a book, a university (se prononce [ju])</i> <span style="color:#94a3b8">— un livre, une université</span></p><h3>Avant une voyelle</h3><p><i>an apple, an hour (se prononce [aʊ])</i> <span style="color:#94a3b8">— une pomme, une heure</span></p><h3>Usage</h3><ul><li>Première mention : <i>I saw a dog.</i> <span style="color:#94a3b8">— J''ai vu un chien.</span></li><li>Profession : <i>She is a doctor.</i> <span style="color:#94a3b8">— Elle est docteur.</span></li><li>Exclamations : <i>What a beautiful day!</i> <span style="color:#94a3b8">— Quelle belle journée !</span></li></ul>' WHERE id = 46;

UPDATE grammar_lessons SET content = '<h3>Usage de THE</h3><ul><li>Quand l''élément est unique : <i>the sun, the president</i> <span style="color:#94a3b8">— le soleil, le président</span></li><li>Deuxième mention : <i>I saw a cat. The cat was black.</i> <span style="color:#94a3b8">— J''ai vu un chat. Le chat était noir.</span></li><li>Superlatifs : <i>the best, the most important</i> <span style="color:#94a3b8">— le meilleur, le plus important</span></li><li>Noms de fleuves, océans, chaînes de montagnes : <i>the Thames, the Pacific, the Alps</i> <span style="color:#94a3b8">— la Tamise, le Pacifique, les Alpes</span></li></ul><h3>Pas de THE</h3><ul><li>Noms de pays (sauf pluriels) : <i>France, the United States</i> <span style="color:#94a3b8">— la France, les États-Unis</span></li><li>Noms de villes, montagnes isolées, lacs</li><li>Repas, sports, langues</li></ul>' WHERE id = 47;

UPDATE grammar_lessons SET content = '<h3>Some</h3><p>Offres, demandes, affirmations : <i>Would you like some coffee?</i> <span style="color:#94a3b8">— Voudrais-tu du café ?</span> / <i>I have some time.</i> <span style="color:#94a3b8">— J''ai un peu de temps.</span></p><h3>Any</h3><p>Négations, interrogations : <i>I don''t have any money.</i> <span style="color:#94a3b8">— Je n''ai pas d''argent.</span> / <i>Do you have any questions?</i> <span style="color:#94a3b8">— As-tu des questions ?</span></p><h3>Exceptions</h3><p><i>Any</i> peut s''utiliser à l''affirmatif avec le sens de "n''importe quel" : <i>Any student can do this.</i> <span style="color:#94a3b8">— N''importe quel étudiant peut faire ça.</span></p>' WHERE id = 48;

UPDATE grammar_lessons SET content = '<h3>Much</h3><p>Noms indénombrables + négation/interrogation : <i>How much water?</i> <span style="color:#94a3b8">— Combien d''eau ?</span> / <i>I don''t have much time.</i> <span style="color:#94a3b8">— Je n''ai pas beaucoup de temps.</span></p><h3>Many</h3><p>Noms dénombrables + négation/interrogation : <i>How many books?</i> <span style="color:#94a3b8">— Combien de livres ?</span> / <i>I don''t have many friends.</i> <span style="color:#94a3b8">— Je n''ai pas beaucoup d''amis.</span></p><h3>A lot of / Lots of / Plenty of</h3><p>Tous types de noms, toutes situations : <i>I have a lot of time/friends.</i> <span style="color:#94a3b8">— J''ai beaucoup de temps/d''amis.</span></p>' WHERE id = 49;

UPDATE grammar_lessons SET content = '<h3>Few / A few</h3><p>Dénombrables : <i>Few people came.</i> <span style="color:#94a3b8">— Peu de gens sont venus.</span> (presque personne, négatif) / <i>A few people came.</i> <span style="color:#94a3b8">— Quelques gens sont venus.</span> (quelques-uns, positif)</p><h3>Little / A little</h3><p>Indénombrables : <i>Little water remained.</i> <span style="color:#94a3b8">— Il ne restait presque pas d''eau.</span> (presque rien, négatif) / <i>A little water remained.</i> <span style="color:#94a3b8">— Il restait un peu d''eau.</span> (un peu, positif)</p>' WHERE id = 50;
