-- ============================================================
-- GRAMMAIRE v18 — Ajout traductions leçons 51-75
-- ============================================================

UPDATE grammar_lessons SET content = '<h3>Tableau</h3><table><tr><th>Singulier</th><th>Pluriel</th></tr><tr><td>I (1e)</td><td>we (1e)</td></tr><tr><td>you (2e)</td><td>you (2e)</td></tr><tr><td>he/she/it (3e)</td><td>they (3e)</td></tr></table><h3>Usage</h3><p>Le sujet fait l''action : <i>She sings.</i> <span style="color:#94a3b8">— Elle chante.</span> / <i>They are happy.</i> <span style="color:#94a3b8">— Ils sont heureux.</span></p>' WHERE id = 51;

UPDATE grammar_lessons SET content = '<h3>Tableau</h3><table><tr><th>Singulier</th><th>Pluriel</th></tr><tr><td>me</td><td>us</td></tr><tr><td>you</td><td>you</td></tr><tr><td>him/her/it</td><td>them</td></tr></table><h3>Usage</h3><p>L''objet subit l''action : <i>She loves him.</i> <span style="color:#94a3b8">— Elle l''aime.</span> / <i>I saw them.</i> <span style="color:#94a3b8">— Je les ai vus.</span></p>' WHERE id = 52;

UPDATE grammar_lessons SET content = '<h3>Adjectifs possessifs (avant le nom)</h3><p>my, your, his, her, its, our, their</p><h3>Pronoms possessifs (remplacent le nom)</h3><p>mine, yours, his, hers, ours, theirs</p><h3>Exemples</h3><p><i>This is my book. / This book is mine.</i> <span style="color:#94a3b8">— C''est mon livre. / Ce livre est le mien.</span></p><p><i>That is her car. / That car is hers.</i> <span style="color:#94a3b8">— C''est sa voiture. / Cette voiture est la sienne.</span></p>' WHERE id = 53;

UPDATE grammar_lessons SET content = '<h3>Formation</h3><p>Adjectif possessif + <i>-self/-selves</i></p><h3>Usage</h3><ul><li>Action réflexive : <i>I cut myself.</i> <span style="color:#94a3b8">— Je me suis coupé.</span></li><li>Pour insister : <i>I did it myself.</i> <span style="color:#94a3b8">— Je l''ai fait moi-même.</span></li><li>Seul : <i>She lives by herself.</i> <span style="color:#94a3b8">— Elle vit seule.</span></li></ul>' WHERE id = 54;

UPDATE grammar_lessons SET content = '<h3>Singulier</h3><p><i>This</i> (proche) : <i>This book is mine.</i> <span style="color:#94a3b8">— Ce livre est à moi.</span></p><p><i>That</i> (loin) : <i>That car is red.</i> <span style="color:#94a3b8">— Cette voiture est rouge.</span></p><h3>Pluriel</h3><p><i>These</i> (proches) : <i>These apples are fresh.</i> <span style="color:#94a3b8">— Ces pommes sont fraîches.</span></p><p><i>Those</i> (loins) : <i>Those mountains are high.</i> <span style="color:#94a3b8">— Ces montagnes sont hautes.</span></p>' WHERE id = 55;

UPDATE grammar_lessons SET content = '<h3>Quelqu''un/quelque chose</h3><p><i>Somebody/someone/something</i> (affirmatif)</p><p><i>Anybody/anyone/anything</i> (négatif/interrogatif)</p><p><i>Nobody/no one/nothing</i> (négatif, sujet)</p><p><i>Everybody/everyone/everything</i> (tout le monde, tout)</p><h3>Accord du verbe</h3><p>Toujours singulier : <i>Everybody is happy.</i> <span style="color:#94a3b8">— Tout le monde est heureux.</span></p>' WHERE id = 56;

UPDATE grammar_lessons SET content = '<h3>Who</h3><p>Pour les personnes : <i>The man who called you is my boss.</i> <span style="color:#94a3b8">— L''homme qui t''a appelé est mon patron.</span></p><h3>Which</h3><p>Pour les choses/animaux : <i>The car which is parked outside is mine.</i> <span style="color:#94a3b8">— La voiture garée dehors est à moi.</span></p><h3>That</h3><p>Pour tout : <i>The book that I read was interesting.</i> <span style="color:#94a3b8">— Le livre que j''ai lu était intéressant.</span></p><h3>Whose / Whom</h3><p><i>Whose</i> = possession : <i>The man whose car was stolen...</i> <span style="color:#94a3b8">— L''homme dont la voiture a été volée...</span></p><p><i>Whom</i> = formel, objet : <i>The person to whom I spoke...</i> <span style="color:#94a3b8">— La personne à qui j''ai parlé...</span></p>' WHERE id = 57;

UPDATE grammar_lessons SET content = '<h3>Who</h3><p>Pour les personnes (sujet) : <i>Who is coming?</i> <span style="color:#94a3b8">— Qui vient ?</span></p><h3>Whom</h3><p>Pour les personnes (objet, formel) : <i>Whom did you see?</i> <span style="color:#94a3b8">— Qui as-tu vu ?</span></p><h3>What</h3><p>Pour les choses : <i>What is your name?</i> <span style="color:#94a3b8">— Quel est ton nom ?</span></p><h3>Which</h3><p>Choix limité : <i>Which colour do you prefer?</i> <span style="color:#94a3b8">— Quelle couleur préfères-tu ?</span></p><h3>Whose</h3><p>Possession : <i>Whose car is this?</i> <span style="color:#94a3b8">— À qui est cette voiture ?</span></p>' WHERE id = 58;

UPDATE grammar_lessons SET content = '<h3>Each other</h3><p>Entre deux personnes : <i>They love each other.</i> <span style="color:#94a3b8">— Ils s''aiment l''un l''autre.</span></p><h3>One another</h3><p>Entre plusieurs personnes (théorique) : <i>They helped one another.</i> <span style="color:#94a3b8">— Ils se sont aidés les uns les autres.</span></p><h3>Usage moderne</h3><p>Aujourd''hui, <i>each other</i> et <i>one another</i> sont souvent interchangeables.</p>' WHERE id = 59;

UPDATE grammar_lessons SET content = '<h3>One</h3><p>Très formel, britannique : <i>One must be careful.</i> <span style="color:#94a3b8">— Il faut être prudent. (on doit)</span></p><h3>You</h3><p>Courant, général : <i>You must be careful.</i> <span style="color:#94a3b8">— Il faut être prudent.</span></p><h3>Différence</h3><p><i>One</i> est plus impersonnel et soutenu. <i>You</i> est plus naturel à l''oral.</p>' WHERE id = 60;

UPDATE grammar_lessons SET content = '<h3>Formation</h3><p><i>BE</i> (présent) + participe passé</p><h3>Exemples</h3><ul><li>Active : <i>Someone cleans the room every day.</i> <span style="color:#94a3b8">— Quelqu''un nettoie la pièce tous les jours.</span></li><li>Passive : <i>The room is cleaned every day.</i> <span style="color:#94a3b8">— La pièce est nettoyée tous les jours.</span></li></ul><h3>Usage</h3><p>Quand l''agent est inconnu, moins important ou évident : <i>My car was stolen.</i> <span style="color:#94a3b8">— Ma voiture a été volée.</span></p>' WHERE id = 61;

UPDATE grammar_lessons SET content = '<h3>Prétérit</h3><p><i>was/were</i> + participe passé : <i>The letter was written yesterday.</i> <span style="color:#94a3b8">— La lettre a été écrite hier.</span></p><h3>Avec modaux</h3><p>Modal + <i>be</i> + participe passé : <i>The report must be finished by Friday.</i> <span style="color:#94a3b8">— Le rapport doit être fini pour vendredi.</span></p><h3>By + agent</h3><p>Quand on mentionne l''agent : <i>The book was written by Hemingway.</i> <span style="color:#94a3b8">— Le livre a été écrit par Hemingway.</span></p>' WHERE id = 62;

UPDATE grammar_lessons SET content = '<h3>Transformation</h3><ul><li>Guillemets → that</li><li>Pronoms : <i>I → he/she</i>, <i>my → his/her</i></li><li>Temps : <i>am → was</i>, <i>have → had</i></li><li>Adverbes : <i>now → then</i>, <i>today → that day</i>, <i>yesterday → the day before</i></li></ul><h3>Exemple</h3><p>Direct : <i>She said, "I am tired."</i></p><p>Reported : <i>She said (that) she was tired.</i> <span style="color:#94a3b8">— Elle a dit qu''elle était fatiguée.</span></p>' WHERE id = 63;

UPDATE grammar_lessons SET content = '<h3>Questions fermées (yes/no)</h3><p><i>if/whether</i> + sujet + verbe : <i>He asked if she was coming.</i> <span style="color:#94a3b8">— Il a demandé si elle venait.</span></p><h3>Questions ouvertes</h3><p>Mot interrogatif + sujet + verbe : <i>She asked where he lived.</i> <span style="color:#94a3b8">— Elle a demandé où il vivait.</span></p><h3>Ordres/demandes</h3><p><i>Tell/ask/order + object + to + infinitive</i> : <i>He told me to wait.</i> <span style="color:#94a3b8">— Il m''a dit d''attendre.</span></p>' WHERE id = 64;

UPDATE grammar_lessons SET content = '<h3>Zero conditional</h3><p>Vérité générale : <i>If + présent, présent</i></p><p><i>If you heat ice, it melts.</i> <span style="color:#94a3b8">— Si tu chauffes de la glace, elle fond.</span></p><h3>First conditional</h3><p>Réel/probable : <i>If + présent, will + base</i></p><p><i>If it rains, I will stay home.</i> <span style="color:#94a3b8">— S''il pleut, je resterai chez moi.</span></p>' WHERE id = 65;

UPDATE grammar_lessons SET content = '<h3>Second conditional</h3><p>Hypothétique/improbable : <i>If + prétérit, would + base</i></p><p><i>If I won the lottery, I would buy a house.</i> <span style="color:#94a3b8">— Si je gagnais à la loterie, j''achèterais une maison.</span></p><h3>Be → were (toutes les personnes)</h3><p><i>If I were rich, I would travel the world.</i> <span style="color:#94a3b8">— Si j''étais riche, je voyagerais autour du monde.</span></p><p>Aussi : <i>If he were here, he would help.</i> <span style="color:#94a3b8">— S''il était là, il aiderait.</span></p>' WHERE id = 66;

UPDATE grammar_lessons SET content = '<h3>Third conditional</h3><p>Regret/impossible dans le passé : <i>If + past perfect, would have + past participle</i></p><p><i>If I had studied harder, I would have passed the exam.</i> <span style="color:#94a3b8">— Si j''avais étudié plus dur, j''aurais réussi l''examen.</span></p><h3>Variation</h3><p><i>Could have, might have</i> au lieu de <i>would have</i></p>' WHERE id = 67;

UPDATE grammar_lessons SET content = '<h3>Wish + prétérit</h3><p>Souhait contraire à la réalité présente : <i>I wish I were taller.</i> <span style="color:#94a3b8">— J''aimerais être plus grand.</span></p><p><i>I wish I had a car.</i> <span style="color:#94a3b8">— J''aimerais avoir une voiture.</span> (mais je n''en ai pas)</p><h3>If only</h3><p>Même sens, plus émotif : <i>If only she knew the truth!</i> <span style="color:#94a3b8">— Si seulement elle savait la vérité !</span></p>' WHERE id = 68;

UPDATE grammar_lessons SET content = '<h3>Wish + past perfect</h3><p>Regret dans le passé : <i>I wish I had studied medicine.</i> <span style="color:#94a3b8">— J''aurais aimé étudier la médecine.</span></p><h3>Exemples</h3><p><i>She wishes she had never met him.</i> <span style="color:#94a3b8">— Elle regrette de l''avoir rencontré.</span></p><p><i>If only I had listened to my parents!</i> <span style="color:#94a3b8">— Si seulement j''avais écouté mes parents !</span></p>' WHERE id = 69;

UPDATE grammar_lessons SET content = '<h3>Have/get + object + past participle</h3><p><i>I had my hair cut.</i> <span style="color:#94a3b8">— Je me suis fait couper les cheveux.</span> (quelqu''un m''a coupé les cheveux)</p><p><i>She is getting the car repaired.</i> <span style="color:#94a3b8">— Elle fait réparer la voiture.</span></p><h3>Différences</h3><p><i>Have</i> = plus courant. <i>Get</i> = plus informel.</p>' WHERE id = 70;

UPDATE grammar_lessons SET content = '<h3>Used to + base</h3><p>Habitude passée (aujourd''hui non) : <i>I used to smoke. (but I quit)</i> <span style="color:#94a3b8">— Je fumais avant. (mais j''ai arrêté)</span></p><h3>Be used to + V-ing / nom</h3><p>Être habitué à : <i>I am used to waking up early.</i> <span style="color:#94a3b8">— Je suis habitué à me lever tôt.</span></p><h3>Get used to</h3><p>Devenir habitué : <i>I got used to the noise.</i> <span style="color:#94a3b8">— Je me suis habitué au bruit.</span></p>' WHERE id = 71;

UPDATE grammar_lessons SET content = '<h3>Too + adjectif</h3><p>Trop (négatif, impossible) : <i>It is too cold to go out.</i> <span style="color:#94a3b8">— Il fait trop froid pour sortir.</span></p><h3>Adjectif + enough</h3><p>Assez (positif, possible) : <i>It is warm enough to go out.</i> <span style="color:#94a3b8">— Il fait assez chaud pour sortir.</span></p><h3>Not + adjectif + enough</h3><p>Pas assez : <i>He is not tall enough to reach the shelf.</i> <span style="color:#94a3b8">— Il n''est pas assez grand pour atteindre l''étagère.</span></p>' WHERE id = 72;

UPDATE grammar_lessons SET content = '<h3>So + adjectif/adverbe</h3><p><i>So beautiful, so quickly</i> <span style="color:#94a3b8">— si beau, si rapidement</span></p><h3>Such + (a/an) + adjectif + nom</h3><p><i>Such a beautiful day, such bad weather</i> <span style="color:#94a3b8">— une si belle journée, un si mauvais temps</span></p><h3>So...that / Such...that</h3><p><i>It was so cold that we stayed inside.</i> <span style="color:#94a3b8">— Il faisait si froid que nous sommes restés à l''intérieur.</span></p><p><i>It was such a good film that I saw it twice.</i> <span style="color:#94a3b8">— C''était un si bon film que je l''ai vu deux fois.</span></p>' WHERE id = 73;

UPDATE grammar_lessons SET content = '<h3>SVO (Subject + Verb + Object)</h3><p><i>She (S) eats (V) apples (O).</i> <span style="color:#94a3b8">— Elle mange des pommes.</span></p><h3>Place des adverbes</h3><p>Fréquence : avant le verbe principal, après BE</p><p><i>She always eats apples. / She is always late.</i> <span style="color:#94a3b8">— Elle mange toujours des pommes. / Elle est toujours en retard.</span></p><h3>Inversion en questions</h3><p><i>Do you like apples?</i> <span style="color:#94a3b8">— Aimes-tu les pommes ?</span></p><p><i>Are you happy?</i> <span style="color:#94a3b8">— Es-tu heureux ?</span></p>' WHERE id = 74;

UPDATE grammar_lessons SET content = '<h3>Formation</h3><p>Auxiliaire + pronom (opposé à l''affirmation) : <i>You are happy, aren''t you?</i> <span style="color:#94a3b8">— Tu es heureux, n''est-ce pas ?</span></p><h3>Règles</h3><ul><li>Phrase positive → tag négatif</li><li>Phrase négative → tag positif</li><li>BE et auxiliaires se répètent : <i>She has left, hasn''t she?</i> <span style="color:#94a3b8">— Elle est partie, n''est-ce pas ?</span></li></ul><h3>Exceptions</h3><p><i>Let''s... shall we?</i> <span style="color:#94a3b8">— Allons-y, d''accord ?</span> / <i>I am... aren''t I?</i> <span style="color:#94a3b8">— Je suis..., n''est-ce pas ?</span></p>' WHERE id = 75;
