-- GRAMMAIRE v19 — Traductions leçons 76-85

UPDATE grammar_lessons SET content = '<h3>After negative adverbs</h3><p><i>Never have I seen such beauty.</i> <span style="color:#94a3b8">— Jamais je n''ai vu une telle beauté.</span></p><p><i>Hardly had I arrived when it started to rain.</i> <span style="color:#94a3b8">— Je venais à peine d''arriver quand il a commencé à pleuvoir.</span></p><h3>Conditionnel sans if</h3><p><i>Were I rich, I would travel.</i> <span style="color:#94a3b8">— Si j''étais riche, je voyagerais.</span></p>' WHERE id = 76;

UPDATE grammar_lessons SET content = '<h3>It is/was... that/who</h3><p><i>It was John who bought a car yesterday.</i> <span style="color:#94a3b8">— C''est John qui a acheté une voiture hier.</span></p><p><i>It was a car that John bought yesterday.</i> <span style="color:#94a3b8">— C''est une voiture que John a achetée hier.</span></p><p><i>It was yesterday that John bought a car.</i> <span style="color:#94a3b8">— C''est hier que John a acheté une voiture.</span></p>' WHERE id = 77;

UPDATE grammar_lessons SET content = '<h3>Do/Does/Did + base</h3><p><i>I do like you!</i> <span style="color:#94a3b8">— Je t''aime vraiment !</span></p><p><i>She does speak French.</i> <span style="color:#94a3b8">— Elle parle bien français.</span></p><p><i>Do be careful!</i> <span style="color:#94a3b8">— Fais bien attention !</span></p><p><i>He did finish his homework.</i> <span style="color:#94a3b8">— Il a bien fini ses devoirs.</span></p>' WHERE id = 78;

UPDATE grammar_lessons SET content = '<h3>Verbes suivis du gérondif</h3><p><i>I enjoy reading.</i> <span style="color:#94a3b8">— J''aime lire.</span></p><h3>Verbes suivis de l''infinitif</h3><p><i>I want to learn.</i> <span style="color:#94a3b8">— Je veux apprendre.</span></p>' WHERE id = 79;

UPDATE grammar_lessons SET content = '<h3>Stop + gérondif</h3><p><i>Stop smoking!</i> <span style="color:#94a3b8">— Arrête de fumer !</span></p><h3>Stop + infinitif</h3><p><i>He stopped to tie his shoelaces.</i> <span style="color:#94a3b8">— Il s''est arrêté pour faire ses lacets.</span></p><h3>Remember + gérondif</h3><p><i>I remember locking the door.</i> <span style="color:#94a3b8">— Je me souviens d''avoir fermé la porte.</span></p><h3>Remember + infinitif</h3><p><i>Remember to lock the door.</i> <span style="color:#94a3b8">— N''oublie pas de fermer la porte.</span></p><h3>Try + gérondif</h3><p><i>Try eating less sugar.</i> <span style="color:#94a3b8">— Essaie de manger moins de sucre.</span></p><h3>Try + infinitif</h3><p><i>Try to be on time.</i> <span style="color:#94a3b8">— Essaie d''être à l''heure.</span></p>' WHERE id = 80;

UPDATE grammar_lessons SET content = '<h3>Exemples courants</h3><ul><li><i>get up</i> = se lever : <i>I get up at 7 AM.</i> <span style="color:#94a3b8">— Je me lève à 7h.</span></li><li><i>turn on</i> = allumer</li><li><i>look for</i> = chercher</li><li><i>give up</i> = abandonner</li><li><i>take off</i> = décoller / enlever</li><li><i>put on</i> = mettre (vêtements)</li><li><i>look after</i> = s''occuper de</li></ul>' WHERE id = 81;

UPDATE grammar_lessons SET content = '<h3>Séparables</h3><p><i>turn off the TV / turn the TV off / turn it off</i> <span style="color:#94a3b8">— éteindre la télé</span></p><h3>Non-séparables</h3><p><i>look after the children</i> <span style="color:#94a3b8">— s''occuper des enfants</span> (PAS look the children after)</p>' WHERE id = 82;

UPDATE grammar_lessons SET content = '<h3>Types</h3><ul><li>Verbe + nom : <i>have breakfast, take a shower, make progress</i> <span style="color:#94a3b8">— prendre le petit-déj, prendre une douche, faire des progrès</span></li><li>Adjectif + nom : <i>heavy rain, strong coffee, fast food</i> <span style="color:#94a3b8">— forte pluie, café fort, fast food</span></li></ul>' WHERE id = 83;

UPDATE grammar_lessons SET content = '<h3>Expressions courantes</h3><ul><li><i>It''s raining cats and dogs.</i> <span style="color:#94a3b8">— Il pleut des cordes.</span></li><li><i>Break a leg!</i> <span style="color:#94a3b8">— Bonne chance !</span></li><li><i>Bite the bullet.</i> <span style="color:#94a3b8">— Prendre son courage à deux mains.</span></li><li><i>Hit the sack.</i> <span style="color:#94a3b8">— Aller se coucher.</span></li><li><i>Let the cat out of the bag.</i> <span style="color:#94a3b8">— Vendre la mèche.</span></li><li><i>Once in a blue moon.</i> <span style="color:#94a3b8">— Tous les trente-six du mois.</span></li></ul>' WHERE id = 84;

UPDATE grammar_lessons SET content = '<h3>Verbe + préposition</h3><ul><li><i>listen to</i> <span style="color:#94a3b8">— écouter</span> (PAS listen the radio)</li><li><i>look at</i> <span style="color:#94a3b8">— regarder</span></li><li><i>wait for</i> <span style="color:#94a3b8">— attendre</span></li><li><i>ask for</i> <span style="color:#94a3b8">— demander</span></li><li><i>pay for</i> <span style="color:#94a3b8">— payer pour</span></li><li><i>depend on</i> <span style="color:#94a3b8">— dépendre de</span></li><li><i>believe in</i> <span style="color:#94a3b8">— croire en</span></li><li><i>agree with</i> <span style="color:#94a3b8">— être d''accord avec</span></li><li><i>apologize for</i> <span style="color:#94a3b8">— s''excuser pour</span></li><li><i>dream of</i> <span style="color:#94a3b8">— rêver de</span></li></ul><p>Attention : aucune logique, il faut apprendre par cœur.</p>' WHERE id = 85;
