-- GRAMMAIRE v20 — Traductions leçons 86-110

UPDATE grammar_lessons SET content = '<h3>Formel</h3><p><i>Dear Sir or Madam, I am writing to inquire about...</i> <span style="color:#94a3b8">— Cher Monsieur ou chère Madame, je vous écris pour demander...</span></p><h3>Informel</h3><p><i>Hey! How''s it going? Just wanted to ask...</i> <span style="color:#94a3b8">— Salut ! Ça va ? Je voulais juste demander...</span></p><h3>Différences</h3><table><tr><th>Formel</th><th>Informel</th></tr><tr><td>I would like to</td><td>I want to</td></tr><tr><td>Could you please</td><td>Can you</td></tr><tr><td>I am afraid</td><td>Sorry</td></tr><tr><td>Furthermore</td><td>Also</td></tr></table>' WHERE id = 86;

UPDATE grammar_lessons SET content = '<h3>Exemples courants</h3><table><tr><th>Anglais</th><th>Faux ami</th><th>Vrai sens</th></tr><tr><td>actually</td><td>actuellement</td><td>en fait</td></tr><tr><td>eventually</td><td>éventuellement</td><td>finalement</td></tr><tr><td>currently</td><td>couramment</td><td>actuellement</td></tr><tr><td>library</td><td>librairie</td><td>bibliothèque</td></tr><tr><td>bookshop</td><td>-</td><td>librairie</td></tr></table>' WHERE id = 87;

UPDATE grammar_lessons SET content = '<h3>Vocabulaire</h3><table><tr><th>UK</th><th>US</th></tr><tr><td>lift</td><td>elevator</td></tr><tr><td>flat</td><td>apartment</td></tr><tr><td>lorry</td><td>truck</td></tr><tr><td>petrol</td><td>gas</td></tr><tr><td>chips</td><td>fries</td></tr><tr><td>crisps</td><td>chips</td></tr></table><h3>Orthographe</h3><p><i>colour/color, organise/organize, travelled/traveled</i></p>' WHERE id = 88;

UPDATE grammar_lessons SET content = '<h3>Règle</h3><p>En anglais standard, une seule négation par phrase.</p><h3>Incorrect</h3><p><i>I don''t know nothing.</i> <span style="color:#94a3b8">— FAUX</span></p><h3>Correct</h3><p><i>I don''t know anything.</i> <span style="color:#94a3b8">— Je ne sais rien.</span></p><p><i>I know nothing.</i> <span style="color:#94a3b8">— Je ne sais rien.</span></p><h3>Exception</h3><p><i>I can''t not help you.</i> <span style="color:#94a3b8">— Je ne peux pas ne pas t''aider. (= Je dois t''aider)</span></p>' WHERE id = 89;

UPDATE grammar_lessons SET content = '<h3>Formation</h3><p><i>as + adjectif/adverbe + as</i></p><h3>Exemples</h3><p><i>She is as tall as her brother.</i> <span style="color:#94a3b8">— Elle est aussi grande que son frère.</span></p><p><i>I run as fast as you.</i> <span style="color:#94a3b8">— Je cours aussi vite que toi.</span></p><h3>Négation</h3><p><i>not as/so + adjectif + as</i> : <i>He is not as rich as his father.</i> <span style="color:#94a3b8">— Il n''est pas aussi riche que son père.</span></p>' WHERE id = 90;

UPDATE grammar_lessons SET content = '<h3>Nombres cardinaux</h3><p>21 = twenty-one, 100 = one hundred, 1,000 = one thousand</p><h3>Nombres ordinaux</h3><p>1st = first, 2nd = second, 3rd = third, 21st = twenty-first</p><h3>Dates</h3><p>UK : <i>14th March 2024 / the fourteenth of March</i> <span style="color:#94a3b8">— le 14 mars 2024</span></p><p>US : <i>March 14, 2024 / March the fourteenth</i> <span style="color:#94a3b8">— le 14 mars 2024</span></p>' WHERE id = 91;

UPDATE grammar_lessons SET content = '<h3>Let</h3><p>Permettre : <i>She let me go.</i> <span style="color:#94a3b8">— Elle m''a laissé partir.</span></p><h3>Make</h3><p>Forcer : <i>She made me laugh.</i> <span style="color:#94a3b8">— Elle m''a fait rire.</span></p><h3>Have</h3><p>Demander à quelqu''un de faire : <i>I had him fix my computer.</i> <span style="color:#94a3b8">— Je lui ai demandé de réparer mon ordinateur.</span></p><h3>Attention</h3><p><i>Let</i> et <i>make</i> sont suivis de l''infinitif SANS to.</p>' WHERE id = 92;

UPDATE grammar_lessons SET content = '<h3>Would rather + base</h3><p>Préférence pour soi : <i>I would rather stay home.</i> <span style="color:#94a3b8">— Je préférerais rester chez moi.</span></p><h3>Would rather + sujet + prétérit</h3><p>Préférence pour quelqu''un d''autre : <i>I would rather you didn''t smoke here.</i> <span style="color:#94a3b8">— J''aimerais mieux que tu ne fumes pas ici.</span></p><h3>Had better</h3><p>Conseil fort : <i>You had better hurry.</i> <span style="color:#94a3b8">— Tu ferais mieux de te dépêcher.</span></p>' WHERE id = 93;

UPDATE grammar_lessons SET content = '<h3>There is</h3><p>Singulier/indénombrable : <i>There is a book on the table.</i> <span style="color:#94a3b8">— Il y a un livre sur la table.</span></p><h3>There are</h3><p>Pluriel : <i>There are three chairs.</i> <span style="color:#94a3b8">— Il y a trois chaises.</span></p><h3>There was/were</h3><p>Passé : <i>There was a problem yesterday.</i> <span style="color:#94a3b8">— Il y avait un problème hier.</span></p><h3>There will be</h3><p>Futur : <i>There will be a meeting tomorrow.</i> <span style="color:#94a3b8">— Il y aura une réunion demain.</span></p>' WHERE id = 94;

UPDATE grammar_lessons SET content = '<h3>Temps</h3><p><i>It is 3 o''clock. / It was raining.</i> <span style="color:#94a3b8">— Il est 3 heures. / Il pleuvait.</span></p><h3>Distance</h3><p><i>It is 10 kilometres to the city.</i> <span style="color:#94a3b8">— Il y a 10 kilomètres jusqu''à la ville.</span></p><h3>Identification</h3><p><i>It is John at the door.</i> <span style="color:#94a3b8">— C''est John à la porte.</span></p><h3>Impossible sans it</h3><p><i>It is important to study.</i> <span style="color:#94a3b8">— Il est important d''étudier.</span></p>' WHERE id = 95;

UPDATE grammar_lessons SET content = '<h3>Adjectifs courts</h3><p>tall → taller → tallest / big → bigger → biggest</p><h3>Adjectifs longs</h3><p>beautiful → more beautiful → most beautiful</p><h3>Exceptions</h3><p>good → better → best / bad → worse → worst / far → further → furthest</p><h3>Than</h3><p><i>She is taller than her brother.</i> <span style="color:#94a3b8">— Elle est plus grande que son frère.</span></p><h3>The...in/of</h3><p><i>He is the best player in the team.</i> <span style="color:#94a3b8">— C''est le meilleur joueur de l''équipe.</span></p>' WHERE id = 96;

UPDATE grammar_lessons SET content = '<h3>Singulier</h3><p><i>the boy''s book, James''s car / James'' car</i> <span style="color:#94a3b8">— le livre du garçon, la voiture de James</span></p><h3>Pluriel</h3><p><i>the boys'' books</i> <span style="color:#94a3b8">— les livres des garçons</span></p><h3>Exceptions</h3><p><i>its</i> = possessif (pas d''apostrophe) | <i>it''s</i> = it is / it has</p><h3>Usage</h3><p>Personnes, animaux : <i>my brother''s wife, the dog''s tail</i> <span style="color:#94a3b8">— la femme de mon frère, la queue du chien</span></p>' WHERE id = 97;

UPDATE grammar_lessons SET content = '<h3>Présent simple / Prétérit simple</h3><p><i>She does not like coffee.</i> <span style="color:#94a3b8">— Elle n''aime pas le café.</span></p><h3>BE</h3><p><i>He is not here.</i> <span style="color:#94a3b8">— Il n''est pas là.</span></p><h3>Modaux</h3><p><i>I cannot swim.</i> <span style="color:#94a3b8">— Je ne sais pas nager.</span></p><h3>Auxiliaires</h3><p><i>I have not finished.</i> <span style="color:#94a3b8">— Je n''ai pas fini.</span></p>' WHERE id = 98;

UPDATE grammar_lessons SET content = '<h3>Questions fermées (yes/no)</h3><p><i>Do you like pizza? / Are you happy?</i> <span style="color:#94a3b8">— Aimes-tu la pizza ? / Es-tu heureux ?</span></p><h3>Questions ouvertes (WH-)</h3><p><i>Where do you live? / What are you doing?</i> <span style="color:#94a3b8">— Où habites-tu ? / Que fais-tu ?</span></p><h3>Questions avec préposition</h3><p>Formel : <i>To whom did you speak?</i> <span style="color:#94a3b8">— À qui as-tu parlé ?</span></p><p>Courant : <i>Who did you speak to?</i> <span style="color:#94a3b8">— À qui as-tu parlé ?</span></p>' WHERE id = 99;

UPDATE grammar_lessons SET content = '<h3>Pas d''article devant</h3><ul><li>Noms propres : <i>France, Paris, Everest</i> <span style="color:#94a3b8">— la France, Paris, l''Everest</span></li><li>Repas : <i>have breakfast</i> <span style="color:#94a3b8">— prendre le petit-déj</span></li><li>Sports : <i>play football</i> <span style="color:#94a3b8">— jouer au foot</span></li><li>Langues : <i>speak French</i> <span style="color:#94a3b8">— parler français</span></li></ul><h3>Attention</h3><p><i>The United States, the Alps</i> <span style="color:#94a3b8">— les États-Unis, les Alpes</span> (noms pluriels)</p>' WHERE id = 100;

UPDATE grammar_lessons SET content = '<h3>Dénombrables</h3><p><i>a book, two books, many books</i> <span style="color:#94a3b8">— un livre, deux livres, beaucoup de livres</span></p><h3>Indénombrables</h3><p><i>water, information, advice, furniture, luggage, money, news</i></p><h3>Quantifiers</h3><p>Dénombrables : <i>many, a few, several</i></p><p>Indénombrables : <i>much, a little, a bit of</i></p>' WHERE id = 101;

UPDATE grammar_lessons SET content = '<h3>All / Both</h3><p><i>All students passed.</i> <span style="color:#94a3b8">— Tous les élèves ont réussi.</span></p><p><i>Both answers are correct.</i> <span style="color:#94a3b8">— Les deux réponses sont correctes.</span></p><h3>Either / Neither</h3><p><i>Either day is fine.</i> <span style="color:#94a3b8">— N''importe quel jour convient.</span></p><p><i>Neither answer is correct.</i> <span style="color:#94a3b8">— Aucune réponse n''est correcte.</span></p><h3>None / No</h3><p><i>None of them came.</i> <span style="color:#94a3b8">— Aucun d''eux n''est venu.</span></p>' WHERE id = 102;

UPDATE grammar_lessons SET content = '<h3>Every vs Each</h3><p><i>Every student has a book.</i> <span style="color:#94a3b8">— Chaque élève a un livre.</span></p><p><i>Each student has his own book.</i> <span style="color:#94a3b8">— Chaque élève a son propre livre.</span></p><h3>None of</h3><p><i>None of my friends came.</i> <span style="color:#94a3b8">— Aucun de mes amis n''est venu.</span></p>' WHERE id = 103;

UPDATE grammar_lessons SET content = '<h3>Formation</h3><ul><li><i>well-known</i> = bien connu</li><li><i>hard-working</i> = travailleur</li><li><i>good-looking</i> = beau/belle</li><li><i>long-lasting</i> = durable</li><li><i>old-fashioned</i> = démodé</li></ul><h3>Position</h3><p>Avant le nom : <i>a well-known actor</i> <span style="color:#94a3b8">— un acteur bien connu</span></p><p>Après BE : <i>The actor is well-known.</i> <span style="color:#94a3b8">— L''acteur est bien connu.</span></p>' WHERE id = 104;

UPDATE grammar_lessons SET content = '<h3>Préfixes</h3><ul><li>un- : <i>unhappy</i> <span style="color:#94a3b8">— malheureux</span></li><li>dis- : <i>disagree</i> <span style="color:#94a3b8">— ne pas être d''accord</span></li><li>in- : <i>incorrect</i> <span style="color:#94a3b8">— incorrect</span></li><li>re- : <i>rewrite</i> <span style="color:#94a3b8">— réécrire</span></li><li>pre- : <i>preview</i> <span style="color:#94a3b8">— aperçu</span></li><li>mis- : <i>misunderstand</i> <span style="color:#94a3b8">— mal comprendre</span></li></ul><h3>Suffixes</h3><ul><li>-ness : <i>happiness</i> <span style="color:#94a3b8">— bonheur</span></li><li>-ful : <i>beautiful</i> <span style="color:#94a3b8">— beau</span></li><li>-less : <i>homeless</i> <span style="color:#94a3b8">— sans-abri</span></li><li>-ment : <i>government</i> <span style="color:#94a3b8">— gouvernement</span></li></ul>' WHERE id = 105;

UPDATE grammar_lessons SET content = '<h3>Ajouter une idée</h3><p>furthermore, moreover, in addition, besides</p><h3>Contraster</h3><p>however, nevertheless, on the other hand, in contrast</p><h3>Expliquer</h3><p>in other words, that is to say, to put it another way</p><h3>Conclure</h3><p>in conclusion, to sum up, all in all, in short</p>' WHERE id = 106;

UPDATE grammar_lessons SET content = '<h3>Formation</h3><p>Base verbale pour toutes les personnes (pas de -s à la 3e personne)</p><h3>Usage</h3><ul><li><i>He suggested that she come early.</i> <span style="color:#94a3b8">— Il a suggéré qu''elle vienne tôt.</span></li><li><i>God save the Queen! / Long live the King!</i> <span style="color:#94a3b8">— Dieu sauve la Reine ! / Vive le Roi !</span></li><li><i>It is important that he be here.</i> <span style="color:#94a3b8">— Il est important qu''il soit là.</span></li></ul><h3>UK vs US</h3><p>Plus courant en américain. En britannique : <i>He suggested that she should come.</i></p>' WHERE id = 107;

UPDATE grammar_lessons SET content = '<h3>Définition</h3><p><i>My brother, a doctor, lives in London.</i> <span style="color:#94a3b8">— Mon frère, médecin, vit à Londres.</span></p><h3>Avec ou sans virgules</h3><ul><li>Avec virgules : <i>Paris, the capital of France, is beautiful.</i> <span style="color:#94a3b8">— Paris, capitale de la France, est belle.</span></li><li>Sans virgules : <i>the writer Hemingway</i> <span style="color:#94a3b8">— l''écrivain Hemingway</span></li></ul>' WHERE id = 108;

UPDATE grammar_lessons SET content = '<h3>Dans les réponses</h3><p><i>Are you coming? Yes, I am.</i> <span style="color:#94a3b8">— Tu viens ? Oui.</span></p><h3>Après and, but, or</h3><p><i>She sings and (she) dances.</i> <span style="color:#94a3b8">— Elle chante et danse.</span></p><h3>Comparaisons</h3><p><i>She sings better than I do.</i> <span style="color:#94a3b8">— Elle chante mieux que moi.</span></p><h3>Infinitif</h3><p><i>I want to go and (to) see her.</i> <span style="color:#94a3b8">— Je veux aller la voir.</span></p>' WHERE id = 109;

UPDATE grammar_lessons SET content = '<h3>Récapitulatif des structures avancées</h3><ul><li>Inversion : <i>Never have I...</i> <span style="color:#94a3b8">— Jamais je n''ai...</span></li><li>Cleft sentences : <i>It was... who...</i> <span style="color:#94a3b8">— C''était... qui...</span></li><li>Subjonctif : <i>I suggest that he be...</i> <span style="color:#94a3b8">— Je suggère qu''il soit...</span></li><li>Emphatic do : <i>I do believe...</i> <span style="color:#94a3b8">— Je crois bien que...</span></li><li>Conditionnels mixtes : <i>If I had studied, I would be a doctor now.</i> <span style="color:#94a3b8">— Si j''avais étudié, je serais médecin maintenant.</span></li></ul><h3>Astuce</h3><p>Lire beaucoup pour intégrer ces structures naturellement.</p>' WHERE id = 110;
