CREATE TABLE IF NOT EXISTS dictation_sentences (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text TEXT NOT NULL,
  translation_fr TEXT,
  difficulty TEXT NOT NULL DEFAULT 'A2',
  category TEXT,
  audio_url TEXT,
  created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now'))
);

INSERT INTO dictation_sentences (text, translation_fr, difficulty, category) VALUES
('To be, or not to be, that is the question.', 'Être ou ne pas être, telle est la question.', 'B2', 'literature'),
('It was the best of times, it was the worst of times.', 'C''était le meilleur des temps, c''était le pire des temps.', 'B2', 'literature'),
('All animals are equal, but some animals are more equal than others.', 'Tous les animaux sont égaux, mais certains animaux sont plus égaux que d''autres.', 'B1', 'literature'),
('The only way to do great work is to love what you do.', 'La seule façon de faire du bon travail est d''aimer ce que vous faites.', 'A2', 'quotes'),
('Life is what happens when you are busy making other plans.', 'La vie, c''est ce qui arrive quand vous êtes occupé à faire d''autres projets.', 'A2', 'quotes'),
('In the beginning, God created the heavens and the earth.', 'Au commencement, Dieu créa les cieux et la terre.', 'B1', 'literature'),
('The sun did not shine. It was too wet to play.', 'Le soleil ne brillait pas. Il faisait trop humide pour jouer.', 'A1', 'literature'),
('A person who never made a mistake never tried anything new.', 'Une personne qui n''a jamais commis d''erreur n''a jamais essayé quelque chose de nouveau.', 'B1', 'quotes'),
('The journey of a thousand miles begins with a single step.', 'Le voyage de mille lieues commence par un seul pas.', 'A2', 'quotes'),
('What we think, we become.', 'Nous devenons ce que nous pensons.', 'A2', 'quotes'),
('Do not go gentle into that good night.', 'N''entre pas sans raison dans cette bonne nuit.', 'C1', 'literature'),
('I have a dream that one day this nation will rise up.', 'J''ai un rêve qu''un jour cette nation se lèvera.', 'B2', 'quotes'),
('The unexamined life is not worth living.', 'La vie non examinée ne vaut pas la peine d''être vécue.', 'C1', 'quotes'),
('Happiness depends upon ourselves.', 'Le bonheur dépend de nous-mêmes.', 'B1', 'quotes'),
('Not all those who wander are lost.', 'Tous ceux qui errent ne sont pas perdus.', 'B2', 'literature'),
('It does not do to dwell on dreams and forget to live.', 'Il ne faut pas se perdre dans les rêves et oublier de vivre.', 'B2', 'literature'),
('The only thing we have to fear is fear itself.', 'La seule chose que nous devions craindre, c''est la peur elle-même.', 'B2', 'quotes'),
('If you tell the truth, you do not have to remember anything.', 'Si vous dites la vérité, vous n''avez pas besoin de vous souvenir de quoi que ce soit.', 'A2', 'quotes'),
('Wisdom is not a product of schooling but of the lifelong attempt to acquire it.', 'La sagesse n''est pas un produit de l''école mais de la tentative de l''acquérir toute la vie.', 'C1', 'quotes'),
('The greatest glory in living lies not in never falling, but in rising every time we fall.', 'La plus grande gloire de vivre ne réside pas dans le fait de ne jamais tomber, mais de se relever à chaque chute.', 'B2', 'quotes'),
('I think, therefore I am.', 'Je pense, donc je suis.', 'B2', 'quotes'),
('Love is composed of a single soul inhabiting two bodies.', 'L''amour est composé d''une seule âme habitant deux corps.', 'B2', 'quotes'),
('There is nothing either good or bad, but thinking makes it so.', 'Rien n''est bon ou mauvais en soi, c''est la pensée qui le rend tel.', 'C1', 'literature'),
('The early bird catches the worm.', 'L''oiseau matinal attrape le ver.', 'A1', 'proverbs'),
('Actions speak louder than words.', 'Les actions parlent plus fort que les mots.', 'A2', 'proverbs'),
('Where there is a will, there is a way.', 'Là où il y a une volonté, il y a un chemin.', 'A2', 'proverbs'),
('A friend in need is a friend indeed.', 'Un ami dans le besoin est un ami pour de vrai.', 'A2', 'proverbs'),
('Better late than never.', 'Mieux vaut tard que jamais.', 'A1', 'proverbs'),
('When one door closes, another opens.', 'Quand une porte se ferme, une autre s''ouvre.', 'A2', 'proverbs'),
('The pen is mightier than the sword.', 'La plume est plus forte que l''épée.', 'B1', 'proverbs'),
('Do not count your chickens before they hatch.', 'Ne compte pas tes poussins avant qu''ils ne soient éclos.', 'B2', 'proverbs'),
('It is a truth universally acknowledged that a single man in possession of a good fortune must be in want of a wife.', 'C''est une vérité universellement reconnue qu''un célibataire pourvu d''une belle fortune doit nécessairement rechercher une femme.', 'C1', 'literature'),
('Call me Ishmael.', 'Appelle-moi Ishmael.', 'A2', 'literature'),
('It was a bright cold day in April, and the clocks were striking thirteen.', 'C''était une journée fraîche et ensoleillée d''avril, et les horloges sonnaient treize heures.', 'B2', 'literature'),
('All happy families are alike; each unhappy family is unhappy in its own way.', 'Toutes les familles heureuses se ressemblent ; chaque famille malheureuse est malheureuse à sa façon.', 'C1', 'literature'),
('The man in black fled across the desert, and the gunslinger followed.', 'L''homme en noir s''enfuit à travers le désert, et le pistolier le suivit.', 'B2', 'literature'),
('So we beat on, boats against the current, borne back ceaselessly into the past.', 'Ainsi nous frappons, des bateaux contre le courant, portés sans cesse vers le passé.', 'C1', 'literature'),
('In my younger and more vulnerable years my father gave me some advice.', 'Dans mes années plus jeunes et plus vulnérables, mon père m''a donné quelques conseils.', 'B2', 'literature'),
('It is a far, far better thing that I do, than I have ever done.', 'C''est une bien meilleure chose que je fais que tout ce que j''ai jamais fait.', 'C1', 'literature'),
('The world was so recent that many things lacked names.', 'Le monde était si récent que beaucoup de choses manquaient de noms.', 'B2', 'literature'),
('He who has a why to live can bear almost any how.', 'Celui qui a un pourquoi pour vivre peut supporter presque n''importe quel comment.', 'B2', 'quotes'),
('We are what we repeatedly do. Excellence, then, is not an act, but a habit.', 'Nous sommes ce que nous faisons de manière répétée. L''excellence, c''est donc pas un acte, mais une habitude.', 'B2', 'quotes'),
('The only true wisdom is in knowing you know nothing.', 'La seule vraie sagesse est de savoir que l''on ne sait rien.', 'B1', 'quotes'),
('Knowing yourself is the beginning of all wisdom.', 'Se connaître soi-même est le début de toute sagesse.', 'B1', 'quotes'),
('An investment in knowledge pays the best interest.', 'Un investissement dans la connaissance paie les meilleurs intérêts.', 'B1', 'quotes'),
('Education is the most powerful weapon which you can use to change the world.', 'L''éducation est l''arme la plus puissante que vous puissiez utiliser pour changer le monde.', 'B2', 'quotes'),
('The beautiful thing about learning is that no one can take it away from you.', 'Ce qui est beau dans l''apprentissage, c''est que personne ne peut vous l''enlever.', 'A2', 'quotes'),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Le succès n''est pas définitif, l''échec n''est pas fatal : c''est le courage de continuer qui compte.', 'B2', 'quotes'),
('Do what you can, with what you have, where you are.', 'Faites ce que vous pouvez, avec ce que vous avez, là où vous êtes.', 'A2', 'quotes'),
('Believe you can and you are halfway there.', 'Croyez que vous pouvez et vous êtes à mi-chemin.', 'A2', 'quotes'),
('Everything you can imagine is real.', 'Tout ce que vous pouvez imaginer est réel.', 'A2', 'quotes'),
('Simplicity is the ultimate sophistication.', 'La simplicité est l''ultime sophistication.', 'B1', 'quotes');
