INSERT INTO dictation_sentences (text, translation_fr, difficulty, category) VALUES
-- Travail / Enterprise
('The meeting will take place in the main conference room at three o clock.', 'La réunion aura lieu dans la salle de conférence principale à trois heures.', 'A2', 'travail'),
('Please submit your weekly report to your supervisor by Friday afternoon.', 'Veuillez soumettre votre rapport hebdomadaire à votre superviseur d''ici vendredi après-midi.', 'B1', 'travail'),
('The company has decided to hire five new employees for the marketing department.', 'L''entreprise a décidé d''embaucher cinq nouveaux employés pour le département marketing.', 'B1', 'travail'),
('I would like to schedule a performance review for next Tuesday morning.', 'J''aimerais planifier un entretien d''évaluation pour mardi matin prochain.', 'B1', 'travail'),
('Our team is working on a new project that will launch in the first quarter.', 'Notre équipe travaille sur un nouveau projet qui sera lancé au premier trimestre.', 'B1', 'travail'),
('The deadline for the proposal has been extended to the end of the month.', 'La date limite pour la proposition a été reportée à la fin du mois.', 'B1', 'travail'),
('She was promoted to senior manager after only two years at the company.', 'Elle a été promue au rang de directrice senior après seulement deux ans dans l''entreprise.', 'B2', 'travail'),
('The training session will cover workplace safety and emergency procedures.', 'La session de formation couvrira la sécurité sur le lieu de travail et les procédures d''urgence.', 'B1', 'travail'),
('Employees are entitled to a minimum of twenty-five days of paid leave per year.', 'Les employés ont droit à un minimum de vingt-cinq jours de congé payé par an.', 'B2', 'travail'),
('The human resources department is organising a team-building event next week.', 'Le département des ressources humaines organise un événement de cohésion d''équipe la semaine prochaine.', 'B2', 'travail'),
('We need to improve communication between the different departments of the company.', 'Nous devons améliorer la communication entre les différents départements de l''entreprise.', 'B1', 'travail'),
('The salary package includes health insurance and a retirement plan.', 'Le package salarial comprend une assurance maladie et un plan de retraite.', 'B2', 'travail'),
('He resigned from his position to pursue a career in a different industry.', 'Il a démissionné de son poste pour poursuivre une carrière dans un autre secteur.', 'B2', 'travail'),
('The board of directors approved the budget for the next fiscal year.', 'Le conseil d''administration a approuvé le budget pour le prochain exercice fiscal.', 'B2', 'travail'),
('Remote working has become increasingly popular since the pandemic.', 'Le télétravail est devenu de plus en plus populaire depuis la pandémie.', 'B1', 'travail'),
-- Santé
('It is important to drink at least eight glasses of water every day.', 'Il est important de boire au moins huit verres d''eau chaque jour.', 'A2', 'sante'),
('The doctor recommended a balanced diet and regular exercise.', 'Le médecin a recommandé un régime équilibré et une activité physique régulière.', 'B1', 'sante'),
('You should take your medication with food to avoid stomach pain.', 'Vous devriez prendre votre médicament avec de la nourriture pour éviter les maux d''estomac.', 'B1', 'sante'),
('The hospital is located on the fifth floor of the main building.', 'L''hôpital se trouve au cinquième étage du bâtiment principal.', 'A2', 'sante'),
('Regular check-ups can help detect health problems at an early stage.', 'Les examens réguliers peuvent aider à détecter les problèmes de santé à un stade précoce.', 'B2', 'sante'),
('The nurse will take your blood pressure and temperature before the consultation.', 'L''infirmière prendra votre tension et votre température avant la consultation.', 'B1', 'sante'),
('I have an appointment with the dentist at ten o clock on Wednesday.', 'J''ai rendez-vous chez le dentiste à dix heures mercredi.', 'A2', 'sante'),
('Smoking is prohibited in all public places and hospital grounds.', 'Fumer est interdit dans tous les lieux publics et les terrains d''hôpitaux.', 'B1', 'sante'),
('The pharmacist advised me to rest and drink plenty of fluids.', 'Le pharmacien m''a conseillé de me reposer et de boire beaucoup de liquides.', 'B1', 'sante'),
('Mental health is just as important as physical health.', 'La santé mentale est tout aussi importante que la santé physique.', 'B1', 'sante'),
('The patient was discharged from hospital after three days of observation.', 'Le patient a été autorisé à quitter l''hôpital après trois jours d''observation.', 'B2', 'sante'),
('Wash your hands regularly to prevent the spread of infections.', 'Lavez-vous les mains régulièrement pour prévenir la propagation des infections.', 'A2', 'sante'),
('The surgeon explained the procedure and answered all our questions.', 'Le chirurgien a expliqué la procédure et a répondu à toutes nos questions.', 'B2', 'sante'),
('A healthy lifestyle includes enough sleep and stress management.', 'Un mode de vie sain comprend suffisamment de sommeil et la gestion du stress.', 'B2', 'sante'),
('The vaccination campaign will start next month at all local clinics.', 'La campagne de vaccination commencera le mois prochain dans toutes les cliniques locales.', 'B2', 'sante'),
-- Éducation
('The students are required to submit their assignments by the end of the week.', 'Les étudiants doivent soumettre leurs devoirs d''ici la fin de la semaine.', 'B1', 'education'),
('The university offers a wide range of courses in science and humanities.', 'L''université propose un large éventail de cours en sciences et en sciences humaines.', 'B2', 'education'),
('She passed her final exam with the highest grade in her class.', 'Elle a réussi son examen final avec la meilleure note de sa classe.', 'B1', 'education'),
('The teacher encouraged the students to participate actively in class discussions.', 'Le professeur a encouragé les étudiants à participer activement aux discussions en classe.', 'B2', 'education'),
('The library is open from nine in the morning until eight in the evening.', 'La bibliothèque est ouverte de neuf heures du matin jusqu''à huit heures du soir.', 'A2', 'education'),
-- Technologie
('Make sure you save your work before closing the application.', 'Assurez-vous d''enregistrer votre travail avant de fermer l''application.', 'A2', 'technologie'),
('The software update will be available for download next Monday.', 'La mise à jour du logiciel sera disponible au téléchargement lundi prochain.', 'B1', 'technologie'),
('Please enter your username and password to access your account.', 'Veuillez saisir votre nom d''utilisateur et votre mot de passe pour accéder à votre compte.', 'B1', 'technologie'),
('The IT department is working on resolving the network issue.', 'Le département informatique travaille à la résolution du problème de réseau.', 'B1', 'technologie'),
('You can share files with your colleagues using the cloud storage system.', 'Vous pouvez partager des fichiers avec vos collègues en utilisant le système de stockage cloud.', 'B2', 'technologie'),
-- Vie quotidienne
('The supermarket is closed on Sundays but open on public holidays.', 'Le supermarché est fermé le dimanche mais ouvert les jours fériés.', 'A2', 'vie_quotidienne'),
('I usually go to the gym three times a week after work.', 'Je vais généralement à la salle de sport trois fois par semaine après le travail.', 'B1', 'vie_quotidienne'),
('The train arrives at platform number three in approximately ten minutes.', 'Le train arrive sur le quai numéro trois dans environ dix minutes.', 'B1', 'vie_quotidienne'),
('Remember to lock the door and turn off the lights before you leave.', 'N''oubliez pas de fermer la porte à clé et d''éteindre les lumières avant de partir.', 'A2', 'vie_quotidienne'),
('The weather forecast says it will be cloudy with a chance of rain tomorrow.', 'Les prévisions météo annoncent un temps nuageux avec risque de pluie demain.', 'B1', 'vie_quotidienne');
