INSERT INTO translation_exercises (title, source, translation, difficulty, category, word_count) VALUES
-- Travail
('Entretien d''embauche', 'I have a job interview next Monday. I need to prepare answers about my experience and my qualifications. I also want to ask questions about the company culture and the team I would be working with.', 'J''ai un entretien d''embauche lundi prochain. Je dois préparer des réponses sur mon expérience et mes qualifications. Je veux aussi poser des questions sur la culture de l''entreprise et l''équipe avec laquelle je travaillerais.', 'medium', 'travail', 38),
('Réunion de service', 'The manager reminded everyone that the weekly meeting has been moved to Thursday afternoon. All team members must bring their progress reports and be ready to discuss the current project status.', 'Le manager a rappelé à tous que la réunion hebdomadaire a été déplacée à jeudi après-midi. Tous les membres de l''équipe doivent apporter leurs rapports d''avancement et être prêts à discuter du statut actuel du projet.', 'medium', 'travail', 33),
('Demande de congé', 'I would like to request two weeks of annual leave from the fifteenth of July to the twenty-eighth. I have already discussed this with my supervisor and arranged for a colleague to cover my tasks during my absence.', 'Je voudrais demander deux semaines de congé annuel du quinze juillet au vingt-huit. J''ai déjà discuté de cela avec mon superviseur et organisé qu''un collègue couvre mes tâches pendant mon absence.', 'medium', 'travail', 38),
('Rapport d''activité', 'This quarterly report shows a fifteen percent increase in sales compared to the same period last year. The marketing campaign launched in March has been particularly effective in attracting new customers.', 'Ce rapport trimestriel montre une augmentation de quinze pour cent des ventes par rapport à la même période l''année dernière. La campagne marketing lancée en mars a été particulièrement efficace pour attirer de nouveaux clients.', 'medium', 'travail', 35),
('Formation professionnelle', 'The company is offering a three-day training course on project management techniques. The sessions will be held at the headquarters and all employees are encouraged to register before the end of the week.', 'L''entreprise propose une formation de trois jours sur les techniques de gestion de projet. Les sessions se tiendront au siège social et tous les employés sont encouragés à s''inscrire avant la fin de la semaine.', 'medium', 'travail', 34),
('Télétravail', 'Working from home has become the new normal for many employees. While some prefer the flexibility and the time saved on commuting, others miss the social interaction and the clear boundary between work and personal life.', 'Le télétravail est devenu la nouvelle norme pour de nombreux employés. Alors que certains préfèrent la flexibilité et le temps gagné sur les trajets, d''autres regrettent l''interaction sociale et la frontière claire entre vie professionnelle et vie privée.', 'hard', 'travail', 37),
('Négociation salariale', 'During the annual review, I presented my achievements and the additional responsibilities I have taken on since my promotion. I requested a salary increase of ten percent to reflect my contribution to the team.', 'Lors de l''évaluation annuelle, j''ai présenté mes réalisations et les responsabilités supplémentaires que j''ai prises depuis ma promotion. J''ai demandé une augmentation de salaire de dix pour cent pour refléter ma contribution à l''équipe.', 'hard', 'travail', 36),
-- Santé
('Visite médicale', 'During the consultation, the doctor asked me about my symptoms, checked my blood pressure, and prescribed a blood test. She advised me to get more rest and to come back if the symptoms persist after a week.', 'Pendant la consultation, le médecin m''a demandé mes symptômes, a vérifié ma tension et a prescrit une prise de sang. Elle m''a conseillé de me reposer davantage et de revenir si les symptômes persistent après une semaine.', 'medium', 'sante', 37),
('Urgences', 'The emergency department operates twenty-four hours a day, seven days a week. Patients are treated according to the severity of their condition, which means that waiting times can vary significantly.', 'Le service des urgences fonctionne vingt-quatre heures par jour, sept jours sur sept. Les patients sont traités selon la gravité de leur état, ce qui signifie que les temps d''attente peuvent varier considérablement.', 'hard', 'sante', 33),
('Mode de vie sain', 'A healthy lifestyle requires a combination of regular physical activity, a balanced diet rich in fruits and vegetables, sufficient sleep, and effective stress management techniques such as meditation or yoga.', 'Un mode de vie sain nécessite une combinaison d''activité physique régulière, d''une alimentation équilibrée riche en fruits et légumes, d''un sommeil suffisant et de techniques efficaces de gestion du stress comme la méditation ou le yoga.', 'hard', 'sante', 34),
('Prévention', 'Preventive healthcare includes regular screenings, vaccinations, and routine check-ups. Early detection of diseases significantly improves treatment outcomes and reduces healthcare costs for both patients and society.', 'La prévention sanitaire comprend les dépistages réguliers, les vaccinations et les examens de routine. La détection précoce des maladies améliore considérablement les résultats des traitements et réduit les coûts de santé pour les patients et la société.', 'hard', 'sante', 32),
('À la pharmacie', 'I went to the pharmacy to pick up my prescription. The pharmacist explained how to take the medication and warned me about possible side effects such as drowsiness and dry mouth.', 'Je suis allé à la pharmacie pour récupérer mon ordonnance. Le pharmacien a expliqué comment prendre le médicament et m''a averti des effets secondaires possibles tels que la somnolence et la sécheresse de la bouche.', 'medium', 'sante', 33),
-- Éducation
('Inscription à l''université', 'Students who wish to enrol in the programme must submit their application before the thirty-first of May. Required documents include a motivation letter, academic transcripts, and two letters of recommendation.', 'Les étudiants qui souhaitent s''inscrire au programme doivent soumettre leur candidature avant le trente et un mai. Les documents requis incluent une lettre de motivation, les relevés de notes et deux lettres de recommandation.', 'hard', 'education', 33),
('Salle de classe', 'The teacher asked the students to open their textbooks to page forty-seven and read the first paragraph aloud. She then divided the class into small groups to discuss the main ideas of the chapter.', 'Le professeur a demandé aux étudiants d''ouvrir leur manuel à la page quarante-sept et de lire le premier paragraphe à voix haute. Elle a ensuite divisé la classe en petits groupes pour discuter des idées principales du chapitre.', 'medium', 'education', 36),
('Examen final', 'The final examination will consist of three parts: a written essay, a multiple-choice section, and an oral presentation. Students are allowed to use a dictionary during the written portion of the exam.', 'L''examen final comportera trois parties : une dissertation écrite, une section à choix multiples et une présentation orale. Les étudiants sont autorisés à utiliser un dictionnaire pendant la partie écrite de l''examen.', 'medium', 'education', 35),
-- Technologie
('Cybersécurité', 'All employees must use strong passwords containing at least twelve characters, including uppercase letters, numbers, and special symbols. Passwords should be changed every ninety days and never shared with colleagues.', 'Tous les employés doivent utiliser des mots de passe forts contenant au moins douze caractères, incluant des majuscules, des chiffres et des symboles spéciaux. Les mots de passe doivent être changés tous les quatre-vingt-dix jours et jamais partagés avec des collègues.', 'hard', 'technologie', 33),
('Nouveau logiciel', 'The IT department has installed a new project management tool on all company computers. A training session will be organised next Wednesday to help employees get familiar with the interface and the main features.', 'Le département informatique a installé un nouvel outil de gestion de projet sur tous les ordinateurs de l''entreprise. Une session de formation sera organisée mercredi prochain pour aider les employés à se familiariser avec l''interface et les principales fonctionnalités.', 'medium', 'technologie', 35),
('Problème technique', 'My computer crashed while I was working on an important presentation. I lost about two hours of work because the file had not been saved automatically. I contacted the support team and they are trying to recover the data.', 'Mon ordinateur a planté alors que je travaillais sur une présentation importante. J''ai perdu environ deux heures de travail car le fichier n''avait pas été enregistré automatiquement. J''ai contacté l''équipe de support et ils essaient de récupérer les données.', 'medium', 'technologie', 38);
