INSERT INTO dictation_sentences (text, translation_fr, difficulty, category) VALUES
-- Réservation
('I would like to book a single room with breakfast for three nights.', 'Je voudrais réserver une chambre simple avec petit-déjeuner pour trois nuits.', 'A2', 'voyage'),
('Do you have any rooms available with a view of the sea?', 'Avez-vous des chambres disponibles avec vue sur la mer ?', 'A2', 'voyage'),
('The reservation is confirmed for the fifteenth of August.', 'La réservation est confirmée pour le quinze août.', 'A2', 'voyage'),
('I need to cancel my booking because my flight has been cancelled.', 'Je dois annuler ma réservation parce que mon vol a été annulé.', 'B1', 'voyage'),
('Is there a discount for booking more than five nights in advance?', 'Y a-t-il une réduction pour une réservation de plus de cinq nuits à l''avance ?', 'B1', 'voyage'),
('The total cost includes taxes and a daily cleaning fee.', 'Le coût total comprend les taxes et des frais de nettoyage quotidiens.', 'B1', 'voyage'),
('Can I pay the deposit with a credit card or do you require cash?', 'Puis-je payer le dépôt avec une carte de crédit ou exigez-vous du liquide ?', 'B1', 'voyage'),
('Your booking reference number is seven eight nine four five.', 'Votre numéro de référence de réservation est sept huit neuf quatre cinq.', 'A2', 'voyage'),
-- Guichet / Aéroport
('Where is the check-in desk for flight BA two four five?', 'Où se trouve le comptoir d''enregistrement pour le vol BA deux quatre cinq ?', 'A2', 'voyage'),
('How many bags can I check in for this flight?', 'Combien de bagages puis-je enregistrer pour ce vol ?', 'A2', 'voyage'),
('Your boarding gate is number twenty-two and boarding starts at six forty-five.', 'Votre porte d''embarquement est le numéro vingt-deux et l''embarquement commence à six heures quarante-cinq.', 'B1', 'voyage'),
('Please have your passport and boarding pass ready for inspection.', 'Veuillez préparer votre passeport et votre carte d''embarquement pour l''inspection.', 'B1', 'voyage'),
('The flight has been delayed by two hours due to bad weather conditions.', 'Le vol a été retardé de deux heures en raison des mauvaises conditions météorologiques.', 'B1', 'voyage'),
('Is this bag within the weight limit for carry-on luggage?', 'Ce sac est-il dans la limite de poids pour les bagages à main ?', 'B1', 'voyage'),
('I would like an aisle seat near the front of the plane if possible.', 'Je voudrais un siège côté couloir près de l''avant de l''avion si possible.', 'B1', 'voyage'),
('You need to go to terminal three for international departures.', 'Vous devez aller au terminal trois pour les départs internationaux.', 'B1', 'voyage'),
('The baggage claim area is on the ground floor next to the exit.', 'La zone de récupération des bagages se trouve au rez-de-chaussée à côté de la sortie.', 'B1', 'voyage'),
('Can I change my flight to an earlier time tomorrow morning?', 'Puis-je changer mon vol pour un horaire plus tôt demain matin ?', 'B1', 'voyage'),
-- Gare / Train
('What time does the next train to Manchester leave?', 'À quelle heure part le prochain train pour Manchester ?', 'A2', 'voyage'),
('I would like a return ticket to Edinburgh, please.', 'Je voudrais un billet aller-retour pour Édimbourg, s''il vous plaît.', 'A2', 'voyage'),
('Which platform does the train to London depart from?', 'De quel quai le train pour Londres part-il ?', 'A2', 'voyage'),
('The journey takes approximately two hours and thirty minutes.', 'Le trajet dure environ deux heures et trente minutes.', 'B1', 'voyage'),
('Is there a direct train or do I need to change?', 'Y a-t-il un train direct ou dois-je changer ?', 'A2', 'voyage'),
('You can buy your ticket at the machine or at the ticket office.', 'Vous pouvez acheter votre billet au distributeur ou au guichet.', 'B1', 'voyage'),
('The last train leaves at eleven forty-five in the evening.', 'Le dernier train part à onze heures quarante-cinq du soir.', 'B1', 'voyage'),
('Please validate your ticket before boarding the train.', 'Veuillez valider votre billet avant de monter dans le train.', 'B1', 'voyage'),
-- Hôtel / Accueil
('What time is check-out at this hotel?', 'À quelle heure est le départ de cet hôtel ?', 'A2', 'voyage'),
('Is breakfast included in the price of the room?', 'Le petit-déjeuner est-il inclus dans le prix de la chambre ?', 'A2', 'voyage'),
('Could you call a taxi to take me to the airport?', 'Pourriez-vous appeler un taxi pour m''emmener à l''aéroport ?', 'B1', 'voyage'),
('The wifi password is written on the key card holder.', 'Le mot de passe wifi est écrit sur le porte-cartes de la clé.', 'B1', 'voyage'),
('Is there a gym and a swimming pool in the hotel?', 'Y a-t-il une salle de sport et une piscine dans l''hôtel ?', 'A2', 'voyage'),
('My room key is not working. Could I get a new one?', 'La clé de ma chambre ne fonctionne pas. Pourrais-je en avoir une nouvelle ?', 'B1', 'voyage'),
('Could I have a late check-out at two o clock please?', 'Pourrais-je avoir un départ tardif à deux heures s''il vous plaît ?', 'B1', 'voyage'),
('The air conditioning is not working properly in my room.', 'La climatisation ne fonctionne pas correctement dans ma chambre.', 'B1', 'voyage'),
('Is there a restaurant nearby that you would recommend?', 'Y a-t-il un restaurant à proximité que vous recommanderiez ?', 'B1', 'voyage'),
-- Demander son chemin
('Excuse me, could you tell me how to get to the nearest tube station?', 'Excusez-moi, pourriez-vous me dire comment aller à la station de métro la plus proche ?', 'B1', 'voyage'),
('Is the museum within walking distance from here?', 'Le musée est-il à distance de marche d''ici ?', 'B1', 'voyage'),
('Turn left at the traffic lights and go straight for two hundred metres.', 'Tournez à gauche au feu et allez tout droit pendant deux cents mètres.', 'B1', 'voyage'),
('The bus stop is just around the corner next to the pharmacy.', 'L''arrêt de bus est juste au coin à côté de la pharmacie.', 'B1', 'voyage'),
('You need to take the second exit at the roundabout.', 'Vous devez prendre la deuxième sortie au rond-point.', 'B1', 'voyage'),
('How long does it take to walk to the city centre?', 'Combien de temps faut-il pour aller au centre-ville à pied ?', 'A2', 'voyage'),
('The tourist information office is located in the main square.', 'Le bureau d''information touristique se trouve sur la place principale.', 'B1', 'voyage'),
('Is this the right bus for the national museum?', 'Est-ce le bon bus pour le musée national ?', 'A2', 'voyage'),
('You should take the underground and get off at the fifth stop.', 'Vous devriez prendre le métro et descendre au cinquième arrêt.', 'B1', 'voyage'),
('The cathedral is open to visitors from nine until six every day.', 'La cathédrale est ouverte aux visiteurs de neuf heures à six heures tous les jours.', 'B1', 'voyage');
