-- Phrasal Verbs from Vocable Anglais Mars 2025 (p10: Daily Life) & Juillet 2025 (p10: Travel & Movement)
INSERT OR IGNORE INTO phrasal_verbs (verb, particle, meaning, example, level) VALUES
-- Daily Life (Mars 2025, p10)
('wake', 'up', 'se réveiller', 'I wake up at seven every morning.', 'beginner'),
('get', 'up', 'se lever', 'She gets up early to go jogging.', 'beginner'),
('look', 'after', 's''occuper de', 'Can you look after my cat while I am away?', 'intermediate'),
('give', 'up', 'abandonner, arrêter', 'He gave up smoking last year.', 'intermediate'),
('carry', 'on', 'continuer', 'Please carry on with your work.', 'intermediate'),
('put', 'off', 'remettre à plus tard, repousser', 'They put off the meeting until next week.', 'intermediate'),
('turn', 'out', 'se révéler, s''avérer', 'It turned out to be a great success.', 'advanced'),
('figure', 'out', 'comprendre, résoudre', 'I can''t figure out how to use this app.', 'intermediate'),
('bring', 'up', 'élever, soulever (un sujet)', 'She was brought up by her grandparents.', 'intermediate'),
('run', 'out of', 'épuiser, ne plus avoir', 'We have run out of milk.', 'intermediate'),
-- Travel & Movement (Juillet 2025, p10)
('check', 'in', 'enregistrer (à l''hôtel ou à l''aéroport)', 'I need to check in at the hotel before six o''clock.', 'beginner'),
('check', 'out', 'quitter (l''hôtel), régler', 'We must check out before eleven in the morning.', 'beginner'),
('set', 'off', 'partir en voyage', 'We set off early to avoid the traffic.', 'intermediate'),
('look', 'around', 'regarder autour, visiter', 'We had a few hours to look around the city.', 'beginner'),
('stop', 'off', 'faire une escale', 'We stopped off in Paris on the way to Rome.', 'intermediate'),
('look', 'round', 'visiter, faire le tour', 'Let''s look round the museum before lunch.', 'intermediate'),
('head', 'for', 'se diriger vers', 'We are heading for the coast.', 'intermediate'),
('touch', 'down', 'atterrir', 'The plane touched down at midnight.', 'intermediate'),
('take', 'off', 'décoller', 'The flight took off thirty minutes late.', 'beginner'),
('get', 'in', 'arriver (à destination)', 'What time does the train get in?', 'beginner'),
('get', 'around', 'se déplacer, circuler', 'It is easy to get around by bus.', 'intermediate'),
('check', 'into', 's''enregistrer à (l''hôtel)', 'We checked into a small hotel near the station.', 'intermediate'),
('book', 'in', 'réserver, s''enregistrer', 'I booked in at the Grand Hotel.', 'intermediate'),
('pull', 'in', 'arriver (train, bus)', 'The train pulled in at exactly three o''clock.', 'intermediate'),
('set', 'out', 'partir, se mettre en route', 'They set out on their journey at dawn.', 'intermediate'),
('look', 'out for', 'faire attention à', 'Look out for pickpockets in crowded areas.', 'intermediate'),
('hold', 'up', 'retarder', 'The storm held up our flight for two hours.', 'intermediate'),
('go', 'back', 'retourner', 'I would love to go back to Italy one day.', 'beginner'),
('look', 'up', 'chercher (une information)', 'I looked up the hotel on the Internet.', 'beginner'),
('find', 'one''s way', 'se repérer, trouver son chemin', 'We lost our way and had to ask for directions.', 'intermediate');
