-- Translation exercises extracted from Vocable Anglais articles (Mars & Juillet 2025)
-- Source: Bilingual articles from News Digest pages

INSERT INTO translation_exercises (title, source, translation, difficulty, category, word_count) VALUES
-- Mars 2025 - p03: AI in Healthcare: A New Era
('IA et santé', 'Artificial intelligence is revolutionising the field of healthcare, offering new possibilities for diagnosis and treatment. AI-powered tools can now analyse medical images with remarkable precision.', 'L''intelligence artificielle révolutionne le domaine de la santé, offrant de nouvelles possibilités pour le diagnostic et le traitement. Les outils alimentés par l''IA peuvent désormais analyser des images médicales avec une précision remarquable.', 'hard', 'technologie', 28),
('IA et confidentialité', 'However, concerns remain about data privacy and the need for human oversight in medical decision-making. Patients must be informed when AI is used in their care.', 'Cependant, des préoccupations subsistent quant à la confidentialité des données et à la nécessité d''une supervision humaine dans les décisions médicales. Les patients doivent être informés lorsque l''IA est utilisée dans leur traitement.', 'hard', 'technologie', 27),
-- Mars 2025 - p04: Climate Policy: Global Efforts
('Sommet climatique', 'World leaders gathered at the climate summit to discuss ambitious targets for reducing greenhouse gas emissions. Many countries have pledged to achieve carbon neutrality by twenty-fifty.', 'Les dirigeants du monde entier se sont réunis au sommet climatique pour discuter d''objectifs ambitieux de réduction des émissions de gaz à effet de serre. De nombreux pays se sont engagés à atteindre la neutralité carbone d''ici 2050.', 'hard', 'environnement', 27),
('Énergies renouvelables', 'The transition to clean energy is accelerating, but experts warn that more action is needed to limit global warming. Investing in renewable energy is essential for a sustainable future.', 'La transition vers les énergies propres s''accélère, mais les experts avertissent que des actions supplémentaires sont nécessaires pour limiter le réchauffement climatique. Investir dans les énergies renouvelables est essentiel pour un avenir durable.', 'hard', 'environnement', 29),
-- Mars 2025 - p05: Space Exploration: The Next Frontier
('Mission vers Mars', 'The new space mission aims to send astronauts to Mars within the next decade, marking a new era in space exploration. Space agencies are developing advanced technologies for this purpose.', 'La nouvelle mission spatiale vise à envoyer des astronautes sur Mars dans la prochaine décennie, marquant une nouvelle ère dans l''exploration spatiale. Les agences spatiales développent des technologies avancées à cet effet.', 'hard', 'science', 29),
('L''eau sur Mars', 'The discovery of water on Mars has raised hopes that one day humans could colonise the red planet. Scientists are studying the possibility of sustaining human life in extreme environments.', 'La découverte d''eau sur Mars a suscité l''espoir qu''un jour, les humains pourraient coloniser la planète rouge. Les scientifiques étudient la possibilité de maintenir la vie humaine dans des environnements extrêmes.', 'hard', 'science', 29),
-- Mars 2025 - p06: European Politics: Unity and Challenges
('Défis européens', 'The European Union faces new challenges as member states debate future policies on migration and economic reform. The recent elections have shifted the balance of power within the union.', 'L''Union européenne fait face à de nouveaux défis alors que les États membres débattent des futures politiques sur la migration et la réforme économique. Les récentes élections ont modifié l''équilibre des pouvoirs au sein de l''union.', 'hard', 'politique', 28),
-- Juillet 2025 - p03: Remote Work Revolution
('Télétravail', 'The shift towards remote work has transformed the traditional office, with many companies adopting hybrid models that combine home and office working.', 'Le passage au télétravail a transformé le bureau traditionnel, de nombreuses entreprises adoptant des modèles hybrides qui combinent travail à domicile et travail au bureau.', 'medium', 'travail', 23),
('Flexibilité et cohésion', 'Employees appreciate the flexibility of working from home, but some miss the social interaction of the office. Studies show that remote workers are often more productive, but maintaining team cohesion remains a challenge.', 'Les employés apprécient la flexibilité du télétravail, mais certains regrettent les interactions sociales du bureau. Des études montrent que les télétravailleurs sont souvent plus productifs, mais maintenir la cohésion d''équipe reste un défi.', 'hard', 'travail', 33),
-- Juillet 2025 - p04: Olympic Games: Paris Legacy
('Héritage olympique', 'The Olympic Games in Paris left a lasting legacy, inspiring a new generation of athletes and promoting sports participation. The infrastructure built for the games will be used by local communities for years to come.', 'Les Jeux Olympiques de Paris ont laissé un héritage durable, inspirant une nouvelle génération d''athlètes et promouvant la participation sportive. Les infrastructures construites pour les Jeux seront utilisées par les communautés locales pendant des années.', 'hard', 'sport', 33),
-- Juillet 2025 - p05: Digital Education: Learning Beyond Classrooms
('Éducation numérique', 'Digital technology has opened up new possibilities for education, allowing students to learn beyond the traditional classroom. Online platforms offer interactive courses that adapt to each student''s pace and learning style.', 'La technologie numérique a ouvert de nouvelles possibilités pour l''éducation, permettant aux élèves d''apprendre au-delà de la salle de classe traditionnelle. Les plateformes en ligne proposent des cours interactifs qui s''adaptent au rythme et au style d''apprentissage de chaque élève.', 'hard', 'education', 33),
('Fracture numérique', 'However, the digital divide remains a challenge, as not all students have access to the necessary technology. Schools and governments must work together to bridge this gap.', 'Cependant, la fracture numérique reste un défi, car tous les élèves n''ont pas accès à la technologie nécessaire. Les écoles et les gouvernements doivent travailler ensemble pour combler cette lacune.', 'medium', 'education', 27),
-- Juillet 2025 - p06: Sustainable Tourism: Traveling Responsibly
('Tourisme durable', 'Sustainable tourism aims to minimise the environmental impact of travel while supporting local communities. Travellers are increasingly choosing eco-friendly accommodations and transportation options.', 'Le tourisme durable vise à minimiser l''impact environnemental des voyages tout en soutenant les communautés locales. Les voyageurs choisissent de plus en plus des hébergements et des options de transport respectueux de l''environnement.', 'hard', 'voyage', 27),
('Surfréquentation touristique', 'Popular destinations are implementing measures to limit overcrowding and protect natural resources. Visitors are encouraged to respect local cultures and traditions during their stay.', 'Les destinations populaires mettent en place des mesures pour limiter la surfréquentation et protéger les ressources naturelles. Les visiteurs sont encouragés à respecter les cultures et les traditions locales pendant leur séjour.', 'medium', 'voyage', 25);
