-- Dictation sentences extracted from Vocable Anglais Mars 2025 (pages 13-20)
-- Source: Bilingual articles (The Power of Music, Social Media and Mental Health, The Art of Conversation, Volunteering)

INSERT OR IGNORE INTO dictation_sentences (text, translation_fr, difficulty, category) VALUES
-- Mars 2025 - p13: The Power of Music
('Music is a universal language that transcends cultural and linguistic barriers, connecting people across the globe.', 'La musique est un langage universel qui transcende les barrières culturelles et linguistiques, connectant les gens à travers le monde.', 'B2', 'culture'),
('Studies have shown that listening to music can reduce stress, lower blood pressure and improve overall mental health.', 'Des études ont montré qu''écouter de la musique peut réduire le stress, abaisser la tension artérielle et améliorer la santé mentale globale.', 'B2', 'santé'),
('Music therapy is increasingly used in hospitals and care homes to help patients recover from trauma and manage pain.', 'La musicothérapie est de plus en plus utilisée dans les hôpitaux et les maisons de retraite pour aider les patients à se remettre d''un traumatisme et à gérer la douleur.', 'B2', 'santé'),
-- Mars 2025 - p14: The Power of Music (continued)
('Learning to play a musical instrument can enhance cognitive abilities, boost creativity and improve memory.', 'Apprendre à jouer d''un instrument de musique peut améliorer les capacités cognitives, stimuler la créativité et améliorer la mémoire.', 'B2', 'education'),
('Streaming services have revolutionised the way we discover and listen to music, giving access to millions of songs.', 'Les services de streaming ont révolutionné la façon dont nous découvrons et écoutons la musique, donnant accès à des millions de chansons.', 'B2', 'technologie'),
('Live concerts create a unique connection between artists and audiences, fostering a sense of community and shared experience.', 'Les concerts en direct créent une connexion unique entre les artistes et le public, favorisant un sentiment de communauté et d''expérience partagée.', 'B2', 'culture'),
-- Mars 2025 - p16: Social Media and Mental Health
('Social media platforms have transformed the way we communicate, share information and connect with others.', 'Les plateformes de réseaux sociaux ont transformé la façon dont nous communiquons, partageons des informations et nous connectons avec les autres.', 'B2', 'technologie'),
('Excessive use of social media has been linked to increased anxiety, depression and low self-esteem among young people.', 'L''utilisation excessive des réseaux sociaux a été associée à une augmentation de l''anxiété, de la dépression et d''une faible estime de soi chez les jeunes.', 'B2', 'santé'),
('Cyberbullying has become a serious problem in schools, with devastating effects on victims'' mental wellbeing.', 'Le cyberharcèlement est devenu un problème grave dans les écoles, avec des effets dévastateurs sur le bien-être mental des victimes.', 'B2', 'societe'),
('Experts recommend setting limits on screen time and taking regular breaks from social media to protect mental health.', 'Les experts recommandent de fixer des limites au temps d''écran et de faire des pauses régulières des réseaux sociaux pour protéger la santé mentale.', 'B2', 'santé'),
-- Mars 2025 - p18: The Art of Conversation
('The art of conversation is a valuable skill that can be learned and perfected with practice and patience.', 'L''art de la conversation est une compétence précieuse qui peut s''apprendre et se perfectionner avec de la pratique et de la patience.', 'B2', 'societe'),
('Active listening is essential for meaningful communication, requiring full attention and genuine interest in the speaker.', 'L''écoute active est essentielle pour une communication significative, exigeant une attention totale et un intérêt sincère pour l''interlocuteur.', 'B2', 'societe'),
('Open-ended questions encourage deeper and more engaging conversations, allowing the other person to express themselves fully.', 'Les questions ouvertes encouragent des conversations plus profondes et plus engageantes, permettant à l''autre personne de s''exprimer pleinement.', 'B2', 'societe'),
('In the age of smartphones, face-to-face conversation is becoming increasingly rare, replaced by text messages and emojis.', 'À l''ère des smartphones, la conversation en face à face devient de plus en plus rare, remplacée par les SMS et les émojis.', 'B2', 'societe'),
-- Mars 2025 - p20: Volunteering: Giving Back
('Volunteering is a rewarding way to give back to the community and make a positive difference in people''s lives.', 'Le bénévolat est un moyen gratifiant de redonner à la communauté et de faire une différence positive dans la vie des gens.', 'B2', 'societe'),
('Many charitable organisations rely heavily on volunteers to carry out their vital work in local communities.', 'De nombreuses organisations caritatives dépendent fortement des bénévoles pour accomplir leur travail vital dans les communautés locales.', 'B2', 'societe'),
('Volunteering can help you develop new skills, gain valuable experience and build a strong professional network.', 'Le bénévolat peut vous aider à développer de nouvelles compétences, à acquérir une expérience précieuse et à construire un solide réseau professionnel.', 'B2', 'travail'),
('Studies show that people who volunteer regularly report higher levels of happiness and life satisfaction.', 'Des études montrent que les personnes qui font du bénévolat régulièrement signalent des niveaux plus élevés de bonheur et de satisfaction de vie.', 'B2', 'societe'),
('From environmental projects to food banks, there are countless ways to get involved and contribute to society.', 'Des projets environnementaux aux banques alimentaires, il existe d''innombrables façons de s''impliquer et de contribuer à la société.', 'B2', 'societe');
