-- Translation exercises extracted from Vocable Anglais Mars 2025 (pages 13-20)
-- Source: Bilingual articles (The Power of Music, Social Media and Mental Health, The Art of Conversation, Volunteering)

INSERT OR IGNORE INTO translation_exercises (title, source, translation, difficulty, category, word_count) VALUES
-- Mars 2025 - p13-14: The Power of Music
('Le pouvoir de la musique', 'Music is a universal language that transcends cultural and linguistic barriers, connecting people across the globe. Studies have shown that listening to music can reduce stress, lower blood pressure and improve overall mental health.', 'La musique est un langage universel qui transcende les barrières culturelles et linguistiques, connectant les gens à travers le monde. Des études ont montré qu''écouter de la musique peut réduire le stress, abaisser la tension artérielle et améliorer la santé mentale globale.', 'hard', 'culture', 33),
('Musicothérapie', 'Music therapy is increasingly used in hospitals and care homes to help patients recover from trauma and manage pain. Learning to play a musical instrument can enhance cognitive abilities, boost creativity and improve memory.', 'La musicothérapie est de plus en plus utilisée dans les hôpitaux et les maisons de retraite pour aider les patients à se remettre d''un traumatisme et à gérer la douleur. Apprendre à jouer d''un instrument de musique peut améliorer les capacités cognitives, stimuler la créativité et améliorer la mémoire.', 'hard', 'santé', 33),
('Streaming et concerts', 'Streaming services have revolutionised the way we discover and listen to music, giving access to millions of songs. Live concerts create a unique connection between artists and audiences, fostering a sense of community and shared experience.', 'Les services de streaming ont révolutionné la façon dont nous découvrons et écoutons la musique, donnant accès à des millions de chansons. Les concerts en direct créent une connexion unique entre les artistes et le public, favorisant un sentiment de communauté et d''expérience partagée.', 'hard', 'technologie', 33),
-- Mars 2025 - p16: Social Media and Mental Health
('Réseaux sociaux', 'Social media platforms have transformed the way we communicate, share information and connect with others. Excessive use of social media has been linked to increased anxiety, depression and low self-esteem among young people.', 'Les plateformes de réseaux sociaux ont transformé la façon dont nous communiquons, partageons des informations et nous connectons avec les autres. L''utilisation excessive des réseaux sociaux a été associée à une augmentation de l''anxiété, de la dépression et d''une faible estime de soi chez les jeunes.', 'hard', 'technologie', 33),
('Cyberharcèlement', 'Cyberbullying has become a serious problem in schools, with devastating effects on victims'' mental wellbeing. Experts recommend setting limits on screen time and taking regular breaks from social media to protect mental health.', 'Le cyberharcèlement est devenu un problème grave dans les écoles, avec des effets dévastateurs sur le bien-être mental des victimes. Les experts recommandent de fixer des limites au temps d''écran et de faire des pauses régulières des réseaux sociaux pour protéger la santé mentale.', 'hard', 'societe', 33),
-- Mars 2025 - p18: The Art of Conversation
('L''art de la conversation', 'The art of conversation is a valuable skill that can be learned and perfected with practice and patience. Active listening is essential for meaningful communication, requiring full attention and genuine interest in the speaker.', 'L''art de la conversation est une compétence précieuse qui peut s''apprendre et se perfectionner avec de la pratique et de la patience. L''écoute active est essentielle pour une communication significative, exigeant une attention totale et un intérêt sincère pour l''interlocuteur.', 'hard', 'societe', 33),
('Questions ouvertes', 'Open-ended questions encourage deeper and more engaging conversations, allowing the other person to express themselves fully. Body language also plays a crucial role in how our messages are perceived by others.', 'Les questions ouvertes encouragent des conversations plus profondes et plus engageantes, permettant à l''autre personne de s''exprimer pleinement. Le langage corporel joue également un rôle crucial dans la façon dont nos messages sont perçus par les autres.', 'hard', 'societe', 32),
('Smartphones et conversation', 'In the age of smartphones, face-to-face conversation is becoming increasingly rare, replaced by text messages and emojis. Many people now find it easier to communicate through a screen than in person.', 'À l''ère des smartphones, la conversation en face à face devient de plus en plus rare, remplacée par les SMS et les émojis. Beaucoup de gens trouvent désormais plus facile de communiquer à travers un écran qu''en personne.', 'medium', 'societe', 31),
-- Mars 2025 - p20: Volunteering: Giving Back
('Le bénévolat', 'Volunteering is a rewarding way to give back to the community and make a positive difference in people''s lives. Many charitable organisations rely heavily on volunteers to carry out their vital work in local communities.', 'Le bénévolat est un moyen gratifiant de redonner à la communauté et de faire une différence positive dans la vie des gens. De nombreuses organisations caritatives dépendent fortement des bénévoles pour accomplir leur travail vital dans les communautés locales.', 'hard', 'societe', 33),
('Compétences et bénévolat', 'Volunteering can help you develop new skills, gain valuable experience and build a strong professional network. Studies show that people who volunteer regularly report higher levels of happiness and life satisfaction.', 'Le bénévolat peut vous aider à développer de nouvelles compétences, à acquérir une expérience précieuse et à construire un solide réseau professionnel. Des études montrent que les personnes qui font du bénévolat régulièrement signalent des niveaux plus élevés de bonheur et de satisfaction de vie.', 'hard', 'travail', 32),
('S''impliquer dans la société', 'From environmental projects to food banks, there are countless ways to get involved and contribute to society. Even small acts of kindness can have a significant impact on those around us.', 'Des projets environnementaux aux banques alimentaires, il existe d''innombrables façons de s''impliquer et de contribuer à la société. Même de petits actes de gentillesse peuvent avoir un impact significatif sur ceux qui nous entourent.', 'medium', 'societe', 29);
