-- Dictation sentences extracted from Vocable Anglais Juillet 2025 (pages 13-20)
-- Source: Bilingual articles (The Future of Food, The Art of Public Speaking, Mindfulness and Wellbeing, The Gig Economy)

INSERT OR IGNORE INTO dictation_sentences (text, translation_fr, difficulty, category) VALUES
-- Juillet 2025 - p13: The Future of Food
('The way we produce and consume food is changing rapidly, driven by technological innovation and environmental concerns.', 'La façon dont nous produisons et consommons la nourriture change rapidement, portée par l''innovation technologique et les préoccupations environnementales.', 'B2', 'environnement'),
('Lab-grown meat, also known as cultured meat, could revolutionise the food industry and reduce the environmental impact of livestock farming.', 'La viande cultivée en laboratoire, également appelée viande de culture, pourrait révolutionner l''industrie alimentaire et réduire l''impact environnemental de l''élevage.', 'B2', 'technologie'),
('Plant-based diets are becoming increasingly popular as more people become aware of the environmental and health benefits.', 'Les régimes à base de plantes deviennent de plus en plus populaires à mesure que davantage de personnes prennent conscience des bienfaits environnementaux et sanitaires.', 'B2', 'sante'),
-- Juillet 2025 - p14: The Future of Food (continued)
('Vertical farming uses less water and land than traditional agriculture while producing higher yields in controlled environments.', 'L''agriculture verticale utilise moins d''eau et de terres que l''agriculture traditionnelle tout en produisant des rendements plus élevés dans des environnements contrôlés.', 'B2', 'environnement'),
('Reducing food waste is essential to feed a growing global population and protect the planet for future generations.', 'Réduire le gaspillage alimentaire est essentiel pour nourrir une population mondiale croissante et protéger la planète pour les générations futures.', 'B2', 'environnement'),
('Many restaurants now source their ingredients locally to support regional farmers and reduce their carbon footprint.', 'De nombreux restaurants s''approvisionnent désormais localement pour soutenir les agriculteurs régionaux et réduire leur empreinte carbone.', 'B2', 'environnement'),
-- Juillet 2025 - p16: The Art of Public Speaking
('Public speaking is one of the most common fears, but it is a skill that can be developed with practice and preparation.', 'Prendre la parole en public est l''une des peurs les plus courantes, mais c''est une compétence qui peut être développée avec de la pratique et de la préparation.', 'B2', 'travail'),
('A good speech should have a clear structure: an engaging introduction, a well-organised body and a memorable conclusion.', 'Un bon discours doit avoir une structure claire : une introduction captivante, un développement bien organisé et une conclusion mémorable.', 'B2', 'travail'),
('Body language, eye contact and voice projection are key elements of effective public speaking.', 'Le langage corporel, le contact visuel et la projection de la voix sont des éléments clés d''une prise de parole en public efficace.', 'B2', 'travail'),
-- Juillet 2025 - p17: The Art of Public Speaking (continued)
('Using stories and anecdotes can make your presentation more relatable and help you connect with your audience.', 'Utiliser des histoires et des anecdotes peut rendre votre présentation plus accessible et vous aider à vous connecter avec votre public.', 'B2', 'travail'),
('Practising in front of a mirror or recording yourself can help you identify areas for improvement in your delivery.', 'S''exercer devant un miroir ou s''enregistrer peut vous aider à identifier les points à améliorer dans votre delivery.', 'B2', 'travail'),
('Even experienced speakers feel nervous before a presentation, but they have learned to channel that energy positively.', 'Même les orateurs expérimentés se sentent nerveux avant une présentation, mais ils ont appris à canaliser cette énergie de manière positive.', 'B2', 'travail'),
-- Juillet 2025 - p18: Mindfulness and Wellbeing
('Mindfulness is the practice of being fully present in the moment, aware of your thoughts and surroundings without judgement.', 'La pleine conscience est la pratique d''être pleinement présent dans l''instant, conscient de ses pensées et de son environnement sans jugement.', 'B2', 'sante'),
('Regular mindfulness meditation has been shown to reduce stress, improve focus and enhance emotional regulation.', 'La méditation régulière de pleine conscience s''est révélée réduire le stress, améliorer la concentration et renforcer la régulation émotionnelle.', 'B2', 'sante'),
('Many companies now offer mindfulness programmes to their employees to promote wellbeing and productivity in the workplace.', 'De nombreuses entreprises proposent désormais des programmes de pleine conscience à leurs employés pour favoriser le bien-être et la productivité au travail.', 'B2', 'travail'),
-- Juillet 2025 - p19: Mindfulness and Wellbeing (continued)
('Simple techniques such as deep breathing and body scans can be practised anywhere, even at your desk during a busy workday.', 'Des techniques simples comme la respiration profonde et les scans corporels peuvent être pratiquées n''importe où, même à votre bureau pendant une journée de travail chargée.', 'B2', 'sante'),
('Research suggests that just ten minutes of mindfulness practice per day can have significant benefits for mental health.', 'Des recherches suggèrent que seulement dix minutes de pratique de la pleine conscience par jour peuvent avoir des bienfaits significatifs pour la santé mentale.', 'B2', 'sante'),
('Mindfulness is not about emptying your mind, but rather observing your thoughts without getting caught up in them.', 'La pleine conscience ne consiste pas à vider son esprit, mais plutôt à observer ses pensées sans s''y laisser emprisonner.', 'B2', 'sante'),
-- Juillet 2025 - p20: The Gig Economy
('The gig economy has transformed the labour market, offering flexibility but also creating uncertainty for many workers.', 'L''économie des missions a transformé le marché du travail, offrant de la flexibilité mais créant aussi de l''incertitude pour de nombreux travailleurs.', 'B2', 'travail'),
('Freelancers and independent contractors enjoy the freedom to choose their projects, but they lack job security and benefits.', 'Les freelances et les entrepreneurs indépendants apprécient la liberté de choisir leurs projets, mais ils manquent de sécurité de l''emploi et d''avantages sociaux.', 'B2', 'travail'),
('Ride-sharing and food delivery apps have become symbols of the gig economy, employing millions of workers worldwide.', 'Les applications de covoiturage et de livraison de repas sont devenues les symboles de l''économie des missions, employant des millions de travailleurs dans le monde.', 'B2', 'technologie'),
('Governments are debating how to regulate the gig economy to protect workers while preserving its flexibility and innovation.', 'Les gouvernements débattent de la façon de réglementer l''économie des missions pour protéger les travailleurs tout en préservant sa flexibilité et son innovation.', 'B2', 'societe');
