-- Additional irregular verbs from Bescherelle "Maîtriser la grammaire anglaise"
-- These verbs are NOT already in the database (79 existing verbs checked)
-- Source: Bescherelle irregular verb tables (pages 216-224)

INSERT OR IGNORE INTO irregular_verbs (base, past, past_participle, meaning, example_base, example_past, example_participle, level, created_at)
VALUES
('arise', 'arose', 'arisen', 'survenir, se lever', 'A problem arises during the meeting.', 'A problem arose unexpectedly.', 'A problem has arisen.', 'advanced', strftime('%s', 'now')),
('awake', 'awoke', 'awoken', 'se réveiller', 'I awake at 6 AM every day.', 'I awoke suddenly.', 'I have awoken early.', 'advanced', strftime('%s', 'now')),
('bear', 'bore', 'born/borne', 'porter, supporter, enfanter', 'She bears the responsibility.', 'She bore the pain.', 'She has borne three children.', 'advanced', strftime('%s', 'now')),
('beat', 'beat', 'beaten', 'battre, vaincre', 'He beats the drum.', 'He beat the champion.', 'He has beaten the record.', 'intermediate', strftime('%s', 'now')),
('bend', 'bent', 'bent', 'plier, courber', 'Don''t bend the rules.', 'He bent the wire.', 'He has bent the pipe.', 'intermediate', strftime('%s', 'now')),
('bet', 'bet/betted', 'bet/betted', 'parier', 'I bet you''re right.', 'I bet on the winning horse.', 'I have bet all my money.', 'intermediate', strftime('%s', 'now')),
('bind', 'bound', 'bound', 'lier, relier', 'They bind the books.', 'They bound his hands.', 'They have bound the documents.', 'advanced', strftime('%s', 'now')),
('bite', 'bit', 'bitten', 'mordre', 'The dog bites strangers.', 'The dog bit the postman.', 'The dog has bitten the child.', 'intermediate', strftime('%s', 'now')),
('bleed', 'bled', 'bled', 'saigner, saigner de', 'His wound bleeds.', 'He bled profusely.', 'He has bled a lot.', 'intermediate', strftime('%s', 'now')),
('blow', 'blew', 'blown', 'souffler', 'The wind blows hard.', 'The wind blew all night.', 'The wind has blown the tree down.', 'intermediate', strftime('%s', 'now')),
('breed', 'bred', 'bred', 'élever, se reproduire', 'They breed horses.', 'They bred dogs for years.', 'They have bred champion dogs.', 'advanced', strftime('%s', 'now')),
('broadcast', 'broadcast', 'broadcast', 'diffuser, émettre', 'They broadcast the news daily.', 'They broadcast the event live.', 'They have broadcast the show.', 'advanced', strftime('%s', 'now')),
('burst', 'burst', 'burst', 'éclater, jaillir', 'The pipe bursts.', 'The pipe burst suddenly.', 'The pipe has burst.', 'intermediate', strftime('%s', 'now')),
('cast', 'cast', 'cast', 'lancer, jeter, distribuer', 'She casts the fishing line.', 'She cast the dice.', 'She has cast her vote.', 'advanced', strftime('%s', 'now')),
('cling', 'clung', 'clung', 's''accrocher à', 'The child clings to her mother.', 'The child clung to her mother.', 'The child has clung to her toy.', 'advanced', strftime('%s', 'now')),
('creep', 'crept', 'crept', 'ramper, se faufiler', 'The cat creeps silently.', 'The cat crept up on the mouse.', 'The cat has crept under the bed.', 'advanced', strftime('%s', 'now')),
('deal', 'dealt', 'dealt', 'traiter, distribuer', 'She deals with customers.', 'She dealt the cards.', 'She has dealt with the issue.', 'intermediate', strftime('%s', 'now')),
('dig', 'dug', 'dug', 'creuser', 'They dig a hole.', 'They dug a tunnel.', 'They have dug the garden.', 'intermediate', strftime('%s', 'now')),
('dream', 'dreamed/dreamt', 'dreamed/dreamt', 'rêver', 'I dream every night.', 'I dreamt about you.', 'I have dreamt of this moment.', 'intermediate', strftime('%s', 'now')),
('drink', 'drank', 'drunk', 'boire', 'He drinks coffee every morning.', 'He drank too much wine.', 'He has drunk all the juice.', 'beginner', strftime('%s', 'now')),
('feed', 'fed', 'fed', 'nourrir', 'She feeds the cat.', 'She fed the baby.', 'She has fed the animals.', 'intermediate', strftime('%s', 'now')),
('fight', 'fought', 'fought', 'se battre, lutter', 'They fight for freedom.', 'They fought bravely.', 'They have fought hard.', 'intermediate', strftime('%s', 'now')),
('flee', 'fled', 'fled', 'fuir, s''enfuir', 'The criminals flee the scene.', 'They fled the country.', 'They have fled to safety.', 'advanced', strftime('%s', 'now')),
('forecast', 'forecast', 'forecast', 'prévoir, prédir', 'They forecast the weather.', 'They forecast rain yesterday.', 'They have forecast a storm.', 'advanced', strftime('%s', 'now')),
('forbid', 'forbade', 'forbidden', 'interdire', 'The sign forbids smoking.', 'The teacher forbade talking.', 'Smoking is forbidden here.', 'advanced', strftime('%s', 'now')),
('forecast', 'forecast', 'forecast', 'prévoir', 'Experts forecast growth.', 'They forecast a recession.', 'They have forecast the trend.', 'advanced', strftime('%s', 'now')),
('foresee', 'foresaw', 'foreseen', 'prévoir, anticiper', 'She foresees problems.', 'She foresaw the crisis.', 'She has foreseen the outcome.', 'advanced', strftime('%s', 'now')),
('forgo', 'forwent', 'forgone', 'renoncer à', 'He forgoes dessert.', 'He forwent the opportunity.', 'He has forgone the pleasure.', 'advanced', strftime('%s', 'now')),
('grind', 'ground', 'ground', 'moudre, broyer', 'They grind coffee beans.', 'They ground the wheat.', 'They have ground the spices.', 'advanced', strftime('%s', 'now')),
('hang', 'hung/hanged', 'hung/hanged', 'accrocher, pendre', 'She hangs the picture.', 'She hung the curtains.', 'She has hung the painting.', 'intermediate', strftime('%s', 'now')),
('heave', 'hove/heaved', 'hove/heaved', 'soulever, halter', 'They heave the anchor.', 'They heaved the heavy box.', 'They have heaved the cargo.', 'advanced', strftime('%s', 'now')),
('kneel', 'knelt', 'knelt', 's''agenouiller', 'He kneels to pray.', 'He knelt before the queen.', 'He has knelt in prayer.', 'advanced', strftime('%s', 'now')),
('knit', 'knit/knitted', 'knit/knitted', 'tricoter', 'She knits sweaters.', 'She knitted a scarf.', 'She has knit a blanket.', 'intermediate', strftime('%s', 'now')),
('lean', 'leaned/leant', 'leaned/leant', 'se pencher, s''appuyer', 'She leans on the wall.', 'She leant against the door.', 'She has leant on his support.', 'intermediate', strftime('%s', 'now')),
('leap', 'leapt/leaped', 'leapt/leaped', 'sauter, bondir', 'The cat leaps over the fence.', 'The cat leapt onto the table.', 'The cat has leapt across the gap.', 'advanced', strftime('%s', 'now')),
('learn', 'learned/learnt', 'learned/learnt', 'apprendre', 'Children learn quickly.', 'She learnt French at school.', 'She has learnt a lot.', 'beginner', strftime('%s', 'now')),
('melt', 'melted', 'melted/molten', 'fondre', 'Ice melts in the sun.', 'The snow melted quickly.', 'The metal has melted.', 'intermediate', strftime('%s', 'now')),
('misunderstand', 'misunderstood', 'misunderstood', 'mal comprendre', 'People misunderstand him.', 'She misunderstood the question.', 'She has misunderstood the instructions.', 'advanced', strftime('%s', 'now')),
('overcome', 'overcame', 'overcome', 'vaincre, surmonter', 'She overcomes obstacles.', 'She overcame her fear.', 'She has overcome many challenges.', 'advanced', strftime('%s', 'now')),
('overdo', 'overdid', 'overdone', 'en faire trop', 'He overdoes the exercise.', 'He overdid the decoration.', 'He has overdone the training.', 'advanced', strftime('%s', 'now')),
('overtake', 'overtook', 'overtaken', 'dépasser, doubler', 'The car overtakes the truck.', 'The car overtook the bus.', 'The car has overtaken three vehicles.', 'advanced', strftime('%s', 'now')),
('overthrow', 'overthrew', 'overthrown', 'renverser, renverser (un gouvernement)', 'They overthrow the dictator.', 'They overthrew the regime.', 'The government has been overthrown.', 'advanced', strftime('%s', 'now')),
('prove', 'proved', 'proved/proven', 'prouver, démontrer', 'She proves her point.', 'She proved the theorem.', 'She has proven her innocence.', 'intermediate', strftime('%s', 'now')),
('quit', 'quit', 'quit', 'quitter, arrêter', 'He quits his job.', 'He quit smoking last year.', 'He has quit the team.', 'intermediate', strftime('%s', 'now')),
('rewind', 'rewound', 'rewound', 'rembobiner', 'She rewinds the tape.', 'She rewound the video.', 'She has rewound the cassette.', 'advanced', strftime('%s', 'now')),
('rid', 'rid', 'rid', 'débarrasser, se débarrasser de', 'She rids the house of pests.', 'She rid herself of doubt.', 'She has rid the garden of weeds.', 'advanced', strftime('%s', 'now')),
('rove', 'roved', 'roved', 'errer, rôder', 'They rove the countryside.', 'They roved the streets.', 'They have roved the forest.', 'advanced', strftime('%s', 'now')),
('saw', 'sawed', 'sawn/sawed', 'scier', 'He saws wood every morning.', 'He sawed the plank.', 'The wood has been sawn.', 'advanced', strftime('%s', 'now')),
('sew', 'sewed', 'sewn/sewed', 'coudre', 'She sews dresses.', 'She sewed a button.', 'She has sewn the hem.', 'intermediate', strftime('%s', 'now')),
('shake', 'shook', 'shaken', 'secouer, trembler', 'She shakes her head.', 'She shook with fear.', 'She has shaken the bottle.', 'intermediate', strftime('%s', 'now')),
('shear', 'sheared', 'shorn/sheared', 'tondre', 'They shear the sheep.', 'They sheared the flock.', 'The sheep have been shorn.', 'advanced', strftime('%s', 'now')),
('shed', 'shed', 'shed', 'verser, perdre (feuilles)', 'Trees shed their leaves.', 'The tree shed its bark.', 'The tree has shed its leaves.', 'advanced', strftime('%s', 'now')),
('slay', 'slew', 'slain', 'tuer, assassiner', 'The hero slays the dragon.', 'The knight slew the beast.', 'The dragon has been slain.', 'advanced', strftime('%s', 'now')),
('slide', 'slid', 'slid', 'glisser', 'Children slide on the ice.', 'She slid across the floor.', 'She has slid into first base.', 'intermediate', strftime('%s', 'now')),
('smell', 'smelled/smelt', 'smelled/smelt', 'sentir, flairer', 'Dogs smell fear.', 'She smelt the flowers.', 'She has smelt the perfume.', 'beginner', strftime('%s', 'now')),
('sow', 'sowed', 'sown/sowed', 'semer', 'Farmers sow seeds in spring.', 'They sowed the field.', 'They have sown the crops.', 'advanced', strftime('%s', 'now')),
('speed', 'sped/speeded', 'sped/speeded', 'accélérer, se presser', 'The car speeds down the road.', 'The car sped past us.', 'The car has sped away.', 'advanced', strftime('%s', 'now')),
('spell', 'spelled/spelt', 'spelled/spelt', 'épeler', 'Children spell their names.', 'She spelt the word correctly.', 'She has spelt every word.', 'beginner', strftime('%s', 'now')),
('spill', 'spilled/spilt', 'spilled/spilt', 'renverser, répandre', 'Don''t spill the milk.', 'She spilt the coffee.', 'She has spilt the water.', 'intermediate', strftime('%s', 'now')),
('spin', 'spun', 'spun', 'filer, tourner', 'Spiders spin webs.', 'She spun the wheel.', 'She has spun the yarn.', 'advanced', strftime('%s', 'now')),
('spread', 'spread', 'spread', 'répandre, étaler', 'They spread the news.', 'They spread the blanket.', 'They have spread the rumor.', 'beginner', strftime('%s', 'now')),
('spring', 'sprang', 'sprung', 'sauter, jaillir, surgir', 'He springs to his feet.', 'He sprang from the chair.', 'He has sprung into action.', 'intermediate', strftime('%s', 'now')),
('stink', 'stank/stunk', 'stunk', 'puer, sentir mauvais', 'The garbage stinks.', 'The room stank of smoke.', 'The room has stunk for days.', 'advanced', strftime('%s', 'now')),
('stride', 'strode', 'stridden', 'marcher à grands pas', 'He strides confidently.', 'He strode across the room.', 'He has stridden forward.', 'advanced', strftime('%s', 'now')),
('strike', 'struck', 'struck', 'frapper, battre', 'The clock strikes noon.', 'He struck the table.', 'He has struck a deal.', 'intermediate', strftime('%s', 'now')),
('string', 'strung', 'strung', 'enfiler, tendre', 'She strings the beads.', 'She strung the lights.', 'She has strung the pearls.', 'advanced', strftime('%s', 'now')),
('strive', 'strove', 'striven', 's''efforcer, tendre vers', 'They strive for excellence.', 'They strove to succeed.', 'They have striven for perfection.', 'advanced', strftime('%s', 'now')),
('swear', 'swore', 'sworn', 'jurer, prêter serment', 'She swears to tell the truth.', 'She swore an oath.', 'She has sworn loyalty.', 'intermediate', strftime('%s', 'now')),
('sweep', 'swept', 'swept', 'balayer, balayer (du regard)', 'She sweeps the floor.', 'She swept the kitchen.', 'She has swept the porch.', 'intermediate', strftime('%s', 'now')),
('swell', 'swelled', 'swollen/swelled', 'gonfler, enfler', 'His ankle swells after the fall.', 'His ankle swelled painfully.', 'His ankle has swollen.', 'advanced', strftime('%s', 'now')),
('swing', 'swung', 'swung', 'balancer, se balancer', 'Children swing on the playground.', 'She swung the bat.', 'She has swung the door open.', 'intermediate', strftime('%s', 'now')),
('tear', 'tore', 'torn', 'déchirer', 'Don''t tear the paper.', 'She tore the letter.', 'The paper has been torn.', 'intermediate', strftime('%s', 'now')),
('thrive', 'throve/thrived', 'thriven/thrived', 'prospérer, s''épanouir', 'Plants thrive in sunlight.', 'The business thrived.', 'The company has thrived.', 'advanced', strftime('%s', 'now')),
('undergo', 'underwent', 'undergone', 'subir, traverser', 'He undergoes surgery.', 'He underwent treatment.', 'He has undergone three operations.', 'advanced', strftime('%s', 'now')),
('understand', 'understood', 'understood', 'comprendre', 'I understand the lesson.', 'I understood the message.', 'I have understood the concept.', 'beginner', strftime('%s', 'now')),
('upset', 'upset', 'upset', 'bouleverser, fâcher', 'The news upsets her.', 'The news upset everyone.', 'She has been upset all day.', 'intermediate', strftime('%s', 'now')),
('weave', 'wove', 'woven', 'tisser', 'She weaves baskets.', 'She wove a rug.', 'She has woven a blanket.', 'advanced', strftime('%s', 'now')),
('weep', 'wept', 'wept', 'pleurer, sangloter', 'She weeps at sad movies.', 'She wept bitterly.', 'She has wept for hours.', 'intermediate', strftime('%s', 'now')),
('wring', 'wrung', 'wrung', 'tordre, tordre (les mains)', 'She wrings the towel.', 'She wrung the wet cloth.', 'She has wrung her hands.', 'advanced', strftime('%s', 'now')),
('writhe', 'writhed', 'writhed', 'se tordre (de douleur)', 'He writhes in pain.', 'He writhed on the floor.', 'He has writhed in agony.', 'advanced', strftime('%s', 'now'));
