-- Phrasal verbs from Bescherelle "Maîtriser la grammaire anglaise"
-- Additional phrasal verbs not already in the database (89 existing checked)
-- Source: Bescherelle chapters on phrasal verbs and verb-preposition combinations

INSERT OR IGNORE INTO phrasal_verbs (verb, particle, meaning, example, level)
VALUES
('ask', 'after', 'demander des nouvelles de quelqu''un', 'She asked after your health.', 'intermediate'),
('ask', 'around', 'demander à plusieurs personnes', 'I''ll ask around and see if anyone knows.', 'intermediate'),
('ask', 'out', 'inviter à sortir', 'He finally asked her out.', 'beginner'),
('back', 'away', 'reculer', 'She backed away from the dog.', 'intermediate'),
('back', 'down', 'céder, renoncer', 'He refused to back down from his position.', 'advanced'),
('back', 'out', 'se dédire, se retirer', 'They backed out of the deal at the last minute.', 'intermediate'),
('back', 'up', 'soutenir, faire une copie de sauvegarde', 'I''ll back you up no matter what.', 'intermediate'),
('blow', 'away', 'épater, éblouir', 'Her performance blew me away.', 'intermediate'),
('blow', 'out', 'éteindre (une flamme), crever (un pneu)', 'The wind blew out the candles.', 'intermediate'),
('blow', 'over', 'se calmer, passer (une tempête)', 'The storm blew over quickly.', 'advanced'),
('blow', 'up', 'exploser, faire exploser', 'The building blew up.', 'beginner'),
('break', 'away', 'se libérer, s''évader', 'The prisoner broke away from the guards.', 'advanced'),
('break', 'in', 'entrer par effraction, interrompre', 'Burglars broke in last night.', 'intermediate'),
('break', 'into', 'entrer par effraction dans', 'They broke into the house.', 'intermediate'),
('break', 'off', 'rompre, cesser (une relation)', 'She broke off the engagement.', 'advanced'),
('break', 'through', 'percer, faire une percée', 'Scientists broke through the barrier.', 'advanced'),
('break', 'up', 'se séparer, rompre', 'They broke up after five years.', 'intermediate'),
('bring', 'about', 'provoquer, causer', 'The changes brought about a revolution.', 'advanced'),
('bring', 'down', 'faire tomber, renverser', 'The scandal brought down the government.', 'advanced'),
('bring', 'forward', 'avancer (une date)', 'They brought the meeting forward.', 'advanced'),
('bring', 'in', 'introduire, rapporter', 'The new policy brought in more revenue.', 'intermediate'),
('bring', 'out', 'sortir, produire, lancer', 'They brought out a new edition.', 'intermediate'),
('bring', 'round', 'convaincre, ramener à la raison', 'She brought him round to her point of view.', 'advanced'),
('brush', 'up', 'réviser, rafraîchir (ses connaissances)', 'I need to brush up my English.', 'intermediate'),
('bump', 'into', 'tomber sur, rencontrer par hasard', 'I bumped into an old friend yesterday.', 'intermediate'),
('burn', 'down', 'brûler complètement', 'The old barn burned down.', 'intermediate'),
('burn', 'out', 's''épuiser (au travail)', 'She burned out after working 80-hour weeks.', 'advanced'),
('call', 'off', 'annuler', 'They called off the wedding.', 'intermediate'),
('call', 'on', 'rendre visite, faire appel à', 'We called on our neighbors.', 'intermediate'),
('call', 'up', 'téléphoner, rappeler', 'He called up his mother.', 'beginner'),
('calm', 'down', 'se calmer', 'Calm down, everything will be fine.', 'beginner'),
('carry', 'out', 'exécuter, réaliser', 'They carried out the experiment.', 'intermediate'),
('catch', 'on', 'comprendre, devenir populaire', 'The new trend caught on quickly.', 'intermediate'),
('check', 'over', 'vérifier, examiner', 'She checked over the document.', 'intermediate'),
('cheer', 'up', 'remonter le moral', 'Cheer up! Things will get better.', 'beginner'),
('clear', 'away', 'débarrasser, ranger', 'She cleared away the dishes.', 'intermediate'),
('clear', 'out', 'vider, partir', 'He cleared out his desk.', 'intermediate'),
('clear', 'up', 'éclaircir, ranger, se dissiper', 'The weather cleared up in the afternoon.', 'intermediate'),
('close', 'down', 'fermer définitivement', 'The factory closed down.', 'intermediate'),
('close', 'in', 'se rapprocher, resserrer', 'The police closed in on the suspect.', 'advanced'),
('come', 'about', 'se produire, arriver', 'How did this situation come about?', 'advanced'),
('come', 'down with', 'attraper (une maladie)', 'She came down with the flu.', 'intermediate'),
('come', 'off', 'se détacher, réussir', 'The button came off my shirt.', 'intermediate'),
('come', 'round', 'se rendre, changer d''avis, venir', 'She came round to our way of thinking.', 'advanced'),
('come', 'to', 'revenir à soi, se chiffrer à', 'He came to after fainting.', 'intermediate'),
('count', 'on', 'compter sur', 'You can count on me.', 'beginner'),
('count', 'out', 'exclure', 'Don''t count me out yet.', 'intermediate'),
('cross', 'out', 'rayer, barrer', 'She crossed out the wrong answer.', 'intermediate'),
('cut', 'across', 'couper à travers', 'We cut across the park.', 'intermediate'),
('cut', 'in', 'couper la parole, doubler', 'She cut in while he was speaking.', 'intermediate'),
('cut', 'off', 'couper, déconnecter', 'The operator cut me off.', 'intermediate'),
('cut', 'out', 'découper, supprimer', 'She cut out the article.', 'intermediate'),
('cut', 'up', 'couper en morceaux', 'She cut up the vegetables.', 'beginner'),
('do', 'away with', 'supprimer, se débarrasser de', 'They did away with the old rules.', 'advanced'),
('do', 'over', 'refaire, repeindre', 'She did over the living room.', 'intermediate'),
('do', 'without', 'se passer de', 'I can''t do without my morning coffee.', 'intermediate'),
('draw', 'back', 'reculer', 'She drew back in fear.', 'advanced'),
('draw', 'out', 'prolonger, tirer de (quelqu''un)', 'The meeting drew out for hours.', 'advanced'),
('draw', 'up', 'rédiger, établir', 'They drew up a contract.', 'advanced'),
('dress', 'down', 's''habiller simplement, réprimander', 'She dressed down for the occasion.', 'intermediate'),
('dress', 'up', 's''habiller élégamment', 'She dressed up for the party.', 'beginner'),
('drink', 'up', 'boire jusqu''au bout', 'Drink up! It''s time to go.', 'beginner'),
('drive', 'away', 'chasser, faire partir', 'The noise drove away the birds.', 'intermediate'),
('drop', 'by', 'passer voir, faire un saut', 'Drop by anytime you''re in town.', 'intermediate'),
('drop', 'in', 'passer voir (sans prévenir)', 'She dropped in for a chat.', 'intermediate'),
('drop', 'out', 'abandonner (études, projet)', 'He dropped out of college.', 'intermediate'),
('eat', 'out', 'manger au restaurant', 'We eat out every Friday.', 'beginner'),
('eat', 'up', 'tout manger, finir son assiette', 'Eat up your vegetables!', 'beginner'),
('face', 'up to', 'affronter, faire face à', 'You must face up to reality.', 'advanced'),
('fall', 'apart', 'se désintégrer, tomber en morceaux', 'The old book fell apart.', 'intermediate'),
('fall', 'behind', 'prendre du retard', 'She fell behind in her studies.', 'intermediate'),
('fall', 'down', 'tomber, s''effondrer', 'The old wall fell down.', 'beginner'),
('fall', 'for', 'tomber amoureux de, se faire avoir', 'He fell for her immediately.', 'intermediate'),
('feel', 'up to', 'se sentir capable de', 'I don''t feel up to going out tonight.', 'intermediate'),
('fill', 'in', 'remplir, compléter', 'Fill in this form, please.', 'beginner'),
('find', 'around to', 'trouver le temps de', 'I finally got around to calling her.', 'advanced'),
('get', 'across', 'faire passer (un message)', 'She got her point across clearly.', 'intermediate'),
('get', 'at', 'atteindre, sous-entendre', 'What are you getting at?', 'advanced'),
('get', 'away', 's''échapper, partir', 'The thief got away.', 'intermediate'),
('get', 'back', 'récupérer, revenir', 'I got my book back.', 'beginner'),
('get', 'behind', 'prendre du retard', 'He got behind with the rent.', 'intermediate'),
('get', 'by', 'se débrouiller, s''en sortir', 'We can get by on one salary.', 'intermediate'),
('get', 'down', 'déprimer, descendre', 'The news got her down.', 'intermediate'),
('get', 'down to', 'se mettre sérieusement à', 'Let''s get down to business.', 'intermediate'),
('get', 'off', 'descendre de, éviter une punition', 'She got off the bus.', 'beginner'),
('get', 'on', 'monter dans, progresser, s''entendre', 'Get on the train quickly.', 'beginner'),
('get', 'out', 'sortir, partir', 'Get out of here!', 'beginner'),
('get', 'over', 'se remettre de, surmonter', 'She got over her illness.', 'intermediate'),
('get', 'through', 'traverser, passer (un examen), joindre', 'I got through the exam.', 'intermediate'),
('get', 'together', 'se réunir', 'Let''s get together next week.', 'intermediate'),
('give', 'away', 'donner, révéler', 'She gave away the secret.', 'intermediate'),
('give', 'in', 'céder, se rendre', 'He gave in to pressure.', 'intermediate'),
('give', 'out', 'distribuer, s''épuiser', 'The teacher gave out the worksheets.', 'intermediate'),
('go', 'ahead', 'continuer, aller de l''avant', 'Go ahead, I''m listening.', 'beginner'),
('go', 'away', 'partir, s''éloigner', 'Go away and leave me alone!', 'beginner'),
('go', 'down', 'descendre, baisser', 'Prices went down last month.', 'beginner'),
('go', 'in for', 'pratiquer, participer à', 'She goes in for swimming.', 'advanced'),
('go', 'off', 'partir, exploser, se déclencher', 'The alarm went off at 6 AM.', 'intermediate'),
('go', 'on', 'continuer, se passer', 'Go on, tell me more!', 'beginner'),
('go', 'out', 'sortir, s''éteindre', 'They go out every Saturday.', 'beginner'),
('go', 'through', 'traverser, examiner', 'She went through her notes.', 'intermediate'),
('go', 'without', 'se passer de', 'We had to go without electricity.', 'intermediate'),
('grow', 'apart', 's''éloigner l''un de l''autre', 'They grew apart over the years.', 'advanced'),
('grow', 'out of', 'trop grand pour, se défaire d''une habitude', 'She grew out of her clothes.', 'intermediate'),
('grow', 'up', 'grandir, devenir adulte', 'She grew up in Paris.', 'beginner'),
('hand', 'down', 'transmettre, léguer', 'The necklace was handed down.', 'advanced'),
('hand', 'in', 'remettre, rendre (un devoir)', 'Hand in your homework tomorrow.', 'beginner'),
('hand', 'out', 'distribuer', 'She handed out flyers.', 'intermediate'),
('hand', 'over', 'remettre, céder', 'He handed over the keys.', 'intermediate'),
('hang', 'around', 'traîner, rôder', 'He hangs around the café.', 'intermediate'),
('hang', 'on', 'attendre, s''accrocher', 'Hang on a second!', 'beginner'),
('hang', 'out', 'traîner, passer du temps', 'We hang out at the mall.', 'intermediate'),
('have', 'on', 'porter (vêtements)', 'She had a red dress on.', 'beginner'),
('head', 'back', 'revenir, faire demi-tour', 'We headed back home.', 'intermediate'),
('hear', 'from', 'recevoir des nouvelles de', 'I haven''t heard from her lately.', 'intermediate'),
('hear', 'out', 'écouter jusqu''au bout', 'Hear me out before you decide.', 'intermediate'),
('hit', 'back', 'riposter', 'She hit back at the criticism.', 'advanced'),
('hit', 'on', 'trouver par hasard, draguer', 'He hit on a great idea.', 'advanced'),
('hold', 'back', 'retenir, freiner', 'She held back her tears.', 'intermediate'),
('hold', 'off', 'repousser, retarder', 'The rain held off until evening.', 'advanced'),
('hold', 'out', 'tenir bon, résister', 'They held out for better conditions.', 'intermediate'),
('hold', 'together', 'tenir ensemble, rester uni', 'The family held together.', 'intermediate'),
('iron', 'out', 'résoudre, aplanir', 'We need to iron out the details.', 'advanced'),
('join', 'in', 'participer, se joindre', 'She joined in the conversation.', 'intermediate'),
('join', 'up', 's''engager, se joindre', 'He joined up at eighteen.', 'intermediate'),
('keep', 'away', 'tenir éloigné', 'Keep away from the edge!', 'intermediate'),
('keep', 'down', 'maintenir bas, réprimer', 'Keep the noise down.', 'intermediate'),
('keep', 'from', 's''empêcher de', 'She couldn''t keep from laughing.', 'intermediate'),
('keep', 'off', 'rester éloigné de', 'Keep off the grass.', 'intermediate'),
('keep', 'on', 'continuer à', 'She kept on talking.', 'intermediate'),
('keep', 'out', 'empêcher d''entrer', 'The sign says "Keep out!".', 'intermediate'),
('keep', 'to', 's''en tenir à, respecter', 'Keep to the plan.', 'intermediate'),
('knock', 'down', 'renverser, démolir', 'The old building was knocked down.', 'intermediate'),
('knock', 'out', 'assommer, éliminer', 'He was knocked out in the first round.', 'intermediate'),
('knock', 'over', 'renverser', 'She knocked over the vase.', 'intermediate'),
('lay', 'down', 'déposer, établir (règles)', 'She laid down the law.', 'intermediate'),
('lay', 'off', 'licencier', 'The company laid off 200 workers.', 'intermediate'),
('lay', 'out', 'disposer, présenter', 'She laid out the plan.', 'advanced'),
('lead', 'on', 'faire espérer, induire en erreur', 'He was leading her on.', 'advanced'),
('lead', 'to', 'mener à, conduire à', 'Hard work leads to success.', 'beginner'),
('leave', 'behind', 'laisser derrière, oublier', 'She left behind her umbrella.', 'intermediate'),
('leave', 'out', 'omettre, exclure', 'She left out an important detail.', 'intermediate'),
('let', 'down', 'décevoir', 'Don''t let me down.', 'intermediate'),
('let', 'in', 'laisser entrer', 'She let in the cat.', 'beginner'),
('let', 'out', 'laisser sortir, relâcher', 'She let out a sigh.', 'intermediate'),
('lie', 'down', 's''allonger', 'I need to lie down for a while.', 'beginner'),
('live', 'down', 'survivre à (une honte)', 'He''ll never live it down.', 'advanced'),
('live', 'up to', 'être à la hauteur de', 'She lived up to expectations.', 'advanced'),
('look', 'down on', 'mépriser, regarder de haut', 'She looks down on lazy people.', 'intermediate'),
('look', 'into', 'examiner, enquêter sur', 'The police are looking into the matter.', 'intermediate'),
('look', 'over', 'examiner, parcourir', 'She looked over the report.', 'intermediate'),
('look', 'through', 'parcourir, feuilleter', 'She looked through the documents.', 'intermediate'),
('look', 'up to', 'admirer, respecter', 'She looks up to her mother.', 'intermediate'),
('make', 'for', 'se diriger vers', 'She made for the exit.', 'intermediate'),
('make', 'out', 'distinguer, comprendre, rédiger', 'I can''t make out the writing.', 'intermediate'),
('make', 'up for', 'compenser', 'She made up for lost time.', 'intermediate'),
('move', 'in', 'emménager', 'They moved in last week.', 'beginner'),
('move', 'out', 'déménager, partir', 'She moved out of her apartment.', 'beginner'),
('pass', 'away', 'décéder', 'Her grandfather passed away.', 'intermediate'),
('pass', 'out', 's''évanouir', 'He passed out from the heat.', 'intermediate'),
('pay', 'back', 'rembourser, se venger', 'I''ll pay you back tomorrow.', 'beginner'),
('pay', 'off', 'rembourser, payer (un pot-de-vin)', 'She paid off her debts.', 'intermediate'),
('pick', 'out', 'choisir, distinguer', 'She picked out a dress.', 'intermediate'),
('point', 'out', 'signaler, faire remarquer', 'She pointed out the mistake.', 'intermediate'),
('pull', 'down', 'démolir', 'They pulled down the old wall.', 'intermediate'),
('pull', 'off', 'réussir (un exploit)', 'She pulled off a surprise party.', 'advanced'),
('pull', 'out', 'se retirer, sortir', 'She pulled out a notebook.', 'intermediate'),
('pull', 'up', 's''arrêter (véhicule), se redresser', 'The car pulled up at the lights.', 'intermediate'),
('push', 'around', 'brimer, malmener', 'Don''t let them push you around.', 'intermediate'),
('push', 'on', 'continuer, presser', 'We pushed on despite the rain.', 'advanced'),
('put', 'across', 'faire comprendre', 'She put her ideas across clearly.', 'advanced'),
('put', 'aside', 'mettre de côté', 'She put aside some money.', 'intermediate'),
('put', 'away', 'ranger', 'Put away your toys!', 'beginner'),
('put', 'down', 'poser, déposer, euthanasier', 'She put down the bag.', 'intermediate'),
('put', 'forward', 'proposer, avancer', 'She put forward a new theory.', 'advanced'),
('put', 'out', 'éteindre, sortir', 'She put out the fire.', 'intermediate'),
('put', 'together', 'assembler', 'She put the puzzle together.', 'intermediate'),
('read', 'over', 'parcourir, relire', 'She read over the contract.', 'intermediate'),
('read', 'up on', 'se renseigner sur', 'She read up on the topic.', 'advanced'),
('rip', 'off', 'arnaquer, voler', 'They ripped me off.', 'intermediate'),
('roll', 'over', 'se retourner', 'The dog rolled over.', 'beginner'),
('rule', 'out', 'exclure, écarter', 'The police ruled out foul play.', 'intermediate'),
('run', 'after', 'poursuivre, courir après', 'She ran after the bus.', 'intermediate'),
('run', 'away', 's''enfuir, fuir', 'The boy ran away from home.', 'beginner'),
('run', 'down', 'renverser, épuiser, critiquer', 'She was run down by a car.', 'intermediate'),
('run', 'off', 's''enfuir, imprimer', 'She ran off with the money.', 'intermediate'),
('run', 'over', 'écraser, répéter', 'She ran over her notes.', 'intermediate'),
('run', 'through', 'parcourir, répéter', 'She ran through the presentation.', 'intermediate'),
('save', 'up', 'économiser', 'She is saving up for a car.', 'beginner'),
('sell', 'out', 'tout vendre, trahir', 'The concert sold out.', 'intermediate'),
('send', 'away', 'renvoyer, expédier', 'She sent away for a catalogue.', 'intermediate'),
('send', 'back', 'renvoyer, retourner', 'She sent back the package.', 'intermediate'),
('send', 'for', 'faire venir, appeler', 'She sent for a doctor.', 'intermediate'),
('send', 'out', 'envoyer, expédier', 'She sent out invitations.', 'intermediate'),
('set', 'about', 'commencer à', 'She set about cleaning the house.', 'advanced'),
('set', 'aside', 'mettre de côté, réserver', 'She set aside time for reading.', 'intermediate'),
('set', 'back', 'retarder, reculer', 'The storm set back the project.', 'advanced'),
('set', 'in', 's''installer (mauvais temps)', 'Winter set in early.', 'advanced'),
('set', 'on', 'attaquer, inciter', 'The dog was set on the intruder.', 'advanced'),
('settle', 'down', 'se stabiliser, s''installer', 'They settled down in the countryside.', 'intermediate'),
('settle', 'up', 'régler (une note)', 'Let me settle up with you.', 'intermediate'),
('show', 'around', 'faire visiter', 'She showed us around the campus.', 'intermediate'),
('show', 'up', 'arriver, se présenter', 'She showed up late.', 'intermediate'),
('shut', 'down', 'fermer, arrêter', 'The computer shut down.', 'intermediate'),
('shut', 'up', 'taire, se taire', 'Shut up! I''m trying to think.', 'beginner'),
('sit', 'around', 'rester assis à ne rien faire', 'We sat around waiting.', 'intermediate'),
('sit', 'back', 's''installer confortablement, se détendre', 'Sit back and relax.', 'intermediate'),
('sit', 'out', 's''abstenir, ne pas participer', 'She sat out the last dance.', 'intermediate'),
('slow', 'down', 'ralentir', 'Slow down! You''re driving too fast.', 'beginner'),
('snap', 'out of', 'sortir de (un état)', 'Snap out of it!', 'advanced'),
('sort', 'through', 'trier, examiner', 'She sorted through the papers.', 'intermediate'),
('split', 'up', 'se séparer, diviser', 'They split up after two years.', 'intermediate'),
('spread', 'out', 's''étaler, se disperser', 'She spread out the map.', 'intermediate'),
('stand', 'by', 'rester fidèle, être prêt', 'I''ll stand by you.', 'intermediate'),
('stand', 'for', 'représenter, tolérer', 'What does UN stand for?', 'intermediate'),
('stand', 'out', 'se démarquer', 'She stands out in a crowd.', 'intermediate'),
('stand', 'up for', 'défendre', 'She stood up for her rights.', 'intermediate'),
('stay', 'behind', 'rester (après les autres)', 'She stayed behind to help.', 'intermediate'),
('stay', 'out', 'rester dehors, rentrer tard', 'She stayed out late last night.', 'intermediate'),
('stay', 'up', 'rester éveillé', 'She stayed up all night studying.', 'beginner'),
('step', 'aside', 's''écarter, se retirer', 'He stepped aside for his successor.', 'advanced'),
('step', 'down', 'démissionner', 'The CEO stepped down.', 'intermediate'),
('stick', 'around', 'rester dans les parages', 'Stick around, I''ll be right back.', 'intermediate'),
('stick', 'out', 'dépasser, résister', 'She stuck out her tongue.', 'intermediate'),
('stick', 'to', 's''en tenir à, persévérer', 'Stick to your principles.', 'intermediate'),
('stick', 'up for', 'défendre', 'She stuck up for her brother.', 'intermediate'),
('stop', 'by', 'passer voir', 'I''ll stop by later.', 'intermediate'),
('switch', 'off', 'éteindre', 'Switch off the lights.', 'beginner'),
('switch', 'on', 'allumer', 'Switch on the TV.', 'beginner'),
('take', 'apart', 'démonter', 'He took apart the engine.', 'intermediate'),
('take', 'back', 'reprendre, retourner', 'She took back her words.', 'intermediate'),
('take', 'down', 'noter, descendre', 'She took down the notes.', 'intermediate'),
('take', 'over', 'prendre le contrôle, reprendre', 'She took over the company.', 'intermediate'),
('take', 'to', 'se mettre à, avoir un penchant pour', 'She took to swimming quickly.', 'intermediate'),
('take', 'up', 'commencer (une activité), occuper', 'She took up yoga.', 'intermediate'),
('talk', 'back', 'répondre, répliquer', 'Don''t talk back to your mother!', 'intermediate'),
('talk', 'over', 'discuter de', 'Let''s talk it over.', 'intermediate'),
('tear', 'down', 'démolir', 'They tore down the old building.', 'intermediate'),
('tear', 'up', 'déchirer en morceaux', 'She tore up the letter.', 'intermediate'),
('tell', 'apart', 'distinguer, différencier', 'I can''t tell them apart.', 'intermediate'),
('tell', 'off', 'réprimander', 'She told him off for being late.', 'intermediate'),
('think', 'over', 'réfléchir à', 'Let me think it over.', 'intermediate'),
('think', 'up', 'inventer, imaginer', 'She thought up a clever plan.', 'intermediate'),
('throw', 'away', 'jeter', 'Don''t throw away that box!', 'beginner'),
('throw', 'out', 'jeter, expulser', 'She threw out the old magazines.', 'intermediate'),
('tidy', 'up', 'ranger', 'Tidy up your room!', 'beginner'),
('tire', 'out', 'épuiser', 'The hike tired us out.', 'intermediate'),
('touch', 'up', 'retoucher, améliorer', 'She touched up the painting.', 'advanced'),
('track', 'down', 'retrouver, localiser', 'She tracked down the reference.', 'intermediate'),
('try', 'out', 'essayer, tester', 'She tried out the new car.', 'intermediate'),
('turn', 'away', 'refuser l''entrée, renvoyer', 'They turned away the beggar.', 'intermediate'),
('turn', 'back', 'faire demi-tour', 'We had to turn back.', 'intermediate'),
('turn', 'in', 'aller se coucher, remettre', 'She turned in early last night.', 'intermediate'),
('turn', 'over', 'retourner, céder', 'She turned over the page.', 'intermediate'),
('use', 'up', 'épuiser, consommer', 'She used up all the milk.', 'intermediate'),
('vote', 'down', 'rejeter (un projet)', 'The proposal was voted down.', 'advanced'),
('wait', 'around', 'patienter', 'We waited around for an hour.', 'intermediate'),
('wait', 'on', 'servir, attendre', 'She waited on tables.', 'intermediate'),
('walk', 'away', 'partir, s''en aller', 'She walked away from the argument.', 'intermediate'),
('walk', 'out', 'sortir en signe de protestation', 'They walked out of the meeting.', 'intermediate'),
('wash', 'away', 'emporter (par l''eau)', 'The flood washed away the bridge.', 'intermediate'),
('wash', 'out', 'laver, annuler (un événement)', 'The game was washed out.', 'intermediate'),
('wash', 'up', 'faire la vaisselle, s''échouer', 'She washed up the dishes.', 'beginner'),
('watch', 'out', 'faire attention', 'Watch out for the step!', 'beginner'),
('wear', 'down', 'user, épuiser', 'The stairs have worn down.', 'intermediate'),
('wear', 'out', 'user, épuiser', 'The shoes wore out quickly.', 'intermediate'),
('wind', 'down', 'se détendre, se déstresser', 'She wound down with a book.', 'intermediate'),
('wind', 'up', 'terminer, finir par', 'The meeting wound up late.', 'intermediate'),
('wipe', 'out', 'détruire complètement, anéantir', 'The disease wiped out the population.', 'advanced'),
('work', 'out', 'résoudre, faire de l''exercice', 'Things worked out in the end.', 'intermediate'),
('work', 'up', 'développer, monter (en puissance)', 'She worked up a sweat.', 'intermediate');
