-- Grammar lessons from Vocable Anglais (Juin 2025)
-- Topics: Passive Voice, Modal Verbs of Deduction, Future Perfect & Future Continuous

INSERT OR IGNORE INTO grammar_lessons (id, title, slug, description, content, category, level, order_index, created_at) VALUES
(118, 'La voix passive', 'vocable-passive-voice', 'La voix passive met l''accent sur l''action plutôt que sur l''agent qui la réalise.', '<h3>Formation</h3><p><b>be + participe passé</b></p><ul><li><i>The book was written by a famous author.</i></li><li><i>The house is being painted.</i></li><li><i>The decision has been made.</i></li></ul><h3>Transitions de temps</h3><ul><li>Present simple → <i>is/are + done</i> : The report is written every month.</li><li>Past simple → <i>was/were + done</i> : The report was written last month.</li><li>Present perfect → <i>has/have been + done</i> : The report has been written.</li><li>Future → <i>will be + done</i> : The report will be written tomorrow.</li><li>Modal → <i>modal + be + done</i> : The report must be written today.</li></ul><h3>Astuce</h3><p>On utilise <i>by</i> pour mentionner l''agent : <i>The painting was created by Picasso.</i> Quand l''agent est évident ou inconnu, on l''omet.</p>', 'voix_passive', 'B1', 118, 1718380800000),
(119, 'Modaux de déduction', 'vocable-modal-verbs-deduction', 'Les modaux de déduction expriment la certitude, la probabilité ou la possibilité.', '<h3>Déduction au présent</h3><ul><li><b>Must</b> (certitude) : <i>She must be at home — the lights are on.</i></li><li><b>Can''t</b> (impossibilité) : <i>He can''t be tired — he just woke up.</i></li><li><b>May/Might/Could</b> (possibilité) : <i>It might rain later.</i></li><li><b>Should</b> (probabilité logique) : <i>They should arrive by noon.</i></li></ul><h3>Déduction au passé</h3><ul><li><b>Must have + participe passé</b> : <i>She must have forgotten about the meeting.</i></li><li><b>Can''t have + participe passé</b> : <i>He can''t have done it alone.</i></li><li><b>May/Might/Could have + participe passé</b> : <i>They might have missed the train.</i></li><li><b>Should have + participe passé</b> : <i>You should have told me earlier.</i></li></ul><h3>Astuce</h3><p><i>Must</i> exprime une certitude positive, <i>can''t</i> une certitude négative. <i>May/might/could</i> expriment une simple possibilité, sans certitude.</p>', 'modaux', 'B2', 119, 1718380800000),
(120, 'Future Perfect & Future Continuous', 'vocable-future-perfect-continuous', 'Le future perfect décrit une action achevée dans le futur, le future continuous une action en cours.', '<h3>Future Perfect</h3><p><b>will have + participe passé</b></p><ul><li><i>By next year, I will have graduated.</i></li><li><i>She will have finished the report by 5 p.m.</i></li></ul><p>Usage : indiquer qu''une action sera terminée avant un point précis du futur. Souvent utilisé avec <i>by</i> (by tomorrow, by next week, by 2030).</p><h3>Future Continuous</h3><p><b>will be + verbe-ing</b></p><ul><li><i>This time tomorrow, I will be flying to Tokyo.</i></li><li><i>At 10 a.m., she will be giving a presentation.</i></li></ul><p>Usage : décrire une action qui sera en cours de déroulement à un moment précis du futur.</p><h3>Comparaison</h3><ul><li>Future perfect : action <b>achevée</b> avant un point futur.</li><li>Future continuous : action <b>en cours</b> à un point futur.</li></ul>', 'temps_verbaux', 'B2', 120, 1718380800000);

-- Exercises for lessons 118-120
INSERT OR IGNORE INTO grammar_exercises (lesson_id, type, question, options, correct_answer, explanation, points, order_index) VALUES
-- Lesson 118: Passive Voice
(118, 'qcm', 'The book ___ by a famous author.', '["writes", "was written", "is writing", "wrote"]', 'was written', 'Passif au past simple → was/were + participe passé', 1, 1),
(118, 'fill_blank', 'The report ___ (write) every month.', NULL, 'is written', 'Passif au present simple → is/are + participe passé', 1, 2),
(118, 'qcm', 'The decision ___ yet.', '["has not been made", "has not made", "is not made", "was not made"]', 'has not been made', 'Passif au present perfect → has/have been + participe passé', 1, 3),
(118, 'fill_blank', 'The house ___ (paint) at the moment.', NULL, 'is being painted', 'Passif au present continuous → is/are being + participe passé', 1, 4),
(118, 'qcm', 'The report ___ by tomorrow.', '["will write", "will be written", "will written", "will be writing"]', 'will be written', 'Passif au futur → will be + participe passé', 1, 5),
-- Lesson 119: Modal verbs of deduction
(119, 'qcm', 'The lights are on. She ___ at home.', '["must be", "can be", "must being", "could being"]', 'must be', 'Must + base verbale → certitude au présent', 1, 1),
(119, 'qcm', 'He just woke up. He ___ tired.', '["must be", "can''t be", "should be", "may be"]', 'can''t be', 'Can''t + base verbale → impossibilité au présent', 1, 2),
(119, 'fill_blank', 'She didn''t answer. She ___ (must/forget) about the meeting.', NULL, 'must have forgotten', 'Must have + participe passé → certitude au passé', 1, 3),
(119, 'qcm', 'They ___ the train — it''s only 8 a.m.', '["might miss", "might have missed", "must miss", "can''t have missed"]', 'can''t have missed', 'Can''t have + participe passé → impossibilité au passé', 1, 4),
(119, 'fill_blank', 'You ___ (should/tell) me earlier.', NULL, 'should have told', 'Should have + participe passé → regret/critique rétrospective', 1, 5),
-- Lesson 120: Future Perfect & Future Continuous
(120, 'qcm', 'By next year, I ___ graduated.', '["will", "will have", "will be", "will having"]', 'will have', 'Future perfect → will have + participe passé', 1, 1),
(120, 'fill_blank', 'By 5 p.m., she ___ (finish) the report.', NULL, 'will have finished', 'Future perfect → action achevée avant un point futur', 1, 2),
(120, 'qcm', 'This time tomorrow, I ___ to Tokyo.', '["will fly", "will be flying", "will have flown", "fly"]', 'will be flying', 'Future continuous → will be + verbe-ing (action en cours)', 1, 3),
(120, 'fill_blank', 'At 10 a.m., she ___ (give) a presentation.', NULL, 'will be giving', 'Future continuous → action en cours à un moment futur', 1, 4),
(120, 'qcm', 'By 2030, scientists ___ a cure.', '["will find", "will be finding", "will have found", "will have been finding"]', 'will have found', 'Future perfect → action achevée avant un point futur (by 2030)', 1, 5);
