-- Translation exercises extracted from Vocable Anglais articles (Juin 2025)
-- Source: Bilingual articles from News Digest pages

INSERT OR IGNORE INTO translation_exercises (title, source, translation, difficulty, category, word_count) VALUES
-- p31: Artificial Intelligence in Everyday Life
('IA au quotidien', 'Artificial intelligence is no longer confined to research labs; it has become an integral part of our daily lives. From voice assistants to recommendation algorithms, AI shapes how we shop, work, and communicate.', 'L''intelligence artificielle n''est plus confinée aux laboratoires de recherche ; elle est devenue une partie intégrante de notre vie quotidienne. Des assistants vocaux aux algorithmes de recommandation, l''IA façonne la façon dont nous faisons nos achats, travaillons et communiquons.', 'hard', 'technologie', 30),
('Éthique et IA', 'The rapid adoption of AI raises important ethical questions about privacy, bias, and accountability. Regulators are struggling to keep pace with technological advancements that seem to outstrip legislation.', 'L''adoption rapide de l''IA soulève d''importantes questions éthiques sur la confidentialité, les biais et la responsabilité. Les régulateurs peinent à suivre le rythme des avancées technologiques qui semblent dépasser la législation.', 'hard', 'technologie', 27),
-- p32: The Green Energy Transition
('Transition énergétique', 'The transition to green energy is accelerating as countries invest heavily in solar and wind power infrastructure. Many governments have set ambitious targets to achieve carbon neutrality within the next two decades.', 'La transition vers les énergies vertes s''accélère alors que les pays investissent massivement dans les infrastructures solaires et éoliennes. De nombreux gouvernements se sont fixé des objectifs ambitieux pour atteindre la neutralité carbone d''ici les deux prochaines décennies.', 'hard', 'environnement', 31),
('Transition juste', 'Critics argue that the transition must be just, ensuring that workers in fossil fuel industries are not left behind. Retraining programmes and financial support are essential for affected communities.', 'Les critiques affirment que la transition doit être juste, en veillant à ce que les travailleurs des industries fossiles ne soient pas laissés pour compte. Les programmes de reconversion et le soutien financier sont essentiels pour les communautés touchées.', 'hard', 'environnement', 28),
-- p33: The Rise of Remote Work
('Télétravail et flexibilité', 'Remote work has fundamentally changed the way companies operate, offering employees unprecedented flexibility. While many workers appreciate the absence of a daily commute, others struggle with isolation and blurred boundaries.', 'Le télétravail a fondamentalement changé la façon dont les entreprises fonctionnent, offrant aux employés une flexibilité sans précédent. Si de nombreux travailleurs apprécient l''absence de trajet quotidien, d''autres luttent contre l''isolement et les frontières floues entre vie pro et perso.', 'hard', 'travail', 32),
('Modèles hybrides', 'Hybrid models have emerged as a compromise, combining the benefits of office collaboration with home-based focus. Companies are investing in digital tools to bridge the gap between remote and in-person teams.', 'Les modèles hybrides sont apparus comme un compromis, combinant les avantages de la collaboration au bureau avec la concentration à domicile. Les entreprises investissent dans des outils numériques pour combler le fossé entre les équipes à distance et en présentiel.', 'hard', 'travail', 30),
-- p34: Mental Health in the Modern Workplace
('Santé mentale au travail', 'Mental health has become a priority for forward-thinking companies that recognise the cost of employee burnout. Employers are introducing wellness programmes that include mindfulness sessions, flexible hours, and mental health days.', 'La santé mentale est devenue une priorité pour les entreprises visionnaires qui reconnaissent le coût de l''épuisement professionnel des employés. Les employeurs introduisent des programmes de bien-être qui incluent des séances de pleine conscience, des horaires flexibles et des jours de santé mentale.', 'hard', 'santé', 33),
('Stigmatisation persistante', 'Despite these efforts, stigma around mental health issues persists in many professional environments. Open conversations and leadership commitment are key to creating a culture of acceptance and support.', 'Malgré ces efforts, la stigmatisation des problèmes de santé mentale persiste dans de nombreux environnements professionnels. Des conversations ouvertes et l''engagement des dirigeants sont essentiels pour créer une culture d''acceptation et de soutien.', 'hard', 'santé', 28),
-- p35: The Future of Public Transport
('Transports publics durables', 'Cities around the world are reimagining public transport to reduce congestion and lower carbon emissions. Electric buses and trams are replacing diesel fleets, while bike-sharing schemes encourage cleaner commutes.', 'Les villes du monde entier réinventent les transports publics pour réduire la congestion et diminuer les émissions de carbone. Les bus et tramways électriques remplacent les flottes diesel, tandis que les systèmes de vélos en libre-service encouragent des trajets plus propres.', 'hard', 'environnement', 31),
('Villes vivables', 'Investment in public transport is seen as essential for creating sustainable and livable urban environments. Affordable and efficient transport systems reduce inequality and improve quality of life for all residents.', 'L''investissement dans les transports publics est considéré comme essentiel pour créer des environnements urbains durables et vivables. Des systèmes de transport abordables et efficaces réduisent les inégalités et améliorent la qualité de vie de tous les habitants.', 'hard', 'environnement', 29),
-- p50: Cultural Heritage in the Digital Age
('Patrimoine numérique', 'Digital technology is transforming how we preserve and experience cultural heritage around the world. Virtual reality allows people to explore museums and historical sites from the comfort of their homes.', 'La technologie numérique transforme la façon dont nous préservons et vivons le patrimoine culturel dans le monde entier. La réalité virtuelle permet aux gens d''explorer des musées et des sites historiques depuis le confort de leur domicile.', 'hard', 'culture', 30),
('Compléter, non remplacer', 'Experts warn that digital replicas should complement, not replace, the experience of visiting cultural sites in person. The authenticity of physical heritage remains irreplaceable and must be protected.', 'Les experts avertissent que les répliques numériques devraient compléter, et non remplacer, l''expérience de visiter les sites culturels en personne. L''authenticité du patrimoine physique reste irremplaçable et doit être protégée.', 'hard', 'culture', 27),
-- p52: The Space Economy
('Économie spatiale', 'The space economy is growing rapidly as private companies launch satellites and develop new technologies. Space tourism is no longer science fiction, with several companies offering suborbital flights to paying customers.', 'L''économie spatiale croît rapidement alors que des entreprises privées lancent des satellites et développent de nouvelles technologies. Le tourisme spatial n''est plus de la science-fiction, plusieurs entreprises proposant des vols suborbitaux à des clients payants.', 'hard', 'science', 31),
('Réglementation spatiale', 'The commercialisation of space raises questions about regulation, sustainability, and the preservation of orbital environments. International cooperation is needed to ensure that space remains a shared resource for humanity.', 'La commercialisation de l''espace soulève des questions sur la réglementation, la durabilité et la préservation des environnements orbitaux. Une coopération internationale est nécessaire pour garantir que l''espace reste une ressource partagée pour l''humanité.', 'hard', 'science', 28);
